const animeData = {
    "anime": [
        {"name": "Solo Leveling Season 2 -Arise from the Shadow-", "url": "index.html"},
        {"name": "The Apothecary Diaries Season 2", "url": "index.html"},
        {"name": "Dr. STONE SCIENCE FUTURE", "url": "index.html"},
        {"name": "Medalist", "url": "index.html"},
        {"name": "I Left My A-Rank Party to Help My Former Students Reach the Dungeon Depths!", "url": "index.html"},
        {"name": "I May Be a Guild Receptionist, but I’ll Solo Any Boss to Clock Out on Time", "url": "index.html"},
        {"name": "Re:ZERO -Starting Life in Another World- Season 3", "url": "index.html"},
        {"name": "SAKAMOTO DAYS", "url": "index.html"},
        {"name": "ONE PIECE", "url": "index.html"},
        {"name": "Blue Box", "url": "index.html"},
        {"name": "One Piece Log: Fish-Man Island Saga", "url": "index.html"},
        {"name": "Solo Leveling", "url": "index.html"},
        {"name": "Orb: On the Movements of the Earth", "url": "index.html"},
        {"name": "I'm the Evil Lord of an Intergalactic Empire!", "url": "index.html"},
        {"name": "Even Given the Worthless “Appraiser” Class, I’m Actually the Strongest", "url": "index.html"},
        {"name": "Welcome to Japan, Ms. Elf!", "url": "index.html"},
        {"name": "Medalist 2nd Season", "url": "index.html"},
        {"name": "Shangri-La Frontier Season 2", "url": "index.html"},
        {"name": "Honey Lemon Soda", "url": "index.html"},
        {"name": "From Bureaucrat to Villainess: Dad's Been Reincarnated!", "url": "index.html"},
        {"name": "Frieren: Beyond Journey’s End", "url": "index.html"},
        {"name": "Dr.STONE SCIENCE FUTURE Part 2", "url": "index.html"},
        {"name": "The Daily Life of a Middle-Aged Online Shopper in Another World", "url": "index.html"},
        {"name": "Bleach", "url": "index.html"},
        {"name": "Übel Blatt", "url": "index.html"},
        {"name": "DAN DA DAN", "url": "index.html"},
        {"name": "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You Season 2", "url": "index.html"},
        {"name": "I'm Getting Married to a Girl I Hate in My Class", "url": "index.html"},
        {"name": "ZENSHU", "url": "index.html"},
        {"name": "The Apothecary Diaries", "url": "index.html"},
        {"name": "You and Idol Precure ♪", "url": "index.html"},
        {"name": "Lazarus", "url": "index.html"},
        {"name": "Hunter x Hunter (2011)", "url": "index.html"},
        {"name": "Headhunted to Another World: From Salaryman to Big Four!", "url": "index.html"},
        {"name": "Ameku M.D.: Doctor Detective", "url": "index.html"},
        {"name": "Blue Miburo", "url": "index.html"},
        {"name": "Black Clover", "url": "index.html"},
        {"name": "Magic Maker: How to Make Magic in Another World", "url": "index.html"},
        {"name": "Ave Mujica - The Die is Cast -", "url": "index.html"},
        {"name": "Fire Force", "url": "index.html"},
        {"name": "Possibly the Greatest Alchemist of All Time", "url": "index.html"},
        {"name": "Tying the Knot with an Amagami Sister", "url": "index.html"},
        {"name": "Medaka Kuroiwa is Impervious to My Charms", "url": "index.html"},
        {"name": "Ao no Hako 2nd Season", "url": "index.html"},
        {"name": "I Have a Crush at Work", "url": "index.html"},
        {"name": "JUJUTSU KAISEN", "url": "index.html"},
        {"name": "Naruto", "url": "index.html"},
        {"name": "Re:Zero kara Hajimeru Isekai Seikatsu 4th Season", "url": "index.html"},
        {"name": "Is It Wrong To Try To Pick Up Girls in a Dungeon? V", "url": "index.html"},
        {"name": "JUJUTSU KAISEN Season 2", "url": "index.html"},
        {"name": "Fire Force Season 2", "url": "index.html"},
        {"name": "Re:ZERO -Starting Life in Another World-", "url": "index.html"},
        {"name": "Naruto: Shippuden", "url": "index.html"},
        {"name": "Gintama", "url": "index.html"},
        {"name": "My Hero Academia: Vigilantes", "url": "index.html"},
        {"name": "Babanba Banban Vampire", "url": "index.html"},
        {"name": "Super Cube", "url": "index.html"},
        {"name": "Chainsaw Man", "url": "index.html"},
        {"name": "Death Note", "url": "index.html"},
        {"name": "Blue Exorcist -The Blue Night Saga-", "url": "index.html"},
        {"name": "WIND BREAKER Season 2", "url": "index.html"},
        {"name": "ISHURA Season 2", "url": "index.html"},
        {"name": "WIND BREAKER", "url": "index.html"},
        {"name": "Dr. STONE", "url": "index.html"},
        {"name": "Sword Art Online", "url": "index.html"},
        {"name": "The Beginning After the End", "url": "index.html"},
        {"name": "WITCH WATCH", "url": "index.html"},
        {"name": "Witchy Precure!! ~MIRAI DAYS~", "url": "index.html"},
        {"name": "Sono Bisque Doll wa Koi wo Suru Season 2", "url": "index.html"},
        {"name": "Kaiju No.8", "url": "index.html"},
        {"name": "Shangri-La Frontier", "url": "index.html"},
        {"name": "Fullmetal Alchemist: Brotherhood", "url": "index.html"},
        {"name": "Neon Genesis Evangelion", "url": "index.html"},
        {"name": "DAN DA DAN Season 2", "url": "index.html"},
        {"name": "Kaiju No. 8 Season 2", "url": "index.html"},
        {"name": "Bogus Skill <<Fruitmaster>> ~About that time I became able to eat unlimited numbers of Skill Fruits (that kill you)~", "url": "index.html"},
        {"name": "Chainsaw Man – The Movie: Reze Arc", "url": "index.html"},
        {"name": "Delicious in Dungeon", "url": "index.html"},
        {"name": "Fire Force Season 3", "url": "index.html"},
        {"name": "Sword of the Demon Hunter: Kijin Gentosho", "url": "index.html"},
        {"name": "ERASED", "url": "index.html"},
        {"name": "Angel Beats!", "url": "index.html"},
        {"name": "Azumanga Daioh", "url": "index.html"},
        {"name": "From Old Country Bumpkin to Master Swordsman", "url": "index.html"},
        {"name": "Flower and Asura", "url": "index.html"},
        {"name": "The Brilliant Healer's New Life in the Shadows", "url": "index.html"},
        {"name": "Dragon Ball DAIMA", "url": "index.html"},
        {"name": "Tower of God Season 2", "url": "index.html"},
        {"name": "Demon Slayer: Kimetsu no Yaiba", "url": "index.html"},
        {"name": "Rascal Does Not Dream of Bunny Girl Senpai", "url": "index.html"},
        {"name": "Soul Eater", "url": "index.html"},
        {"name": "Gurren Lagann", "url": "index.html"},
        {"name": "Yu Yu Hakusho: Ghostfiles", "url": "index.html"},
        {"name": "Solo Leveling -ReAwakening-", "url": "index.html"},
        {"name": "Kaoru Hana wa Rin to Saku", "url": "index.html"},
        {"name": "The Red Ranger Becomes an Adventurer in Another World", "url": "index.html"},
        {"name": "Farmagia", "url": "index.html"},
        {"name": "Anyway, I'm Falling in Love with You.", "url": "index.html"},
        {"name": "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2", "url": "index.html"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc", "url": "index.html"},
        {"name": "BLUE LOCK Season 2", "url": "index.html"},
        {"name": "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You", "url": "index.html"},
        {"name": "Dr. STONE New World Part 2", "url": "index.html"},
        {"name": "Arifureta: From Commonplace to World's Strongest Season 3", "url": "index.html"},
        {"name": "Horimiya", "url": "index.html"},
        {"name": "Tokyo Revengers", "url": "index.html"},
        {"name": "Re:ZERO -Starting Life in Another World- Season 2", "url": "index.html"},
        {"name": "I’m a Noble on the Brink of Ruin, So I Might as Well Try Mastering Magic", "url": "index.html"},
        {"name": "I'm Living With a Otaku NEET Kunoichi?!", "url": "index.html"},
        {"name": "Toilet-bound Hanako-kun Season 2", "url": "index.html"},
        {"name": "TRILLION GAME", "url": "index.html"},
        {"name": "OKITSURA: Fell in Love with an Okinawan Girl, but I Just Wish I Know What She's Saying", "url": "index.html"},
        {"name": "Spice and Wolf: MERCHANT MEETS THE WISE WOLF", "url": "index.html"},
        {"name": "My Dress-Up Darling", "url": "index.html"},
        {"name": "BOCCHI THE ROCK!", "url": "index.html"},
        {"name": "Vinland Saga", "url": "index.html"},
        {"name": "Tokyo Ghoul", "url": "index.html"},
        {"name": "Attack on Titan", "url": "index.html"},
        {"name": "JoJo's Bizarre Adventure (TV)", "url": "index.html"},
        {"name": "Princess Mononoke", "url": "index.html"},
        {"name": "SAKAMOTO DAYS Part 2", "url": "index.html"},
        {"name": "Please Put Them On, Takamine-san", "url": "index.html"},
        {"name": "Lycoris Recoil: Friends are thieves of time.", "url": "index.html"},
        {"name": "Gachiakuta", "url": "index.html"},
        {"name": "Girls Band Cry", "url": "index.html"},
        {"name": "To Be Hero X", "url": "index.html"},
        {"name": "Tengoku Daimakyo", "url": "index.html"},
        {"name": "Can a Boy-Girl Friendship Survive?", "url": "index.html"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", "url": "index.html"},
        {"name": "KONOSUBA -God's blessing on this wonderful world! 3", "url": "index.html"},
        {"name": "Hell’s Paradise", "url": "index.html"},
        {"name": "Link Click", "url": "index.html"},
        {"name": "That Time I Got Reincarnated as a Slime", "url": "index.html"},
        {"name": "My Hero Academia", "url": "index.html"},
        {"name": "One-Punch Man", "url": "index.html"},
        {"name": "Assassination Classroom", "url": "index.html"},
        {"name": "Terror in Resonance", "url": "index.html"},
        {"name": "HAIKYU!!", "url": "index.html"},
        {"name": "Kuroko's Basketball", "url": "index.html"},
        {"name": "Blue Exorcist", "url": "index.html"},
        {"name": "Dragon Ball Z", "url": "index.html"},
        {"name": "Monster", "url": "index.html"},
        {"name": "BanG Dream! It's MyGO!!!!! / Ave Mujica (Zoku-hen)", "url": "index.html"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Infinity Castle", "url": "index.html"},
        {"name": "The Summer Hikaru Died", "url": "index.html"},
        {"name": "Momentary Lily", "url": "index.html"},
        {"name": "mono", "url": "index.html"},
        {"name": "My Deer Friend Nokotan", "url": "index.html"},
        {"name": "You are Ms. Servant", "url": "index.html"},
        {"name": "Rascal Does Not Dream of Santa Claus", "url": "index.html"},
        {"name": "Oshi no Ko Season 2", "url": "index.html"},
        {"name": "DEMON LORD 2099", "url": "index.html"},
        {"name": "Mushoku Tensei: Jobless Reincarnation Season 2", "url": "index.html"},
        {"name": "BLUE LOCK", "url": "index.html"},
        {"name": "Vinland Saga Season 2", "url": "index.html"},
        {"name": "The Eminence in Shadow", "url": "index.html"},
        {"name": "Summer Time Rendering", "url": "index.html"},
        {"name": "Re:ZERO -Starting Life in Another World- Season 2 Part 2", "url": "index.html"},
        {"name": "Death Parade", "url": "index.html"},
        {"name": "Parasyte -the maxim-", "url": "index.html"},
        {"name": "Kill la Kill", "url": "index.html"},
        {"name": "Steins;Gate", "url": "index.html"},
        {"name": "Fairy Tail", "url": "index.html"},
        {"name": "Howl‘s Moving Castle", "url": "index.html"},
        {"name": "Mobile Suit Gundam", "url": "index.html"},
        {"name": "Cowboy Bebop", "url": "index.html"},
        {"name": "There's No Freaking Way I'll Be Your Lover! Unless...", "url": "index.html"},
        {"name": "Kowloon Generic Romance", "url": "index.html"},
        {"name": "KONOSUBA -God's Blessing on This Wonderful World! 3 -BONUS STAGE-", "url": "index.html"},
        {"name": "Rock is a Lady’s Modesty", "url": "index.html"},
        {"name": "Let This Grieving Soul Retire", "url": "index.html"},
        {"name": "The Shiunji Family Children", "url": "index.html"},
        {"name": "LOOK BACK", "url": "index.html"},
        {"name": "Loner Life in Another World", "url": "index.html"},
        {"name": "Touhai: Ura Rate Mahjong Touhai Roku", "url": "index.html"},
        {"name": "Link Click: Bridon Arc", "url": "index.html"},
        {"name": "My Happy Marriage Season 2", "url": "index.html"},
        {"name": "My Hero Academia Season 7", "url": "index.html"},
        {"name": "The Eminence in Shadow Season 2", "url": "index.html"},
        {"name": "Pokémon Horizons: The Series", "url": "index.html"},
        {"name": "2.5 Dimensional Seduction", "url": "index.html"},
        {"name": "That Time I Got Reincarnated as a Slime Season 3", "url": "index.html"},
        {"name": "Romantic Killer", "url": "index.html"},
        {"name": "Ragna Crimson", "url": "index.html"},
        {"name": "Summer Pockets", "url": "index.html"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", "url": "index.html"},
        {"name": "Attack on Titan Final Season Part 2", "url": "index.html"},
        {"name": "Shikimori's Not Just a Cutie", "url": "index.html"},
        {"name": "86 EIGHTY-SIX", "url": "index.html"},
        {"name": "Attack on Titan Final Season", "url": "index.html"},
        {"name": "Kaguya-sama: Love is War", "url": "index.html"},
        {"name": "Wotakoi: Love is Hard for Otaku", "url": "index.html"},
        {"name": "Devilman Crybaby", "url": "index.html"},
        {"name": "Made in Abyss", "url": "index.html"},
        {"name": "Mob Psycho 100", "url": "index.html"},
        {"name": "Steins;Gate 0", "url": "index.html"},
        {"name": "Charlotte", "url": "index.html"},
        {"name": "HAIKYU!! 2nd Season", "url": "index.html"},
        {"name": "A Silent Voice", "url": "index.html"},
        {"name": "The Seven Deadly Sins", "url": "index.html"},
        {"name": "The Irregular at Magic High School", "url": "index.html"},
        {"name": "Date A Live", "url": "index.html"},
        {"name": "PSYCHO-PASS", "url": "index.html"},
        {"name": "The Future Diary", "url": "index.html"},
        {"name": "Kimi ni Todoke: From Me to You", "url": "index.html"},
        {"name": "Toradora!", "url": "index.html"},
        {"name": "Code Geass: Lelouch of the Rebellion", "url": "index.html"},
        {"name": "Dragon Ball", "url": "index.html"},
        {"name": "Mobile Suit Gundam GQuuuuuuX", "url": "index.html"},
        {"name": "The Unaware Atelier Meister", "url": "index.html"},
        {"name": "May I Ask for One Final Thing?", "url": "index.html"},
        {"name": "Yandere Dark Elf: She Chased Me All the Way From Another World!", "url": "index.html"},
        {"name": "Apocalypse Hotel", "url": "index.html"},
        {"name": "Silent Witch: Chinmoku no Majo no Kakushigoto", "url": "index.html"},
        {"name": "Sentai Daishikkaku 2nd Season", "url": "index.html"},
        {"name": "Unnamed Memory Season 2", "url": "index.html"},
        {"name": "Isekai Mokushiroku Mynoghra: Hametsu no Bunmei de Hajimeru Sekai Seifuku", "url": "index.html"},
        {"name": "Makina-san's a Love Bot?!", "url": "index.html"},
        {"name": "The Rising of the Shield Hero Season 4", "url": "index.html"},
        {"name": "The Strongest Magician in the Demon Lord's Army was a Human", "url": "index.html"},
        {"name": "Your Forma", "url": "index.html"},
        {"name": "A Sign of Affection", "url": "index.html"},
        {"name": "Pseudo Harem", "url": "index.html"},
        {"name": "Alya Sometimes Hides Her Feelings in Russian", "url": "index.html"},
        {"name": "The Dangers in My Heart", "url": "index.html"},
        {"name": "Dark Gathering", "url": "index.html"},
        {"name": "Moonrise", "url": "index.html"},
        {"name": "I've Been Killing Slimes For 300 Years And Maxed Out My Level Season 2", "url": "index.html"},
        {"name": "Chiikawa", "url": "index.html"},
        {"name": "Cyberpunk: Edgerunners", "url": "index.html"},
        {"name": "BEASTARS Season 2", "url": "index.html"},
        {"name": "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train", "url": "index.html"},
        {"name": "Mushoku Tensei: Jobless Reincarnation", "url": "index.html"},
        {"name": "Attack on Titan Season 3 Part 2", "url": "index.html"},
        {"name": "The Promised Neverland", "url": "index.html"},
        {"name": "I Want to Eat Your Pancreas", "url": "index.html"},
        {"name": "The Rising of the Shield Hero", "url": "index.html"},
        {"name": "Boruto: Naruto Next Generations", "url": "index.html"},
        {"name": "One-Punch Man Season 2", "url": "index.html"},
        {"name": "KONOSUBA -God's blessing on this wonderful world! 2", "url": "index.html"},
        {"name": "Plastic Memories", "url": "index.html"},
        {"name": "Blood Blockade Battlefront", "url": "index.html"},
        {"name": "Clannad: After Story", "url": "index.html"},
        {"name": "Pokémon", "url": "index.html"},
        {"name": "Serial Experiments Lain", "url": "index.html"},
        {"name": "Case Closed", "url": "index.html"},
        {"name": "Cardcaptor Sakura", "url": "index.html"},
        {"name": "NEET Kunoichi to Naze ka Dousei Hajimemashita OVAs", "url": "index.html"},
        {"name": "My Hero Academia FINAL SEASON", "url": "index.html"},
        {"name": "Sousou no Frieren 2nd Season", "url": "index.html"},
        {"name": "Uma Musume: Cinderella Gray", "url": "index.html"},
        {"name": "Aharen-san wa Hakarenai Season 2", "url": "index.html"},
        {"name": "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World Season 2", "url": "index.html"},
        {"name": "Beheneko: The Elf-Girl's Cat is Secretly an S-Ranked Monster!", "url": "index.html"},
        {"name": "Yofukashi no Uta Season 2", "url": "index.html"},
        {"name": "Sorairo Utility (TV)", "url": "index.html"},
        {"name": "Wistoria: Wand and Sword", "url": "index.html"},
        {"name": "Failure Frame: I Became the Strongest and Annihilated Everything with Low-Level Spells", "url": "index.html"},
        {"name": "SHOSHIMIN: How to Become Ordinary", "url": "index.html"},
        {"name": "Makeine: Too Many Losing Heroines!", "url": "index.html"},
        {"name": "I Parry Everything", "url": "index.html"},
        {"name": "BLEACH: Thousand-Year Blood War - The Conflict", "url": "index.html"},
        {"name": "Bungo Stray Dogs 5", "url": "index.html"},
        {"name": "Senpai is an Otokonoko", "url": "index.html"},
        {"name": "The Elusive Samurai", "url": "index.html"},
        {"name": "Attack on Titan Final Season THE FINAL CHAPTERS Special 2", "url": "index.html"},
        {"name": "ISHURA", "url": "index.html"},
        {"name": "I Was Reincarnated as the 7th Prince So I Can Take My Time Perfecting My Magical Ability", "url": "index.html"},
        {"name": "Undead Unluck", "url": "index.html"},
        {"name": "Days with My Stepsister", "url": "index.html"},
        {"name": "MASHLE: MAGIC AND MUSCLES", "url": "index.html"},
        {"name": "Ninja Kamui", "url": "index.html"},
        {"name": "KONOSUBA -An Explosion on This Wonderful World!", "url": "index.html"},
        {"name": "Farming Life in Another World", "url": "index.html"},
        {"name": "Call of the Night", "url": "index.html"},
        {"name": "Aharen-san wa Hakarenai", "url": "index.html"},
        {"name": "OVERLORD: The Sacred Kingdom", "url": "index.html"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc", "url": "index.html"},
        {"name": "Vivy -Fluorite Eye's Song-", "url": "index.html"},
        {"name": "Banished from the Hero’s Party, I Decided to Live a Quiet Life in the Countryside", "url": "index.html"},
        {"name": "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense. Season 2", "url": "index.html"},
        {"name": "Josee, the Tiger and the Fish", "url": "index.html"},
        {"name": "I've Been Killing Slimes for 300 Years and Maxed Out My Level", "url": "index.html"},
        {"name": "The Rising of the Shield Hero Season 3", "url": "index.html"},
        {"name": "The Rising of the Shield Hero Season 2", "url": "index.html"},
        {"name": "ID: INVADED", "url": "index.html"},
        {"name": "That Time I Got Reincarnated as a Slime Season 2", "url": "index.html"},
        {"name": "Dororo", "url": "index.html"},
        {"name": "Umamusume: Pretty Derby", "url": "index.html"},
        {"name": "Tsukigakirei", "url": "index.html"},
        {"name": "My Hero Academia Season 2", "url": "index.html"},
        {"name": "Your Name.", "url": "index.html"},
        {"name": "JoJo's Bizarre Adventure: Diamond is Unbreakable", "url": "index.html"},
        {"name": "Grimgar of Fantasy and Ash", "url": "index.html"},
        {"name": "Kiznaiver", "url": "index.html"},
        {"name": "KONOSUBA -God's blessing on this wonderful world!", "url": "index.html"},
        {"name": "Assassination Classroom 2", "url": "index.html"},
        {"name": "Attack on Titan Season 2", "url": "index.html"},
        {"name": "Food Wars!", "url": "index.html"},
        {"name": "Overlord", "url": "index.html"},
        {"name": "Seraph of the End: Vampire Reign", "url": "index.html"},
        {"name": "Yona of the Dawn", "url": "index.html"},
        {"name": "Your lie in April", "url": "index.html"},
        {"name": "World Break: Aria of Curse for a Holy Swordsman", "url": "index.html"},
        {"name": "Blue Spring Ride", "url": "index.html"},
        {"name": "Noragami", "url": "index.html"},
        {"name": "Fate/stay night: Unlimited Blade Works", "url": "index.html"},
        {"name": "Log Horizon", "url": "index.html"},
        {"name": "Magi: The Labyrinth of Magic", "url": "index.html"},
        {"name": "Fate/Zero", "url": "index.html"},
        {"name": "Puella Magi Madoka Magica", "url": "index.html"},
        {"name": "Deadman Wonderland", "url": "index.html"},
        {"name": "NANA", "url": "index.html"},
        {"name": "Macross Plus", "url": "index.html"},
        {"name": "Ao no Miburo: Serizawa Ansatsu-hen", "url": "index.html"},
        {"name": "Ki ni Natteru Hito ga Otoko Janakatta", "url": "index.html"},
        {"name": "Food for the Soul", "url": "index.html"},
        {"name": "Anne Shirley", "url": "index.html"},
        {"name": "The Too-Perfect Saint: Tossed Aside by My Fiancé and Sold to Another Kingdom", "url": "index.html"},
        {"name": "CARDFIGHT!! VANGUARD Divinez DELUXE Arc", "url": "index.html"},
        {"name": "Grand Blue Season 2", "url": "index.html"},
        {"name": "Mikadono Sanshimai wa Angai, Choroi.", "url": "index.html"},
        {"name": "Once Upon a Witch's Death", "url": "index.html"},
        {"name": "Ranma1/2 (2024)", "url": "index.html"},
        {"name": "SPY×FAMILY Season 3", "url": "index.html"},
        {"name": "Rurouni Kenshin -Kyoto Disturbance-", "url": "index.html"},
        {"name": "The Magical Girl and the Evil Lieutenant Used to Be Archenemies", "url": "index.html"},
        {"name": "Watari-kun no xx ga Houkai Sunzen", "url": "index.html"},
        {"name": "7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!", "url": "index.html"},
        {"name": "Dou Po Cangqiong: Nian Fan 3", "url": "index.html"},
        {"name": "Why Does Nobody Remember Me in This World?", "url": "index.html"},
        {"name": "BanG Dream! It's MyGO!!!!!", "url": "index.html"},
        {"name": "Horimiya: The Missing Pieces", "url": "index.html"},
        {"name": "Quality Assurance in Another World", "url": "index.html"},
        {"name": "Mission: Yozakura Family", "url": "index.html"},
        {"name": "Dead Mount Death Play", "url": "index.html"},
        {"name": "An Archdemon's Dilemma: How to Love Your Elf Bride", "url": "index.html"},
        {"name": "Buddy Daddies", "url": "index.html"},
        {"name": "My Love Story with Yamada-kun at Lv999", "url": "index.html"},
        {"name": "Our Dating Story: The Experienced You and The Inexperienced Me", "url": "index.html"},
        {"name": "No Longer Allowed in Another World", "url": "index.html"},
        {"name": "Date A Live V", "url": "index.html"},
        {"name": "TRIGUN STAMPEDE", "url": "index.html"},
        {"name": "Oshi No Ko", "url": "index.html"},
        {"name": "Classroom of the Elite Season 3", "url": "index.html"},
        {"name": "I've Somehow Gotten Stronger When I Improved My Farm-Related Skills", "url": "index.html"},
        {"name": "Classroom of the Elite Season 2", "url": "index.html"},
        {"name": "The Angel Next Door Spoils Me Rotten", "url": "index.html"},
        {"name": "Tokyo Revengers Season 2", "url": "index.html"},
        {"name": "Suzume", "url": "index.html"},
        {"name": "More than a Married Couple, but Not Lovers.", "url": "index.html"},
        {"name": "Skip and Loafer", "url": "index.html"},
        {"name": "Mobile Suit Gundam: The Witch from Mercury", "url": "index.html"},
        {"name": "FAIRY TAIL 100 YEARS QUEST", "url": "index.html"},
        {"name": "Soul Land 2: The Peerless Tang Clan", "url": "index.html"},
        {"name": "Renegade Immortal", "url": "index.html"},
        {"name": "BEASTARS Final Season Part 1", "url": "index.html"},
        {"name": "Overlord IV", "url": "index.html"},
        {"name": "The Case Study of Vanitas", "url": "index.html"},
        {"name": "86 EIGHTY-SIX Part 2", "url": "index.html"},
        {"name": "takt op.Destiny", "url": "index.html"},
        {"name": "Dr. STONE New World", "url": "index.html"},
        {"name": "Is It Wrong to Try to Pick Up Girls in a Dungeon? IV", "url": "index.html"},
        {"name": "The Genius Prince's Guide to Raising a Nation Out of Debt", "url": "index.html"},
        {"name": "GOBLIN SLAYER II", "url": "index.html"},
        {"name": "Blue Period", "url": "index.html"},
        {"name": "Mushoku Tensei: Jobless Reincarnation Cour 2", "url": "index.html"},
        {"name": "WONDER EGG PRIORITY", "url": "index.html"},
        {"name": "How a Realist Hero Rebuilt the Kingdom", "url": "index.html"},
        {"name": "My Hero Academia Season 5", "url": "index.html"},
        {"name": "That Time I Got Reincarnated as a Slime Season 2 Part 2", "url": "index.html"},
        {"name": "Akudama Drive", "url": "index.html"},
        {"name": "The God of High School", "url": "index.html"},
        {"name": "By the Grace of the Gods", "url": "index.html"},
        {"name": "Tower of God", "url": "index.html"},
        {"name": "Uzaki-chan Wants to Hang Out!", "url": "index.html"},
        {"name": "Made in Abyss: The Golden City of the Scorching Sun", "url": "index.html"},
        {"name": "To Your Eternity", "url": "index.html"},
        {"name": "Dr. STONE: STONE WARS", "url": "index.html"},
        {"name": "Ranking of Kings", "url": "index.html"},
        {"name": "Arifureta: From Commonplace to World's Strongest Season 2", "url": "index.html"},
        {"name": "The Quintessential Quintuplets 2", "url": "index.html"},
        {"name": "Toilet-bound Hanako-kun", "url": "index.html"},
        {"name": "BEASTARS", "url": "index.html"},
        {"name": "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense.", "url": "index.html"},
        {"name": "Dorohedoro", "url": "index.html"},
        {"name": "My Hero Academia Season 4", "url": "index.html"},
        {"name": "Domestic Girlfriend", "url": "index.html"},
        {"name": "JoJo's Bizarre Adventure: Golden Wind", "url": "index.html"},
        {"name": "Overlord III", "url": "index.html"},
        {"name": "Plunderer", "url": "index.html"},
        {"name": "Date A Live III", "url": "index.html"},
        {"name": "Arifureta: From Commonplace to World's Strongest", "url": "index.html"},
        {"name": "My Hero Academia Season 3", "url": "index.html"},
        {"name": "Attack on Titan Season 3", "url": "index.html"},
        {"name": "The Ancient Magus' Bride", "url": "index.html"},
        {"name": "Kakegurui", "url": "index.html"},
        {"name": "Violet Evergarden", "url": "index.html"},
        {"name": "The Disastrous Life of Saiki K.", "url": "index.html"},
        {"name": "Eromanga Sensei", "url": "index.html"},
        {"name": "Saga of Tanya the Evil", "url": "index.html"},
        {"name": "Prison School", "url": "index.html"},
        {"name": "Fairy Tail Series 2", "url": "index.html"},
        {"name": "Akame ga Kill!", "url": "index.html"},
        {"name": "No Game, No Life", "url": "index.html"},
        {"name": "Ace of the Diamond", "url": "index.html"},
        {"name": "Golden Time", "url": "index.html"},
        {"name": "My Teen Romantic Comedy SNAFU", "url": "index.html"},
        {"name": "Blast of Tempest", "url": "index.html"},
        {"name": "Sankarea: Undying Love", "url": "index.html"},
        {"name": "Another", "url": "index.html"},
        {"name": "Chihayafuru", "url": "index.html"},
        {"name": "Guilty Crown", "url": "index.html"},
        {"name": "Nichijou - My Ordinary Life", "url": "index.html"},
        {"name": "Toaru Kagaku no Railgun: Misaka-san wa Ima Chuumoku no Mato Desukara", "url": "index.html"},
        {"name": "Amagami SS", "url": "index.html"},
        {"name": "Shiki", "url": "index.html"},
        {"name": "A Certain Magical Index", "url": "index.html"},
        {"name": "Spice and Wolf", "url": "index.html"},
        {"name": "Code Geass: Lelouch of the Rebellion R2", "url": "index.html"},
        {"name": "The Girl Who Leapt Through Time", "url": "index.html"},
        {"name": "Clannad", "url": "index.html"},
        {"name": "Darker than Black", "url": "index.html"},
        {"name": "Lucky☆Star", "url": "index.html"},
        {"name": "When They Cry", "url": "index.html"},
        {"name": "Hellsing Ultimate", "url": "index.html"},
        {"name": "Grave of the Fireflies", "url": "index.html"},
        {"name": "Hajime no Ippo: The Fighting!", "url": "index.html"},
        {"name": "FLCL", "url": "index.html"},
        {"name": "Spirited Away", "url": "index.html"},
        {"name": "Fullmetal Alchemist", "url": "index.html"},
        {"name": "Mobile Suit Zeta Gundam", "url": "index.html"},
        {"name": "Akira", "url": "index.html"},
        {"name": "Ghost in the Shell", "url": "index.html"},
        {"name": "METEORGIRL", "url": "index.html"},
        {"name": "Kuroiwa Medaka ni Watashi no Kawaii ga Tsuujinai 2nd Season", "url": "index.html"},
        {"name": "Rurouni Kenshin: Meiji Kenkaku Romantan 3", "url": "index.html"},
        {"name": "Kono Subarashii Sekai ni Shukufuku wo! (Zoku-hen)", "url": "index.html"},
        {"name": "Kimi ga Shinu made Koi wo Shitai", "url": "index.html"},
        {"name": "Bocchi the Rock! 2nd Season", "url": "index.html"},
        {"name": "Nageki no Bourei wa Intai shitai 2", "url": "index.html"},
        {"name": "Tsuihousha Shokudou e Youkoso!", "url": "index.html"},
        {"name": "Seihantai na Kimi to Boku", "url": "index.html"},
        {"name": "Catch Me at the Ballpark!", "url": "index.html"},
        {"name": "Watashi wo Tabetai, Hitodenashi", "url": "index.html"},
        {"name": "Lockdown Zone: Level X Season 2", "url": "index.html"},
        {"name": "CITY THE ANIMATION", "url": "index.html"},
        {"name": "Kobayashi-san Chi no Maidragon Samishii Gariya no Ryuu", "url": "index.html"},
        {"name": "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 4th Season", "url": "index.html"},
        {"name": "Ame to Kimi to", "url": "index.html"},
        {"name": "I Was Reincarnated as the 7th Prince So I Can Take My Time Perfecting My Magical Ability Season 2", "url": "index.html"},
        {"name": "The Quintessential Quintuplets Specials 2", "url": "index.html"},
        {"name": "Good Bye, Dragon Life", "url": "index.html"},
        {"name": "MONOGATARI Series: OFF & MONSTER Season", "url": "index.html"},
        {"name": "Plus-Sized Elf", "url": "index.html"},
        {"name": "Uma Musume: Pretty Derby - Shin Jidai no Tobira", "url": "index.html"},
        {"name": "A Nobody's Way Up to an Exploration Hero", "url": "index.html"},
        {"name": "Kage no Jitsuryokusha ni Naritakute!: Zankyou-hen", "url": "index.html"},
        {"name": "Nina the Starry Bride", "url": "index.html"},
        {"name": "Chillin' in Another World with Level 2 Super Cheat Powers", "url": "index.html"},
        {"name": "Kimi ni Todoke: From Me to You Season 3", "url": "index.html"},
        {"name": "My Hero Academia: You’re Next", "url": "index.html"},
        {"name": "The Demon Prince of Momochi House", "url": "index.html"},
        {"name": "Sword Art Online Alternative: Gun Gale Online II", "url": "index.html"},
        {"name": "The Fable", "url": "index.html"},
        {"name": "Suicide Squad ISEKAI", "url": "index.html"},
        {"name": "Fate/strange Fake", "url": "index.html"},
        {"name": "MASHLE: MAGIC AND MUSCLES Season 2", "url": "index.html"},
        {"name": "The Dangers in My Heart Season 2", "url": "index.html"},
        {"name": "A Condition Called Love", "url": "index.html"},
        {"name": "365 Days to the Wedding", "url": "index.html"},
        {"name": "The Foolish Angel Dances with the Devil", "url": "index.html"},
        {"name": "Tokyo Revengers Season 2 Part 2", "url": "index.html"},
        {"name": "The Ossan Newbie Adventurer, Trained to Death by the Most Powerful Party, Became Invincible", "url": "index.html"},
        {"name": "A Returner's Magic Should Be Special", "url": "index.html"},
        {"name": "AQUARION: Myth of Emotions", "url": "index.html"},
        {"name": "Mr. Villain's Day Off", "url": "index.html"},
        {"name": "Rascal Does Not Dream of a Knapsack Kid", "url": "index.html"},
        {"name": "VTuber Legend: How I Went Viral after Forgetting to Turn Off My Stream", "url": "index.html"},
        {"name": "The Girl I Like Forgot Her Glasses", "url": "index.html"},
        {"name": "Whisper Me a Love Song", "url": "index.html"},
        {"name": "Mysterious Disappearances", "url": "index.html"},
        {"name": "SPY x FAMILY Season 2", "url": "index.html"},
        {"name": "I'm in Love with the Villainess", "url": "index.html"},
        {"name": "Campfire Cooking in Another World with my Absurd Skill", "url": "index.html"},
        {"name": "Synduality Noir", "url": "index.html"},
        {"name": "The Café Terrace and Its Goddesses", "url": "index.html"},
        {"name": "Am I Actually the Strongest?", "url": "index.html"},
        {"name": "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too", "url": "index.html"},
        {"name": "One Punch Man 3", "url": "index.html"},
        {"name": "HAIKYU!! The Dumpster Battle", "url": "index.html"},
        {"name": "Reborn as a Vending Machine, I Now Wander the Dungeon", "url": "index.html"},
        {"name": "The Ice Guy and His Cool Female Colleague", "url": "index.html"},
        {"name": "My Home Hero", "url": "index.html"},
        {"name": "Kubo Won't Let Me Be Invisible", "url": "index.html"},
        {"name": "In Another World With My Smartphone 2", "url": "index.html"},
        {"name": "My Happy Marriage", "url": "index.html"},
        {"name": "Engage Kiss", "url": "index.html"},
        {"name": "NieR:Automata Ver1.1a", "url": "index.html"},
        {"name": "Black Summoner", "url": "index.html"},
        {"name": "Insomniacs After School", "url": "index.html"},
        {"name": "Rurouni Kenshin (2023)", "url": "index.html"},
        {"name": "Yu☆Gi☆Oh! Go Rush!!", "url": "index.html"},
        {"name": "SPY x FAMILY Cour 2", "url": "index.html"},
        {"name": "TONIKAWA: Over The Moon For You Season 2", "url": "index.html"},
        {"name": "SPY x FAMILY", "url": "index.html"},
        {"name": "Tokyo 24th Ward", "url": "index.html"},
        {"name": "Mob Psycho 100 III", "url": "index.html"},
        {"name": "I'm the Villainess, So I'm Taming the Final Boss", "url": "index.html"},
        {"name": "Management of a Novice Alchemist", "url": "index.html"},
        {"name": "Teasing Master Takagi-san Season 3", "url": "index.html"},
        {"name": "Komi Can’t Communicate", "url": "index.html"},
        {"name": "A Couple of Cuckoos", "url": "index.html"},
        {"name": "JUJUTSU KAISEN 0", "url": "index.html"},
        {"name": "Scarlet Nexus", "url": "index.html"},
        {"name": "The Devil is a Part-Timer! Season 2", "url": "index.html"},
        {"name": "The Misfit of Demon King Academy Ⅱ: History's Strongest Demon King Reincarnates and Goes to School with His Descendants", "url": "index.html"},
        {"name": "My Isekai Life: I Gained a Second Character Class and Became the Strongest Sage in the World!", "url": "index.html"},
        {"name": "Platinum End", "url": "index.html"},
        {"name": "Record of Ragnarok", "url": "index.html"},
        {"name": "Love of Kill", "url": "index.html"},
        {"name": "Girlfriend, Girlfriend", "url": "index.html"},
        {"name": "Peach Boy Riverside", "url": "index.html"},
        {"name": "BLEACH: Thousand-Year Blood War", "url": "index.html"},
        {"name": "Date A Live IV", "url": "index.html"},
        {"name": "Welcome to Demon School! Iruma-kun Season 2", "url": "index.html"},
        {"name": "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway", "url": "index.html"},
        {"name": "The Daily Life of the Immortal King", "url": "index.html"},
        {"name": "Food Wars! The Fifth Plate", "url": "index.html"},
        {"name": "The Misfit of Demon King Academy: History’s Strongest Demon King Reincarnates and Goes to School with His Descendants", "url": "index.html"},
        {"name": "Uzumaki", "url": "index.html"},
        {"name": "Food Wars! The Fourth Plate", "url": "index.html"},
        {"name": "given", "url": "index.html"},
        {"name": "Ascendance of a Bookworm", "url": "index.html"},
        {"name": "Science Fell in Love, So I Tried to Prove It", "url": "index.html"},
        {"name": "Cautious Hero: The Hero Is Overpowered but Overly Cautious", "url": "index.html"},
        {"name": "Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?", "url": "index.html"},
        {"name": "So I'm a Spider, So What?", "url": "index.html"},
        {"name": "The Quintessential Quintuplets", "url": "index.html"},
        {"name": "Violet Evergarden: the Movie", "url": "index.html"},
        {"name": "Chihayafuru 3", "url": "index.html"},
        {"name": "Grand Blue Dreaming", "url": "index.html"},
        {"name": "Tokyo Ghoul:re", "url": "index.html"},
        {"name": "Re:ZERO -Starting Life in Another World- OVAs", "url": "index.html"},
        {"name": "MAGICAL GIRL SITE", "url": "index.html"},
        {"name": "Teasing Master Takagi-san", "url": "index.html"},
        {"name": "Food Wars! The Third Plate", "url": "index.html"},
        {"name": "Overlord II", "url": "index.html"},
        {"name": "BLEND-S", "url": "index.html"},
        {"name": "BAKI", "url": "index.html"},
        {"name": "Blue Exorcist: Kyoto Saga", "url": "index.html"},
        {"name": "Little Witch Academia (TV)", "url": "index.html"},
        {"name": "Masamune-kun's Revenge", "url": "index.html"},
        {"name": "Miss Kobayashi's Dragon Maid", "url": "index.html"},
        {"name": "HAIKYU!! 3rd Season", "url": "index.html"},
        {"name": "Orange", "url": "index.html"},
        {"name": "Food Wars! The Second Plate", "url": "index.html"},
        {"name": "Tanaka-kun is Always Listless", "url": "index.html"},
        {"name": "Bungo Stray Dogs", "url": "index.html"},
        {"name": "Saekano: How to Raise a Boring Girlfriend ♭", "url": "index.html"},
        {"name": "Dragon Ball Super", "url": "index.html"},
        {"name": "Monster Musume: Everyday Life With Monster Girls", "url": "index.html"},
        {"name": "Himouto! Umaru-chan", "url": "index.html"},
        {"name": "My Love Story!!", "url": "index.html"},
        {"name": "Durarara!! X2 The Second Arc", "url": "index.html"},
        {"name": "Lord Marksman and Vanadis", "url": "index.html"},
        {"name": "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt", "url": "index.html"},
        {"name": "Fate/stay night: Unlimited Blade Works 2nd Season", "url": "index.html"},
        {"name": "World Trigger", "url": "index.html"},
        {"name": "My Teen Romantic Comedy SNAFU TOO!", "url": "index.html"},
        {"name": "Saekano: How to Raise a Boring Girlfriend", "url": "index.html"},
        {"name": "Sword Art Online II", "url": "index.html"},
        {"name": "The Kawai Complex Guide to Manors and Hostel Behavior", "url": "index.html"},
        {"name": "JoJo's Bizarre Adventure: Stardust Crusaders", "url": "index.html"},
        {"name": "Date A Live II", "url": "index.html"},
        {"name": "Kuroko's Basketball 2", "url": "index.html"},
        {"name": "The Last: Naruto the Movie", "url": "index.html"},
        {"name": "The Wind Rises", "url": "index.html"},
        {"name": "The Devil is a Part-Timer!", "url": "index.html"},
        {"name": "Kamisama Kiss", "url": "index.html"},
        {"name": "My Little Monster", "url": "index.html"},
        {"name": "Daily Lives of High School Boys", "url": "index.html"},
        {"name": "Fate/Zero Season 2", "url": "index.html"},
        {"name": "High School DxD", "url": "index.html"},
        {"name": "Penguindrum", "url": "index.html"},
        {"name": "Blood-C", "url": "index.html"},
        {"name": "Toaru Kagaku no Railgun: Entenka no Satsuei Model mo Raku ja Arimasen wa ne.", "url": "index.html"},
        {"name": "High School of the Dead", "url": "index.html"},
        {"name": "Maid-Sama!", "url": "index.html"},
        {"name": "Baka and Test - Summon the Beasts", "url": "index.html"},
        {"name": "Dragon Ball Z Kai", "url": "index.html"},
        {"name": "Angel of Legend", "url": "index.html"},
        {"name": "Black Butler", "url": "index.html"},
        {"name": "Ponyo", "url": "index.html"},
        {"name": "School Days (TV)", "url": "index.html"},
        {"name": "The Familiar of Zero", "url": "index.html"},
        {"name": "Sailor Moon Sailor Stars", "url": "index.html"},
        {"name": "Shin Chan", "url": "index.html"},
        {"name": "Ergo Proxy", "url": "index.html"},
        {"name": "Kiki's Delivery Service", "url": "index.html"},
        {"name": "Haibane Renmei", "url": "index.html"},
        {"name": "Hellsing", "url": "index.html"},
        {"name": "InuYasha", "url": "index.html"},
        {"name": "Air", "url": "index.html"},
        {"name": "Rurouni Kenshin", "url": "index.html"},
        {"name": "Berserk", "url": "index.html"},
        {"name": "Trigun", "url": "index.html"},
        {"name": "Momentary Lily: Tsudzuite iku Kappou, Kappou!", "url": "index.html"},
        {"name": "Koisuru ONE PIECE", "url": "index.html"},
        {"name": "Natsume Yuujinchou × Kumamoto-ken: Hitoyoshi Kuma de no Yasashii Jikan", "url": "index.html"},
        {"name": "ALL YOU NEED IS KILL", "url": "index.html"},
        {"name": "Ansatsusha de Aru Ore no Status ga Yuusha yori mo Akiraka ni Tsuyoi no da ga", "url": "index.html"},
        {"name": "Princess Principal: Crown Handler - Chapter 4", "url": "index.html"},
        {"name": "Fushigi ‌no ‌Kuni ‌de ‌Alice to: Dive ‌in ‌Wonderland", "url": "index.html"},
        {"name": "Yuugao", "url": "index.html"},
        {"name": "Maomao no Hitorigoto 2nd Season", "url": "index.html"},
        {"name": "Solo Camping for Two", "url": "index.html"},
        {"name": "Skip and Loafer Season 2", "url": "index.html"},
        {"name": "Theatre of Darkness: Yamishibai 14", "url": "index.html"},
        {"name": "Uchuujin MuuMuu", "url": "index.html"},
        {"name": "Nazotoki wa Dinner no Ato de", "url": "index.html"},
        {"name": "Dekin no Mogura: The Earthbound Mole", "url": "index.html"},
        {"name": "Xianwu Zhuan 3", "url": "index.html"},
        {"name": "ONE PIECE FAN LETTER", "url": "index.html"},
        {"name": "Re:Zero kara Hajimeru Kyuukei Jikan (Break Time) 3rd Season", "url": "index.html"},
        {"name": "Tensei Shitara Slime Datta Ken - Soukai no Namida-hen", "url": "index.html"},
        {"name": "Virgin Punk", "url": "index.html"},
        {"name": "SHOSHIMIN: How to become Ordinary Season 2", "url": "index.html"},
        {"name": "Ruri no Houseki", "url": "index.html"},
        {"name": "Tsuihou Sareta Tensei Juukishi wa Game Sashiki de Musou Suru", "url": "index.html"},
        {"name": "Negative Positive Angler", "url": "index.html"},
        {"name": "Yuusha Party wo Tsuihou Sareta Shiro Madoushi, S Rank Boukensha ni Hirowareru: Kono Shiro Madoushi ga Kikakugaisugiru", "url": "index.html"},
        {"name": "Kanojo, Okarishimasu 4th Season", "url": "index.html"},
        {"name": "Fire Force Season 3 Part 2", "url": "index.html"},
        {"name": "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha", "url": "index.html"},
        {"name": "Bad Girl", "url": "index.html"},
        {"name": "TASOKARE HOTEL", "url": "index.html"},
        {"name": "DEAD DEAD DEMONS DEDEDEDE DESTRUCTION", "url": "index.html"},
        {"name": "YAIBA: Samurai Legend", "url": "index.html"},
        {"name": "Tougen Anki: Legend of the Cursed Blood", "url": "index.html"},
        {"name": "The Most Notorious Talker Runs the World's Greatest Clan", "url": "index.html"},
        {"name": "Uma Musume: Pretty Derby - ROAD TO THE TOP Movie", "url": "index.html"},
        {"name": "Nyaight of the Living Cat", "url": "index.html"},
        {"name": "Tono to Inu", "url": "index.html"},
        {"name": "Tasuketsu -Fate of the Majority-", "url": "index.html"},
        {"name": "The Healer Who Was Banished From His Party, Is, in Fact, the Strongest", "url": "index.html"},
        {"name": "Sai-Kyo-Oh! Zukan: The Ultimate Battles", "url": "index.html"},
        {"name": "Yumemiru Otome", "url": "index.html"},
        {"name": "A Terrified Teacher at Ghoul School!", "url": "index.html"},
        {"name": "Trapezium", "url": "index.html"},
        {"name": "A Journey Through Another World: Raising Kids While Adventuring", "url": "index.html"},
        {"name": "Wonderful Precure!", "url": "index.html"},
        {"name": "Magilumiere Magical Girls Inc.", "url": "index.html"},
        {"name": "Promise of Wizard", "url": "index.html"},
        {"name": "THE NEW GATE", "url": "index.html"},
        {"name": "I Want to Escape from Princess Lessons", "url": "index.html"},
        {"name": "YATAGARASU: The Raven Does Not Choose Its Master", "url": "index.html"},
        {"name": "Yakuza Fiancé: Raise wa Tanin ga Ii", "url": "index.html"},
        {"name": "Scott Pilgrim Takes Off", "url": "index.html"},
        {"name": "The Strongest Tank's Labyrinth Raids -A Tank with a Rare 9999 Resistance Skill Got Kicked from the Hero's Party-", "url": "index.html"},
        {"name": "How I Attended an All-Guy's Mixer", "url": "index.html"},
        {"name": "Case Closed: The Million-dollar Pentagram", "url": "index.html"},
        {"name": "Synduality Noir Part 2", "url": "index.html"},
        {"name": "Re:Monster", "url": "index.html"},
        {"name": "Dahlia in Bloom: Crafting a Fresh Start with Magical Tools", "url": "index.html"},
        {"name": "Demon Lord, Retry! R", "url": "index.html"},
        {"name": "I’ll Become a Villainess Who Goes Down in History", "url": "index.html"},
        {"name": "Grandpa and Grandma Turn Young Again", "url": "index.html"},
        {"name": "GOOD NIGHT WORLD", "url": "index.html"},
        {"name": "UniteUp! -Uni:Birth-", "url": "index.html"},
        {"name": "Yuusha Kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku", "url": "index.html"},
        {"name": "Love Is Indivisible by Twins", "url": "index.html"},
        {"name": "Cherry Magic! Thirty Years of Virginity Can Make You a Wizard?!", "url": "index.html"},
        {"name": "A Salad Bowl of Eccentrics", "url": "index.html"},
        {"name": "Hell’s Paradise Season 2", "url": "index.html"},
        {"name": "'Tis Time for Torture, Princess", "url": "index.html"},
        {"name": "The Café Terrace and Its Goddesses Season 2", "url": "index.html"},
        {"name": "Mofa Gongzhu De Xiao Fannao", "url": "index.html"},
        {"name": "ZatsuTabi -That's Journey-", "url": "index.html"},
        {"name": "BEYBLADE X", "url": "index.html"},
        {"name": "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World", "url": "index.html"},
        {"name": "Go-toubun no Hanayome∽", "url": "index.html"},
        {"name": "Jellyfish Can’t Swim in the Night", "url": "index.html"},
        {"name": "Metallic Rouge", "url": "index.html"},
        {"name": "3-nen Z-gumi Ginpachi-sensei", "url": "index.html"},
        {"name": "Gushing Over Magical Girls", "url": "index.html"},
        {"name": "Doctor Elise: The Royal Lady with the Lamp", "url": "index.html"},
        {"name": "GAMERA -Rebirth-", "url": "index.html"},
        {"name": "Tales of Wedding Rings", "url": "index.html"},
        {"name": "Zom 100: Bucket List of the Dead", "url": "index.html"},
        {"name": "The Many Sides of Voice Actor Radio", "url": "index.html"},
        {"name": "Blue Exorcist -Shimane Illuminati Saga-", "url": "index.html"},
        {"name": "GHOST CAT ANZU", "url": "index.html"},
        {"name": "Lookism", "url": "index.html"},
        {"name": "The Gene of AI", "url": "index.html"},
        {"name": "GO! GO! Loser Ranger!", "url": "index.html"},
        {"name": "The Colors Within", "url": "index.html"},
        {"name": "My Instant Death Ability is Overpowered", "url": "index.html"},
        {"name": "The Dreaming Boy is a Realist", "url": "index.html"},
        {"name": "Bye Bye, Earth", "url": "index.html"},
        {"name": "The Weakest Tamer Began a Journey to Pick Up Trash", "url": "index.html"},
        {"name": "Busu ni Hanataba wo.", "url": "index.html"},
        {"name": "My Daughter Left the Nest and Returned an S-Rank Adventurer", "url": "index.html"},
        {"name": "Banished from the Hero’s Party, I Decided to Live a Quiet Life in the Countryside Season 2", "url": "index.html"},
        {"name": "The Girl Downstairs", "url": "index.html"},
        {"name": "Berserk of Gluttony", "url": "index.html"},
        {"name": "Hokkaido Gals Are Super Adorable!", "url": "index.html"},
        {"name": "Tsuyokute New Saga", "url": "index.html"},
        {"name": "Train to the End of the World", "url": "index.html"},
        {"name": "Urusei Yatsura (2022) Season 3", "url": "index.html"},
        {"name": "ATRI -My Dear Moments-", "url": "index.html"},
        {"name": "Mecha Ude: Mechanical Arms", "url": "index.html"},
        {"name": "Let You Down", "url": "index.html"},
        {"name": "The Ancient Magus' Bride Season 2", "url": "index.html"},
        {"name": "I'm Giving the Disgraced Noble Lady I Rescued a Crash Course in Naughtiness", "url": "index.html"},
        {"name": "The Witch and the Beast", "url": "index.html"},
        {"name": "The Magical Revolution of the Reincarnated Princess and the Genius Young Lady", "url": "index.html"},
        {"name": "The Aristocrat’s Otherworldly Adventure: Serving Gods Who Go Too Far", "url": "index.html"},
        {"name": "Sasaki and Peeps", "url": "index.html"},
        {"name": "Chillin’ in My 30s after Getting Fired from the Demon King’s Army", "url": "index.html"},
        {"name": "Fluffy Paradise", "url": "index.html"},
        {"name": "Tomo-chan Is a Girl!", "url": "index.html"},
        {"name": "Kaguya-sama: Love is War -The First Kiss That Never Ends-", "url": "index.html"},
        {"name": "Beast Tamer", "url": "index.html"},
        {"name": "The Masterful Cat is Depressed Again Today", "url": "index.html"},
        {"name": "Uma Musume: Pretty Derby - ROAD TO THE TOP", "url": "index.html"},
        {"name": "A Galaxy Next Door", "url": "index.html"},
        {"name": "Play It Cool, Guys", "url": "index.html"},
        {"name": "The Unwanted Undead Adventurer", "url": "index.html"},
        {"name": "Ao no Orchestra", "url": "index.html"},
        {"name": "Attack on Titan Final Season THE FINAL CHAPTERS Special 1", "url": "index.html"},
        {"name": "Masamune-kun's Revenge R", "url": "index.html"},
        {"name": "JoJo's Bizarre Adventure: STONE OCEAN Part 2", "url": "index.html"},
        {"name": "RWBY: Ice Queendom", "url": "index.html"},
        {"name": "Grisaia: Phantom Trigger", "url": "index.html"},
        {"name": "Lonely Castle in the Mirror", "url": "index.html"},
        {"name": "The Reincarnation of the Strongest Exorcist in Another World", "url": "index.html"},
        {"name": "Lucifer and the Biscuit Hammer", "url": "index.html"},
        {"name": "The Irregular at Magic High School Season 3", "url": "index.html"},
        {"name": "Butareba -The Story of a Man Turned into a Pig-", "url": "index.html"},
        {"name": "Golden Kamuy Season 4", "url": "index.html"},
        {"name": "Seirei Gensouki: Spirit Chronicles Season 2", "url": "index.html"},
        {"name": "Tomodachi Game", "url": "index.html"},
        {"name": "Summoned to Another World for a Second Time", "url": "index.html"},
        {"name": "DON'T TOY WITH ME, MISS NAGATORO 2nd Attack", "url": "index.html"},
        {"name": "I'm Quitting Heroing", "url": "index.html"},
        {"name": "Our Last Crusade or the Rise of a New World Season 2", "url": "index.html"},
        {"name": "How a Realist Hero Rebuilt the Kingdom Part 2", "url": "index.html"},
        {"name": "My Hero Academia Season 6", "url": "index.html"},
        {"name": "TSUKIMICHI -Moonlit Fantasy- Season 2", "url": "index.html"},
        {"name": "Welcome to Demon School! Iruma-kun Season 3", "url": "index.html"},
        {"name": "To Your Eternity Season 2", "url": "index.html"},
        {"name": "The Wrong Way to Use Healing Magic", "url": "index.html"},
        {"name": "Guimi Zhi Zhu", "url": "index.html"},
        {"name": "Deep Insanity THE LOST CHILD", "url": "index.html"},
        {"name": "Life With an Ordinary Guy Who Reincarnated Into a Total Fantasy Knockout", "url": "index.html"},
        {"name": "BUILD-DIVIDE -#000000- CODE BLACK", "url": "index.html"},
        {"name": "Skeleton Knight in Another World", "url": "index.html"},
        {"name": "The Faraway Paladin", "url": "index.html"},
        {"name": "Dance Dance Danseur", "url": "index.html"},
        {"name": "Love After World Domination", "url": "index.html"},
        {"name": "Mieruko-chan", "url": "index.html"},
        {"name": "Irina: The Vampire Cosmonaut", "url": "index.html"},
        {"name": "The Misfit of Demon King Academy II (Cour 2)", "url": "index.html"},
        {"name": "Sacrificial Princess and the King of Beasts", "url": "index.html"},
        {"name": "The Detective Is Already Dead", "url": "index.html"},
        {"name": "When Will Ayumu Make His Move?", "url": "index.html"},
        {"name": "I'm Standing on a Million Lives Season 2", "url": "index.html"},
        {"name": "Gintama: THE SEMI-FINAL", "url": "index.html"},
        {"name": "SHADOWS HOUSE", "url": "index.html"},
        {"name": "Godzilla Singular Point", "url": "index.html"},
        {"name": "Uzaki-chan Wants to Hang Out! Season 2", "url": "index.html"},
        {"name": "SK8 the Infinity", "url": "index.html"},
        {"name": "Sword Art Online the Movie -Progressive- Aria of a Starless Night", "url": "index.html"},
        {"name": "The Dungeon of Black Company", "url": "index.html"},
        {"name": "Dawang Raoming", "url": "index.html"},
        {"name": "SHAMAN KING (2021)", "url": "index.html"},
        {"name": "MARS RED", "url": "index.html"},
        {"name": "A Whisker Away", "url": "index.html"},
        {"name": "Koikimo", "url": "index.html"},
        {"name": "World Trigger 2nd Season", "url": "index.html"},
        {"name": "Kemono Jihen", "url": "index.html"},
        {"name": "SSSS.DYNAZENON", "url": "index.html"},
        {"name": "Idoly Pride", "url": "index.html"},
        {"name": "Rent-a-Girlfriend", "url": "index.html"},
        {"name": "Ascendance of a Bookworm Part 2", "url": "index.html"},
        {"name": "HAIKYU‼ TO THE TOP Part 2", "url": "index.html"},
        {"name": "Kakushigoto", "url": "index.html"},
        {"name": "Heaven Official's Blessing", "url": "index.html"},
        {"name": "APPARE-RANMAN!", "url": "index.html"},
        {"name": "The Irregular at Magic High School: Visitor Arc", "url": "index.html"},
        {"name": "Is It Wrong to Try to Pick Up Girls in a Dungeon? III", "url": "index.html"},
        {"name": "Sleepy Princess in the Demon Castle", "url": "index.html"},
        {"name": "Ikebukuro West Gate Park", "url": "index.html"},
        {"name": "GIBIATE", "url": "index.html"},
        {"name": "BNA", "url": "index.html"},
        {"name": "Great Pretender", "url": "index.html"},
        {"name": "Interspecies Reviewers", "url": "index.html"},
        {"name": "The Boy and the Heron", "url": "index.html"},
        {"name": "Mob Psycho 100 II: The First Spirits and Such Company Trip ~A Journey that Mends the Heart and Heals the Soul~", "url": "index.html"},
    ]
};