const gamesData = {
    "games": [
        {"name": "Black Myth: Wukong", "url": "index.html"},
        {"name": "Assassin's Creed Shadows", "url": "index.html"},
        {"name": "Split Fiction", "url": "index.html"},
        {"name": "Two Point Museum", "url": "index.html"},
        {"name": "Monster Hunter Wilds", "url": "index.html"},
        {"name": "Like a Dragon: Pirate Yakuza in Hawaii", "url": "index.html"},
        {"name": "Civilization 7", "url": "index.html"},
        {"name": "Kingdom Come: Deliverance 2", "url": "index.html"},
        {"name": "Citizen Sleeper 2: Starward Vector", "url": "index.html"},
        {"name": "Dynasty Warriors: Origins", "url": "index.html"},
        {"name": "Mouthwashing", "url": "index.html"},
        {"name": "Marvel Rivals", "url": "index.html"},
        {"name": "Indiana Jones and the Great Circle", "url": "index.html"},
        {"name": "Microsoft Flight Simulator 2024", "url": "index.html"},
        {"name": "STALKER 2: Heart of Chornobyl", "url": "index.html"},
        {"name": "Life is Strange: Double Exposure", "url": "index.html"},
        {"name": "Dragon Age: The Veilguard", "url": "index.html"},
        {"name": "Call of Duty: Black Ops 6", "url": "index.html"},
        {"name": "Sonic X Shadow Generations", "url": "index.html"},
        {"name": "MechWarrior 5: Clans", "url": "index.html"},
        {"name": "Metaphor: ReFantazio", "url": "index.html"},
        {"name": "Silent Hill 2 Remake", "url": "index.html"},
        {"name": "Warhammer 40,000: Space Marine 2", "url": "index.html"},
        {"name": "Counter-Strike 2 & GO", "url": "index.html"},
        {"name": "Minecraft", "url": "index.html"},
        {"name": "Fortnite", "url": "index.html"},
        {"name": "The Sims 4", "url": "index.html"},
        {"name": "ROBLOX", "url": "index.html"},
        {"name": "Marvel Rivals", "url": "index.html"},
        {"name": "League of Legends", "url": "index.html"},
        {"name": "Dota 2", "url": "index.html"},
        {"name": "Valorant", "url": "index.html"},
        {"name": "PUBG: BATTLEGROUNDS", "url": "index.html"},
        {"name": "Call of Duty: Modern Warfare II/III/Warzone/Black Ops 6", "url": "index.html"},
        {"name": "Monster Hunter Wilds", "url": "index.html"},
        {"name": "Overwatch 1 & 2", "url": "index.html"},
        {"name": "HELLDIVERS 2", "url": "index.html"},
        {"name": "Grand Theft Auto V", "url": "index.html"},
        {"name": "Rocket League", "url": "index.html"},
        {"name": "Tom Clancy's Rainbow Six: Siege", "url": "index.html"},
        {"name": "Apex Legends", "url": "index.html"},
        {"name": "Delta Force", "url": "index.html"},
        {"name": "Rust", "url": "index.html"},
        {"name": "Tetris", "url": "index.html"},
        {"name": "The Legend of Zelda: Ocarina of Time", "url": "index.html"},
        {"name": "Super Mario 64", "url": "index.html"},
        {"name": "Half-Life 2", "url": "index.html"},
        {"name": "Resident Evil 4", "url": "index.html"},
        {"name": "BioShock", "url": "index.html"},
        {"name": "Final Fantasy VII", "url": "index.html"},
        {"name": "World of Warcraft", "url": "index.html"},
        {"name": "Metal Gear Solid", "url": "index.html"},
        {"name": "Doom", "url": "index.html"},
        {"name": "The Elder Scrolls V: Skyrim", "url": "index.html"},
        {"name": "Mass Effect 2", "url": "index.html"},
        {"name": "The Last of Us", "url": "index.html"},
        {"name": "Super Mario World", "url": "index.html"},
        {"name": "Chrono Trigger", "url": "index.html"},
        {"name": "The Legend of Zelda: A Link to the Past", "url": "index.html"},
        {"name": "Red Dead Redemption", "url": "index.html"},
        {"name": "GoldenEye 007", "url": "index.html"},
        {"name": "Halo: Combat Evolved", "url": "index.html"},
        {"name": "Portal 2", "url": "index.html"},
        {"name": "Minecraft", "url": "index.html"},
        {"name": "Street Fighter II", "url": "index.html"},
        {"name": "Portal", "url": "index.html"},
        {"name": "The Witcher 3", "url": "index.html"},
        {"name": "Super Metroid", "url": "index.html"},
        {"name": "Super Mario Bros.", "url": "index.html"},
        {"name": "Shadow of the Colossus", "url": "index.html"},
        {"name": "Deus Ex", "url": "index.html"},
        {"name": "Super Mario Bros. 3", "url": "index.html"},
        {"name": "Grand Theft Auto V", "url": "index.html"},
        {"name": "Half-Life", "url": "index.html"},
        {"name": "Call of Duty 4: Modern Warfare", "url": "index.html"},
        {"name": "Uncharted 2: Among Thieves", "url": "index.html"},
        {"name": "Grand Theft Auto III", "url": "index.html"},
        {"name": "Metroid Prime", "url": "index.html"},
        {"name": "Starcraft", "url": "index.html"},
        {"name": "Dark Souls", "url": "index.html"},
        {"name": "Castlevania: Symphony of the Night", "url": "index.html"},
        {"name": "The Legend of Zelda: Breath of the Wild", "url": "index.html"},
        {"name": "The Legend of Zelda", "url": "index.html"},
        {"name": "Pokemon Red/Blue", "url": "index.html"},
        {"name": "Super Mario Kart", "url": "index.html"},
        {"name": "Star Wars: Knights of the Old Republic", "url": "index.html"},
        {"name": "Super Mario Galaxy", "url": "index.html"},
        {"name": "Final Fantasy VI", "url": "index.html"},
        {"name": "Fallout 3", "url": "index.html"},
        {"name": "The Legend of Zelda: The Wind Waker", "url": "index.html"},
        {"name": "Metal Gear Solid 3: Snake Eater", "url": "index.html"},
        {"name": "Resident Evil", "url": "index.html"},
        {"name": "Silent Hill 2", "url": "index.html"},
        {"name": "Grand Theft Auto: San Andreas", "url": "index.html"},
        {"name": "Diablo II", "url": "index.html"},
        {"name": "Super Smash Bros. Melee", "url": "index.html"},
        {"name": "Pac-Man", "url": "index.html"},
        {"name": "Journey", "url": "index.html"},
        {"name": "Ico", "url": "index.html"},
        {"name": "Space Invaders", "url": "index.html"},
        {"name": "Grand Theft Auto: Vice City", "url": "index.html"},
        {"name": "Overwatch", "url": "index.html"},
        {"name": "The Sims", "url": "index.html"},
        {"name": "Donkey Kong", "url": "index.html"},
        {"name": "Mario Kart 8", "url": "index.html"},
        {"name": "Super Mario Galaxy 2", "url": "index.html"},
        {"name": "Bloodborne", "url": "index.html"},
        {"name": "Baldur's Gate II", "url": "index.html"},
        {"name": "Tomb Raider", "url": "index.html"},
        {"name": "Team Fortress 2", "url": "index.html"},
        {"name": "Okami", "url": "index.html"},
        {"name": "Batman: Arkham Asylum", "url": "index.html"},
        {"name": "The Secret of Monkey Island", "url": "index.html"},
        {"name": "Mass Effect", "url": "index.html"},
        {"name": "The Walking Dead", "url": "index.html"},
        {"name": "Batman: Arkham City", "url": "index.html"},
        {"name": "Prince of Persia: The Sands of Time", "url": "index.html"},
        {"name": "Sonic the Hedgehog", "url": "index.html"},
        {"name": "Grim Fandango", "url": "index.html"},
        {"name": "The Elder Scrolls IV: Oblivion", "url": "index.html"},
        {"name": "The Legend of Zelda: Majora's Mask", "url": "index.html"},
        {"name": "Wii Sports", "url": "index.html"},
        {"name": "Counter-Strike", "url": "index.html"},
        {"name": "Braid", "url": "index.html"},
        {"name": "Pong", "url": "index.html"},
        {"name": "Final Fantasy X", "url": "index.html"},
        {"name": "Halo 2", "url": "index.html"},
        {"name": "Sid Meier's Civilization", "url": "index.html"},
        {"name": "Halo 3", "url": "index.html"},
        {"name": "System Shock 2", "url": "index.html"},
        {"name": "Mega Man 2", "url": "index.html"},
        {"name": "Super Mario Odyssey", "url": "index.html"},
        {"name": "Grand Theft Auto IV", "url": "index.html"},
        {"name": "Assassin's Creed II", "url": "index.html"},
        {"name": "The Legend of Zelda: Twilight Princess", "url": "index.html"},
        {"name": "Punch-Out!!", "url": "index.html"},
        {"name": "Earthbound", "url": "index.html"},
        {"name": "Metal Gear Solid V: The Phantom Pain", "url": "index.html"},
        {"name": "Resident Evil 2", "url": "index.html"},
        {"name": "Shin Megami Tensei: Persona 4", "url": "index.html"},
        {"name": "Yoshi's Island", "url": "index.html"},
        {"name": "Quake", "url": "index.html"},
        {"name": "Doom (2016)", "url": "index.html"},
        {"name": "God of War", "url": "index.html"},
        {"name": "God of War (2018)", "url": "index.html"},
        {"name": "Rocket League", "url": "index.html"},
        {"name": "Tony Hawk's Pro Skater 2", "url": "index.html"},
        {"name": "Mario Kart 64", "url": "index.html"},
        {"name": "SimCity", "url": "index.html"},
        {"name": "Secret of Mana", "url": "index.html"},
        {"name": "Planescape: Torment", "url": "index.html"},
        {"name": "Gears of War", "url": "index.html"},
        {"name": "Horizon: Zero Dawn", "url": "index.html"},
        {"name": "Metal Gear Solid 2: Sons of Liberty", "url": "index.html"},
        {"name": "Sid Meier's Civilization IV", "url": "index.html"},
        {"name": "The Elder Scrolls III: Morrowind", "url": "index.html"},
        {"name": "Starcraft 2", "url": "index.html"},
        {"name": "Uncharted 4: A Thief's End", "url": "index.html"},
        {"name": "Dead Space", "url": "index.html"},
        {"name": "Red Dead Redemption 2", "url": "index.html"},
        {"name": "NBA Jam", "url": "index.html"},
        {"name": "Sonic the Hedgehog 2", "url": "index.html"},
        {"name": "Ms. Pac-Man", "url": "index.html"},
        {"name": "Stardew Valley", "url": "index.html"},
        {"name": "Nier: Automata", "url": "index.html"},
        {"name": "Final Fantasy Tactics", "url": "index.html"},
        {"name": "Titanfall 2", "url": "index.html"},
        {"name": "Metal Gear Solid 4: Guns of the Patriots", "url": "index.html"},
        {"name": "UFO: Enemy Unknown", "url": "index.html"},
        {"name": "Beyond Good & Evil", "url": "index.html"},
        {"name": "Contra", "url": "index.html"},
        {"name": "Banjo-Kazooie", "url": "index.html"},
        {"name": "Donkey Kong Country", "url": "index.html"},
        {"name": "Burnout 3: Takedown", "url": "index.html"},
        {"name": "SoulCalibur", "url": "index.html"},
        {"name": "BioShock Infinite", "url": "index.html"},
        {"name": "Limbo", "url": "index.html"},
        {"name": "Advance Wars", "url": "index.html"},
        {"name": "Inside", "url": "index.html"},
        {"name": "Fallout: New Vegas", "url": "index.html"},
        {"name": "Shenmue", "url": "index.html"},
        {"name": "The Legend of Zelda: Link's Awakening", "url": "index.html"},
        {"name": "Metroid", "url": "index.html"},
        {"name": "Wolfenstein 3D", "url": "index.html"},
        {"name": "Spelunky", "url": "index.html"},
        {"name": "League of Legends", "url": "index.html"},
        {"name": "Psychonauts", "url": "index.html"},
        {"name": "Myst", "url": "index.html"},
        {"name": "Left 4 Dead", "url": "index.html"},
        {"name": "Dragon Age: Origins", "url": "index.html"},
        {"name": "Sid Meier's Civilization V", "url": "index.html"},
        {"name": "Dance Dance Revolution", "url": "index.html"},
        {"name": "Guitar Hero", "url": "index.html"},
        {"name": "Super Meat Boy", "url": "index.html"},
        {"name": "Age of Empires II: The Age of Kings", "url": "index.html"},
        {"name": "Super Mario RPG: Legend of the Seven Stars", "url": "index.html"},
        {"name": "Maniac Mansion: Day of the Tentacle", "url": "index.html"},
        {"name": "Diablo", "url": "index.html"},
        {"name": "Tekken 3", "url": "index.html"},
        {"name": "Super Smash Bros. Brawl", "url": "index.html"},
        {"name": "Sid Meier's Civilization II", "url": "index.html"},
        {"name": "Star Wars: TIE Fighter", "url": "index.html"},
        {"name": "Resident Evil 7: Biohazard", "url": "index.html"},
        {"name": "Final Fantasy IX", "url": "index.html"},
        {"name": "Bayonetta 2", "url": "index.html"},
        {"name": "Persona 5", "url": "index.html"},
        {"name": "Star Fox 64", "url": "index.html"},
        {"name": "Rock Band", "url": "index.html"},
        {"name": "Xenoblade Chronicles", "url": "index.html"},
        {"name": "Gran Turismo", "url": "index.html"},
        {"name": "Far Cry 3", "url": "index.html"},
        {"name": "Alien: Isolation", "url": "index.html"},
        {"name": "Fortnite", "url": "index.html"},
        {"name": "Dishonored", "url": "index.html"},
        {"name": "Dune II", "url": "index.html"},
        {"name": "Pokemon Gold/Silver", "url": "index.html"},
        {"name": "Eternal Darkness: Sanity's Requiem", "url": "index.html"},
        {"name": "Celeste", "url": "index.html"},
        {"name": "Fallout", "url": "index.html"},
        {"name": "Lemmings", "url": "index.html"},
        {"name": "Duke Nukem 3D", "url": "index.html"},
        {"name": "SimCity 2000", "url": "index.html"},
        {"name": "Warcraft III: Reign of Chaos", "url": "index.html"},
        {"name": "Katamari Damacy", "url": "index.html"},
        {"name": "XCOM: Enemy Unknown", "url": "index.html"},
        {"name": "LittleBigPlanet", "url": "index.html"},
        {"name": "Perfect Dark", "url": "index.html"},
        {"name": "Streets of Rage II", "url": "index.html"},
        {"name": "Diablo III", "url": "index.html"},
        {"name": "Street Fighter IV", "url": "index.html"},
        {"name": "Final Fantasy IV", "url": "index.html"},
        {"name": "Zork I", "url": "index.html"},
        {"name": "Bayonetta", "url": "index.html"},
        {"name": "Elite", "url": "index.html"},
        {"name": "Undertale", "url": "index.html"},
        {"name": "God of War II", "url": "index.html"},
        {"name": "Quake III Arena", "url": "index.html"},
        {"name": "Mass Effect 3", "url": "index.html"},
        {"name": "Final Fantasy XII", "url": "index.html"},
        {"name": "Left 4 Dead 2", "url": "index.html"},
        {"name": "Soul Calibur II", "url": "index.html"},
        {"name": "Unreal Tournament", "url": "index.html"},
        {"name": "Spider-Man (2018)", "url": "index.html"},
        {"name": "Mortal Kombat II", "url": "index.html"},
        {"name": "Shovel Knight", "url": "index.html"},
        {"name": "Kingdom Hearts", "url": "index.html"},
        {"name": "Fallout 4", "url": "index.html"},
        {"name": "Super Smash Bros.", "url": "index.html"},
        {"name": "Super Smash Bros. Ultimate", "url": "index.html"},
        {"name": "Eve Online", "url": "index.html"},
        {"name": "Mortal Kombat", "url": "index.html"},
        {"name": "Hotline Miami", "url": "index.html"},
        {"name": "God of War III", "url": "index.html"},
        {"name": "Burnout Paradise", "url": "index.html"},
        {"name": "Deus Ex: Human Revolution", "url": "index.html"},
        {"name": "Rock Band 3", "url": "index.html"},
        {"name": "F-Zero GX", "url": "index.html"},
        {"name": "Dishonored 2", "url": "index.html"},
        {"name": "Ultima IV: Quest of the Avatar", "url": "index.html"},
        {"name": "Rayman Legends", "url": "index.html"},
        {"name": "Paper Mario: The Thousand-Year Door", "url": "index.html"},
        {"name": "Gran Turismo 3: A-Spec", "url": "index.html"},
        {"name": "Rez", "url": "index.html"},
        {"name": "FTL: Faster Than Light", "url": "index.html"},
        {"name": "Monkey Island 2: LeChuck's Revenge", "url": "index.html"},
        {"name": "Company of Heroes", "url": "index.html"},
        {"name": "Battlefield 1942", "url": "index.html"},
        {"name": "DOTA 2", "url": "index.html"},
        {"name": "Cuphead", "url": "index.html"},
        {"name": "Monster Hunter: World", "url": "index.html"},
        {"name": "Warcraft II: Tides of Darkness", "url": "index.html"},
        {"name": "XCOM 2", "url": "index.html"},
        {"name": "Fallout 2", "url": "index.html"},
        {"name": "Animal Crossing", "url": "index.html"},
        {"name": "Tomb Raider (2013)", "url": "index.html"},
        {"name": "Skies of Arcadia", "url": "index.html"},
        {"name": "Final Fantasy", "url": "index.html"},
        {"name": "Gone Home", "url": "index.html"},
        {"name": "Destiny 2", "url": "index.html"},
        {"name": "Super Mario Sunshine", "url": "index.html"},
        {"name": "Asteroids", "url": "index.html"},
        {"name": "Heavy Rain", "url": "index.html"},
        {"name": "Divinity: Original Sin 2", "url": "index.html"},
        {"name": "Tom Clancy's Splinter Cell: Chaos Theory", "url": "index.html"},
        {"name": "Prince of Persia", "url": "index.html"},
        {"name": "Double Dragon", "url": "index.html"},
        {"name": "R-Type", "url": "index.html"},
        {"name": "Hearthstone", "url": "index.html"},
        {"name": "What Remains of Edith Finch", "url": "index.html"},
        {"name": "Tony Hawk's Pro Skater", "url": "index.html"},
        {"name": "The Legend of Zelda: Skyward Sword", "url": "index.html"},
        {"name": "Kingdom Hearts II", "url": "index.html"},
        {"name": "Borderlands 2", "url": "index.html"},
        {"name": "Suikoden II", "url": "index.html"},
        {"name": "Silent Hill", "url": "index.html"},
        {"name": "Gauntlet", "url": "index.html"},
        {"name": "Fez", "url": "index.html"},
        {"name": "Demon's Souls", "url": "index.html"},
        {"name": "Battlefield 2", "url": "index.html"},
        {"name": "Resident Evil 2", "url": "index.html"},
        {"name": "Mirror's Edge", "url": "index.html"},
        {"name": "PlayerUnknown's Battlegrounds", "url": "index.html"},
        {"name": "Sid Meier's Pirates", "url": "index.html"},
        {"name": "Animal Crossing: New Leaf", "url": "index.html"},
        {"name": "The Witcher 2: Assassins of Kings", "url": "index.html"},
        {"name": "Splatoon 2", "url": "index.html"},
        {"name": "Super Mario Bros. 2", "url": "index.html"},
        {"name": "Counter-Strike: Global Offensive", "url": "index.html"},
        {"name": "OutRun", "url": "index.html"},
        {"name": "Galaga", "url": "index.html"},
        {"name": "Everquest", "url": "index.html"},
        {"name": "Hollow Knight", "url": "index.html"},
        {"name": "Jet Set Radio", "url": "index.html"},
        {"name": "Contra III: The Alien Wars", "url": "index.html"},
        {"name": "Baldur's Gate", "url": "index.html"},
        {"name": "Castlevania", "url": "index.html"},
        {"name": "Bubble Bobble", "url": "index.html"},
        {"name": "Mario + Rabbids Kingdom Battle", "url": "index.html"},
        {"name": "Fire Emblem: Awakening", "url": "index.html"},
        {"name": "Thief II: The Metal Age", "url": "index.html"},
        {"name": "Life Is Strange", "url": "index.html"},
        {"name": "Metroid Prime 3: Corruption", "url": "index.html"},
        {"name": "Devil May Cry", "url": "index.html"},
        {"name": "Ikaruga", "url": "index.html"},
        {"name": "Alone in the Dark", "url": "index.html"},
        {"name": "Assassin's Creed Odyssey", "url": "index.html"},
        {"name": "Forza Horizon 3", "url": "index.html"},
        {"name": "Street Fighter III: Third Strike", "url": "index.html"},
        {"name": "Final Fantasy VIII", "url": "index.html"},
        {"name": "Dragon Quest", "url": "index.html"},
        {"name": "Rome: Total War", "url": "index.html"},
        {"name": "Crash Bandicoot: Warped", "url": "index.html"},
        {"name": "Mega Man X", "url": "index.html"},
        {"name": "Conker's Bad Fur Day", "url": "index.html"},
        {"name": "Robotron: 2084", "url": "index.html"},
        {"name": "Ultima Online", "url": "index.html"},
        {"name": "Uncharted 3: Drake's Deception", "url": "index.html"},
        {"name": "Phantasy Star Online", "url": "index.html"},
        {"name": "Destiny", "url": "index.html"},
        {"name": "Max Payne", "url": "index.html"},
        {"name": "PaRappa the Rapper", "url": "index.html"},
        {"name": "Dragon Quest VIII: Journey of the Cursed King", "url": "index.html"},
        {"name": "Splatoon", "url": "index.html"},
        {"name": "Assassin's Creed IV: Black Flag", "url": "index.html"},
        {"name": "The Witness", "url": "index.html"},
        {"name": "Crazy Taxi", "url": "index.html"},
        {"name": "Marvel vs. Capcom 2: New Age of Heroes", "url": "index.html"},
        {"name": "Outer Wilds", "url": "index.html"},
        {"name": "Homeworld", "url": "index.html"},
        {"name": "Super Mario 3D World", "url": "index.html"},
        {"name": "Dead Cells", "url": "index.html"},
        {"name": "Gears of War 2", "url": "index.html"},
        {"name": "Crash Bandicoot", "url": "index.html"},
        {"name": "Rise of the Tomb Raider", "url": "index.html"},
        {"name": "Ori and the Blind Forest", "url": "index.html"},
        {"name": "Viewtiful Joe", "url": "index.html"},
        {"name": "Ninja Gaiden", "url": "index.html"},
        {"name": "Star Fox", "url": "index.html"},
        {"name": "Gran Turismo 4", "url": "index.html"},
        {"name": "Forza Horizon 4", "url": "index.html"},
        {"name": "Sam & Max Hit the Road", "url": "index.html"},
        {"name": "Teenage Mutant Ninja Turtles: Turtles in Time", "url": "index.html"},
        {"name": "Xenogears", "url": "index.html"},
        {"name": "DuckTales", "url": "index.html"},
        {"name": "Tecmo Super Bowl", "url": "index.html"},
        {"name": "M.U.L.E.", "url": "index.html"},
        {"name": "Fable II", "url": "index.html"},
        {"name": "Dark Souls III", "url": "index.html"},
        {"name": "F-Zero", "url": "index.html"},
        {"name": "Angry Birds", "url": "index.html"},
        {"name": "Ultima Underworld: The Stygian Abyss", "url": "index.html"},
        {"name": "Super Mario Maker", "url": "index.html"},
        {"name": "WarioWare, Inc.: Mega MicroGames!", "url": "index.html"},
        {"name": "Command & Conquer", "url": "index.html"},
        {"name": "Pitfall!", "url": "index.html"},
        {"name": "Devil May Cry 3", "url": "index.html"},
        {"name": "Thief: The Dark Project", "url": "index.html"},
        {"name": "Wolfenstein II: The New Colossus", "url": "index.html"},
        {"name": "Mario Kart DS", "url": "index.html"},
        {"name": "Papers, Please", "url": "index.html"},
        {"name": "Vampire: The Masquerade - Bloodlines", "url": "index.html"},
        {"name": "Until Dawn", "url": "index.html"},
        {"name": "Gunstar Heroes", "url": "index.html"},
        {"name": "Hitman: Blood Money", "url": "index.html"},
        {"name": "Pokemon Go", "url": "index.html"},
        {"name": "Ninja Gaiden", "url": "index.html"},
        {"name": "Mario Kart Wii", "url": "index.html"},
        {"name": "Spacewar!", "url": "index.html"},
        {"name": "Phoenix Wright: Ace Attorney", "url": "index.html"},
        {"name": "Doom II: Hell on Earth", "url": "index.html"},
        {"name": "Mario Kart: Double Dash", "url": "index.html"},
        {"name": "NHL '94", "url": "index.html"},
        {"name": "Maniac Mansion", "url": "index.html"},
        {"name": "The Legend of Zelda: A Link Between Worlds", "url": "index.html"},
        {"name": "Lumines", "url": "index.html"},
        {"name": "Shenmue II", "url": "index.html"},
        {"name": "Into the Breach", "url": "index.html"},
        {"name": "Alan Wake", "url": "index.html"},
        {"name": "Adventure", "url": "index.html"},
        {"name": "TimeSplitters 2", "url": "index.html"},
        {"name": "Rock Band 2", "url": "index.html"},
        {"name": "Metroid Prime 2: Echoes", "url": "index.html"},
        {"name": "Final Fantasy XIV: A Realm Reborn", "url": "index.html"},
        {"name": "Bastion", "url": "index.html"},
        {"name": "Wave Race 64", "url": "index.html"},
        {"name": "Kerbal Space Program", "url": "index.html"},
        {"name": "Tom Clancy's Splinter Cell", "url": "index.html"},
        {"name": "Kentucky Route Zero", "url": "index.html"},
        {"name": "Tecmo Bowl", "url": "index.html"},
        {"name": "The Chronicles of Riddick: Escape from Butcher Bay", "url": "index.html"},
        {"name": "Amnesia: The Dark Descent", "url": "index.html"},
        {"name": "Earthworm Jim", "url": "index.html"},
        {"name": "Command & Conquer: Red Alert", "url": "index.html"},
        {"name": "Chrono Cross", "url": "index.html"},
        {"name": "Return of the Obra Dinn", "url": "index.html"},
        {"name": "Super Smash Bros. for Wii U", "url": "index.html"},
        {"name": "Super Castlevania IV", "url": "index.html"},
        {"name": "The World Ends With You", "url": "index.html"},
        {"name": "Donkey Kong", "url": "index.html"},
        {"name": "Sekiro: Shadows Die Twice", "url": "index.html"},
        {"name": "Donkey Kong Country Returns", "url": "index.html"},
        {"name": "Street Fighter II Turbo: Hyper Fighting", "url": "index.html"},
        {"name": "Donkey Kong Country 2", "url": "index.html"},
        {"name": "Metroid II: Return of Samus", "url": "index.html"},
        {"name": "Tom Clancy's Rainbow Six Siege", "url": "index.html"},
        {"name": "Bionic Commando", "url": "index.html"},
        {"name": "Tetris Effect", "url": "index.html"},
        {"name": "New Super Mario Bros.", "url": "index.html"},
        {"name": "Pikmin 2", "url": "index.html"},
        {"name": "Donkey Kong Country: Tropical Freeze", "url": "index.html"},
        {"name": "The Longest Journey", "url": "index.html"},
        {"name": "Call of Duty", "url": "index.html"},
        {"name": "Defender", "url": "index.html"},
        {"name": "Sega Rally Championship", "url": "index.html"},
        {"name": "SSX 3", "url": "index.html"},
        {"name": "Golden Axe", "url": "index.html"},
        {"name": "Hitman", "url": "index.html"},
        {"name": "Shin Megami Tensei: Persona 3", "url": "index.html"},
        {"name": "Another World", "url": "index.html"},
        {"name": "Halo: Reach", "url": "index.html"},
        {"name": "Wizardry: Proving Grounds of the Mad Overlord", "url": "index.html"},
        {"name": "Dungeon Master", "url": "index.html"},
        {"name": "Borderlands", "url": "index.html"},
        {"name": "The Last Guardian", "url": "index.html"},
        {"name": "Quake II", "url": "index.html"},
        {"name": "Yakuza 0", "url": "index.html"},
        {"name": "Tony Hawk's Pro Skater 3", "url": "index.html"},
        {"name": "King's Quest", "url": "index.html"},
        {"name": "Assassin's Creed: Brotherhood", "url": "index.html"},
        {"name": "Metal Gear Solid: Peace Walker", "url": "index.html"},
        {"name": "Halo 4", "url": "index.html"},
        {"name": "Gran Turismo 2", "url": "index.html"},
        {"name": "World of Goo", "url": "index.html"},
        {"name": "Cave Story", "url": "index.html"},
        {"name": "NiGHTS into Dreams...", "url": "index.html"},
        {"name": "Battlefield: Bad Company 2", "url": "index.html"},
        {"name": "Paper Mario", "url": "index.html"},
        {"name": "John Madden Football", "url": "index.html"},
        {"name": "Dragon Age: Inquisition", "url": "index.html"},
        {"name": "Control", "url": "index.html"},
        {"name": "ActRaiser", "url": "index.html"},
        {"name": "Panzer Dragoon Saga", "url": "index.html"},
        {"name": "Her Story", "url": "index.html"},
        {"name": "Grand Theft Auto: Chinatown Wars", "url": "index.html"},
        {"name": "Wipeout 2097", "url": "index.html"},
        {"name": "Command & Conquer: Red Alert 2", "url": "index.html"},
        {"name": "F.E.A.R.", "url": "index.html"},
        {"name": "New Super Mario Bros. Wii", "url": "index.html"},
        {"name": "Mario & Luigi: Superstar Saga", "url": "index.html"},
        {"name": "Mega Man 3", "url": "index.html"},
        {"name": "Valkyria Chronicles", "url": "index.html"},
        {"name": "Battlefield 1", "url": "index.html"},
        {"name": "Phantasy Star IV: The End of the Millennium", "url": "index.html"},
        {"name": "Wipeout", "url": "index.html"},
        {"name": "River City Ransom", "url": "index.html"},
        {"name": "The Oregon Trail", "url": "index.html"},
        {"name": "Ultima VII: The Black Gate", "url": "index.html"},
        {"name": "Sid Meier's Civilization VI", "url": "index.html"},
        {"name": "Elite Beat Agents", "url": "index.html"},
        {"name": "Super Mario Land 2: 6 Golden Coins", "url": "index.html"},
        {"name": "Saints Row: The Third", "url": "index.html"},
        {"name": "Guitar Hero II", "url": "index.html"},
        {"name": "Tempest", "url": "index.html"},
        {"name": "Firewatch", "url": "index.html"},
        {"name": "Geometry Wars: Retro Evolved 2", "url": "index.html"},
        {"name": "Syndicate", "url": "index.html"},
        {"name": "Max Payne 2: The Fall of Max Payne", "url": "index.html"},
        {"name": "The Sims 2", "url": "index.html"},
        {"name": "Populous", "url": "index.html"},
        {"name": "Legacy of Kain: Soul Reaver", "url": "index.html"},
        {"name": "Zelda II: The Adventure of Link", "url": "index.html"},
        {"name": "Pole Position", "url": "index.html"},
        {"name": "Metroid Fusion", "url": "index.html"},
        {"name": "Vagrant Story", "url": "index.html"},
        {"name": "Crysis", "url": "index.html"},
        {"name": "Star Wars", "url": "index.html"},
        {"name": "Star Wars Rogue Squadron II: Rogue Leader", "url": "index.html"},
        {"name": "Uncharted: Drake's Fortune", "url": "index.html"},
        {"name": "Death Stranding", "url": "index.html"},
        {"name": "Killer7", "url": "index.html"},
        {"name": "Castlevania III: Dracula's Curse", "url": "index.html"},
        {"name": "Sonic Mania", "url": "index.html"},
        {"name": "Apex Legends", "url": "index.html"},
        {"name": "Pokemon Yellow", "url": "index.html"},
        {"name": "Mario Kart 7", "url": "index.html"},
        {"name": "Final Fight", "url": "index.html"},
        {"name": "Thumper", "url": "index.html"},
        {"name": "Middle-Earth: Shadow Of Mordor", "url": "index.html"},
        {"name": "Call of Duty: Modern Warfare 2", "url": "index.html"},
        {"name": "Castlevania: Aria of Sorrow", "url": "index.html"},
        {"name": "Super Monkey Ball", "url": "index.html"},
        {"name": "Spec Ops: The Line", "url": "index.html"},
        {"name": "Mega Man", "url": "index.html"},
        {"name": "Ratchet & Clank: Up Your Arsenal", "url": "index.html"},
        {"name": "Daytona USA", "url": "index.html"},
        {"name": "Jak and Daxter: The Precursor Legacy", "url": "index.html"},
        {"name": "Sonic the Hedgehog 3", "url": "index.html"},
        {"name": "Crusader Kings II", "url": "index.html"},
        {"name": "Disco Elysium", "url": "index.html"},
        {"name": "Kirby's Adventure", "url": "index.html"},
        {"name": "Super Punch-Out!!", "url": "index.html"},
        {"name": "Cities: Skylines", "url": "index.html"},
        {"name": "Hellblade: Senua's Sacrifice", "url": "index.html"},
        {"name": "Assassin's Creed Origins", "url": "index.html"},
        {"name": "Guild Wars 2", "url": "index.html"},
        {"name": "80 Days", "url": "index.html"},
        {"name": "Threes", "url": "index.html"},
        {"name": "Resident Evil - Code: Veronica", "url": "index.html"},
        {"name": "Super Hexagon", "url": "index.html"},
        {"name": "Counter-Strike: Source", "url": "index.html"},
        {"name": "The Legend of Zelda: The Minish Cap", "url": "index.html"},
        {"name": "Ghosts 'n Goblins", "url": "index.html"},
        {"name": "Madden NFL 2005", "url": "index.html"},
        {"name": "Manic Miner", "url": "index.html"},
        {"name": "Pokemon Black/White", "url": "index.html"},
        {"name": "Super Mario 3D Land", "url": "index.html"},
        {"name": "Battlefield 3", "url": "index.html"},
        {"name": "Aladdin", "url": "index.html"},
        {"name": "Star Wars Jedi Knight: Dark Forces II", "url": "index.html"},
        {"name": "ESPN NFL 2K5", "url": "index.html"},
        {"name": "Monument Valley", "url": "index.html"},
        {"name": "LittleBigPlanet 2", "url": "index.html"},
        {"name": "Final Fantasy XV", "url": "index.html"},
        {"name": "Batman: Arkham Knight", "url": "index.html"},
        {"name": "Crackdown", "url": "index.html"},
        {"name": "Luigi's Mansion", "url": "index.html"},
        {"name": "Indiana Jones and the Fate of Atlantis", "url": "index.html"},
        {"name": "WWF No Mercy", "url": "index.html"},
        {"name": "Super Street Fighter IV", "url": "index.html"},
        {"name": "Ultima I", "url": "index.html"},
        {"name": "Metal Gear", "url": "index.html"},
        {"name": "Virtua Fighter 2", "url": "index.html"},
        {"name": "Sensible World of Soccer", "url": "index.html"},
        {"name": "Unreal Tournament 2004", "url": "index.html"},
        {"name": "Killer Instinct", "url": "index.html"},
        {"name": "Twisted Metal 2", "url": "index.html"},
        {"name": "Hitman 2", "url": "index.html"},
        {"name": "Peggle", "url": "index.html"},
        {"name": "Condemned", "url": "index.html"},
        {"name": "Flashback", "url": "index.html"},
        {"name": "Age of Empires", "url": "index.html"},
        {"name": "The Legend of Zelda: Phantom Hourglass", "url": "index.html"},
        {"name": "Virtua Fighter 4", "url": "index.html"},
        {"name": "System Shock", "url": "index.html"},
        {"name": "Duck Hunt", "url": "index.html"},
        {"name": "Street Fighter Alpha III", "url": "index.html"},
        {"name": "Broken Sword: The Shadow of the Templars", "url": "index.html"},
        {"name": "Tetris Attack", "url": "index.html"},
        {"name": "Missile Command", "url": "index.html"},
        {"name": "Pokemon Ruby/Sapphire", "url": "index.html"},
        {"name": "Arms", "url": "index.html"},
        {"name": "Super Mario Land", "url": "index.html"},
        {"name": "Call of Duty: Black Ops", "url": "index.html"},
        {"name": "Metal Slug", "url": "index.html"},
        {"name": "Animal Crossing: Wild World", "url": "index.html"},
        {"name": "No Man's Sky", "url": "index.html"},
        {"name": "Dr. Mario", "url": "index.html"},
        {"name": "Star Wars: Knights of the Old Republic II", "url": "index.html"},
        {"name": "The Sims 3", "url": "index.html"},
        {"name": "Geometry Wars: Retro Evolved", "url": "index.html"},
        {"name": "Virtua Fighter", "url": "index.html"},
        {"name": "Tales of Symphonia", "url": "index.html"},
        {"name": "Fire Emblem", "url": "index.html"},
        {"name": "Sonic & Knuckles", "url": "index.html"},
        {"name": "WarioWare: Twisted!", "url": "index.html"},
        {"name": "Golden Sun", "url": "index.html"},
        {"name": "Pokemon X/Y", "url": "index.html"},
        {"name": "Mafia: The City of Lost Heaven", "url": "index.html"},
        {"name": "Kid Icarus", "url": "index.html"},
        {"name": "Super Puzzle Fighter II Turbo", "url": "index.html"},
        {"name": "FIFA 12", "url": "index.html"},
        {"name": "Grand Theft Auto", "url": "index.html"},
        {"name": "Tekken 5", "url": "index.html"},
        {"name": "Far Cry", "url": "index.html"},
        {"name": "Bully", "url": "index.html"},
        {"name": "Far Cry 4", "url": "index.html"},
        {"name": "Fire Emblem: Three Houses", "url": "index.html"},
        {"name": "S.T.A.L.K.E.R.: Shadow of Chernobyl", "url": "index.html"},
        {"name": "Wing Commander", "url": "index.html"},
        {"name": "Dragon's Lair", "url": "index.html"},
        {"name": "Pokemon Sun/Moon", "url": "index.html"},
        {"name": "Dead Rising", "url": "index.html"},
        {"name": "Ultima III: Exodus", "url": "index.html"},
        {"name": "L.A. Noire", "url": "index.html"},
        {"name": "Speedball 2: Brutal Deluxe", "url": "index.html"},
        {"name": "F-Zero X", "url": "index.html"},
        {"name": "Jet Set Radio Future", "url": "index.html"},
        {"name": "Plants vs. Zombies", "url": "index.html"},
        {"name": "The Curse of Monkey Island", "url": "index.html"},
        {"name": "Devil May Cry 5", "url": "index.html"},
        {"name": "Pokemon: Let's Go, Pikachu! and Let's Go, Eevee!", "url": "index.html"},
        {"name": "Rayman 2: The Great Escape", "url": "index.html"},
        {"name": "Ratchet & Clank", "url": "index.html"},
        {"name": "Tomb Raider II", "url": "index.html"},
        {"name": "Star Wars: Battlefront II", "url": "index.html"},
        {"name": "Pro Evolution Soccer 6", "url": "index.html"},
        {"name": "The Legend of Zelda: Oracle of Seasons/Ages", "url": "index.html"},
        {"name": "Castle Crashers", "url": "index.html"},
        {"name": "Freespace 2", "url": "index.html"},
        {"name": "Pikmin", "url": "index.html"},
        {"name": "Prey", "url": "index.html"},
        {"name": "Star Control II", "url": "index.html"},
        {"name": "Gears of War 4", "url": "index.html"},
        {"name": "Sid Meier's Civilization III", "url": "index.html"},
        {"name": "Super Hot", "url": "index.html"},
        {"name": "Shining Force II", "url": "index.html"},
        {"name": "Fable", "url": "index.html"},
        {"name": "Halo 5: Guardians", "url": "index.html"},
        {"name": "Manhunt", "url": "index.html"},
        {"name": "Battletoads", "url": "index.html"},
        {"name": "Ridge Racer", "url": "index.html"},
        {"name": "Night in the Woods", "url": "index.html"},
        {"name": "Metal Gear Solid: The Twin Snakes", "url": "index.html"},
        {"name": "Pikmin 3", "url": "index.html"},
        {"name": "Divinity: Original Sin", "url": "index.html"},
        {"name": "Fatal Frame II: Crimson Butterfly", "url": "index.html"},
        {"name": "Uncharted: The Lost Legacy", "url": "index.html"},
        {"name": "Herzog Zwei", "url": "index.html"},
        {"name": "Bulletstorm", "url": "index.html"},
        {"name": "Injustice 2", "url": "index.html"},
        {"name": "Battlezone", "url": "index.html"},
        {"name": "Excitebike", "url": "index.html"},
        {"name": "Disgaea: Hour of Darkness", "url": "index.html"},
        {"name": "Superbrothers: Sword & Sworcery EP", "url": "index.html"},
        {"name": "Guardian Heroes", "url": "index.html"},
        {"name": "Sea of Thieves", "url": "index.html"},
        {"name": "Wii Sports Resort", "url": "index.html"},
        {"name": "Spyro the Dragon", "url": "index.html"},
        {"name": "New Super Mario Bros. U", "url": "index.html"},
        {"name": "Dead Space 2", "url": "index.html"},
        {"name": "Full Throttle", "url": "index.html"},
        {"name": "Virtua Tennis", "url": "index.html"},
        {"name": "Gabriel Knight: Sins of the Fathers", "url": "index.html"},
        {"name": "Flower", "url": "index.html"},
        {"name": "Dragon Quest III", "url": "index.html"},
        {"name": "Final Fantasy Tactics Advance", "url": "index.html"},
        {"name": "Xenoblade Chronicles 2", "url": "index.html"},
        {"name": "Super Bomberman", "url": "index.html"},
        {"name": "MechWarrior 2: 31st Century Combat", "url": "index.html"},
        {"name": "Golf Story", "url": "index.html"},
        {"name": "Diddy Kong Racing", "url": "index.html"},
        {"name": "Dark Souls II", "url": "index.html"},
        {"name": "Infamous 2", "url": "index.html"},
        {"name": "Metroid Zero Mission", "url": "index.html"},
        {"name": "Worms", "url": "index.html"},
        {"name": "Enslaved: Odyssey to the West", "url": "index.html"},
        {"name": "Darkest Dungeon", "url": "index.html"},
        {"name": "Sonic CD", "url": "index.html"},
        {"name": "Pokemon HeartGold/SoulSilver", "url": "index.html"},
        {"name": "Jade Empire", "url": "index.html"},
        {"name": "Dragon Quest IV: Chapters of the Chosen", "url": "index.html"},
        {"name": "Comix Zone", "url": "index.html"},
        {"name": "Mario Tennis", "url": "index.html"},
        {"name": "Far Cry 2", "url": "index.html"},
        {"name": "Black & White", "url": "index.html"},
        {"name": "Worms Armageddon", "url": "index.html"},
        {"name": "Total War: Shogun 2", "url": "index.html"},
        {"name": "Sunset Overdrive", "url": "index.html"},
        {"name": "Captain Toad: Treasure Tracker", "url": "index.html"},
        {"name": "Monster Hunter 4 Ultimate", "url": "index.html"},
        {"name": "After Burner", "url": "index.html"},
        {"name": "Castlevania: Dawn of Sorrow", "url": "index.html"},
        {"name": "Boulder Dash", "url": "index.html"},
        {"name": "Vanquish", "url": "index.html"},
        {"name": "Mark of the Ninja", "url": "index.html"},
        {"name": "Archon", "url": "index.html"},
        {"name": "Wolfenstein: The New Order", "url": "index.html"},
        {"name": "Ape Escape", "url": "index.html"},
        {"name": "Frogger", "url": "index.html"},
        {"name": "God of War: Chains of Olympus", "url": "index.html"},
        {"name": "Forza Motorsport 4", "url": "index.html"},
        {"name": "Phantasy Star", "url": "index.html"},
        {"name": "Neverwinter Nights", "url": "index.html"},
        {"name": "Slaves to Armok II: Dwarf Fortress", "url": "index.html"},
        {"name": "Dragon Ball FighterZ", "url": "index.html"},
        {"name": "Radiant Silvergun", "url": "index.html"},
        {"name": "Medal of Honor", "url": "index.html"},
        {"name": "Strider", "url": "index.html"},
        {"name": "999: 9 Hours, 9 Persons, 9 Doors", "url": "index.html"},
        {"name": "Wasteland", "url": "index.html"},
        {"name": "Ghost Trick: Phantom Detective", "url": "index.html"},
        {"name": "Saturn Bomberman", "url": "index.html"},
        {"name": "Sonic Adventure", "url": "index.html"},
        {"name": "Slay the Spire", "url": "index.html"},
        {"name": "Baseball Stars", "url": "index.html"},
        {"name": "Dying Light", "url": "index.html"},
        {"name": "Power Stone 2", "url": "index.html"},
        {"name": "Outlast", "url": "index.html"},
        {"name": "Bejeweled", "url": "index.html"},
        {"name": "Madden NFL 2004", "url": "index.html"},
        {"name": "Professor Layton and the Curious Village", "url": "index.html"},
        {"name": "Rainbow Islands", "url": "index.html"},
        {"name": "Donkey Kong Jungle Beat", "url": "index.html"},
        {"name": "Pokemon Diamond and Pearl", "url": "index.html"},
        {"name": "Ridiculous Fishing", "url": "index.html"},
        {"name": "King's Quest VI: Heir Today, Gone Tomorrow", "url": "index.html"},
        {"name": "Starsiege: Tribes", "url": "index.html"},
        {"name": "Ratchet & Clank: A Crack in Time", "url": "index.html"},
        {"name": "The Stanley Parable", "url": "index.html"},
        {"name": "Pro Evolution Soccer 3", "url": "index.html"},
        {"name": "Sensible Soccer", "url": "index.html"},
        {"name": "Centipede", "url": "index.html"},
        {"name": "Puyo Puyo Tetris", "url": "index.html"},
        {"name": "1080 Snowboarding", "url": "index.html"},
        {"name": "Shadow Complex", "url": "index.html"},
        {"name": "Animal Crossing: New Horizons", "url": "index.html"},
        {"name": "SOMA", "url": "index.html"},
        {"name": "Sonic Adventure 2", "url": "index.html"},
        {"name": "Elite: Dangerous", "url": "index.html"},
        {"name": "Killzone 2", "url": "index.html"},
        {"name": "Samurai Shodown II", "url": "index.html"},
        {"name": "Super Paper Mario", "url": "index.html"},
        {"name": "Ys Book I & II", "url": "index.html"},
        {"name": "The Operative: No One Lives Forever", "url": "index.html"},
        {"name": "Mother 3", "url": "index.html"},
        {"name": "Thief: Deadly Shadows", "url": "index.html"},
        {"name": "Oddworld: Stranger's Wrath", "url": "index.html"},
        {"name": "Marble Madness", "url": "index.html"},
        {"name": "Hades", "url": "index.html"},
        {"name": "Tron", "url": "index.html"},
        {"name": "South Park: The Stick of Truth", "url": "index.html"},
        {"name": "Snipperclips", "url": "index.html"},
        {"name": "LEGO Star Wars", "url": "index.html"},
        {"name": "Super Smash Bros For 3DS", "url": "index.html"},
        {"name": "Octopath Traveler", "url": "index.html"},
        {"name": "Super Mario All-Stars", "url": "index.html"},
        {"name": "Impossible Mission", "url": "index.html"},
        {"name": "Warhammer 40,000: Dawn of War", "url": "index.html"},
        {"name": "Call of Duty 2", "url": "index.html"},
        {"name": "Puzzle Bobble", "url": "index.html"},
        {"name": "Joust", "url": "index.html"},
        {"name": "Final Fantasy III", "url": "index.html"},
        {"name": "Subnautica", "url": "index.html"},
        {"name": "Dungeon Keeper", "url": "index.html"},
        {"name": "Virtua Racing", "url": "index.html"},
        {"name": "DayZ", "url": "index.html"},
        {"name": "Syphon Filter", "url": "index.html"},
        {"name": "Paradroid", "url": "index.html"},
        {"name": "X-Men", "url": "index.html"},
        {"name": "The Simpsons", "url": "index.html"},
        {"name": "NBA 2K11", "url": "index.html"},
        {"name": "Project Gotham Racing 2", "url": "index.html"},
        {"name": "NBA Street Vol. 2", "url": "index.html"},
        {"name": "Pokemon Sword / Shield", "url": "index.html"},
        {"name": "Streets Of Rage", "url": "index.html"},
        {"name": "Nethack", "url": "index.html"},
        {"name": "Gears of War 3", "url": "index.html"},
        {"name": "Ni No Kuni: Wrath of the White Witch", "url": "index.html"},
        {"name": "Pro Evolution Soccer 4", "url": "index.html"},
        {"name": "Untitled Goose Game", "url": "index.html"},
        {"name": "Donkey Kong 64", "url": "index.html"},
        {"name": "Tetris 99", "url": "index.html"},
        {"name": "Blast Corps", "url": "index.html"},
        {"name": "Dragon Quest V", "url": "index.html"},
        {"name": "Sleeping Dogs", "url": "index.html"},
        {"name": "Spy Hunter", "url": "index.html"},
        {"name": "Pilotwings", "url": "index.html"},
        {"name": "Advance Wars: Dual Strike", "url": "index.html"},
        {"name": "The Last of Us Part II", "url": "index.html"},
        {"name": "Towerfall Ascension", "url": "index.html"},
        {"name": "Pokemon Snap", "url": "index.html"},
        {"name": "Assassin's Creed", "url": "index.html"},
        {"name": "Star Wars Jedi Knight II: Jedi Outcast", "url": "index.html"},
        {"name": "Kirby's Dream Land", "url": "index.html"},
        {"name": "Bard's Tale", "url": "index.html"},
        {"name": "Florence", "url": "index.html"},
        {"name": "Hitman 2: Silent Assassin", "url": "index.html"},
        {"name": "Tom Clancy's Rainbow Six", "url": "index.html"},
        {"name": "Forza Motorsport 7", "url": "index.html"},
        {"name": "Dragon Quest IX: Sentinels of the Starry Skies", "url": "index.html"},
        {"name": "Silent Hills: P.T.", "url": "index.html"},
        {"name": "Super Ghouls 'n Ghosts", "url": "index.html"},
        {"name": "Sid Meier's Alpha Centauri", "url": "index.html"},
        {"name": "R.C. Pro-Am", "url": "index.html"},
        {"name": "Star Wars: Rogue Squadron", "url": "index.html"},
        {"name": "Samurai Shodown", "url": "index.html"},
        {"name": "Rogue", "url": "index.html"},
        {"name": "Need for Speed: Most Wanted", "url": "index.html"},
        {"name": "The Legend of Zelda: Four Swords Adventures", "url": "index.html"},
        {"name": "Zack & Wiki: Quest for Barbaros' Treasure", "url": "index.html"},
        {"name": "Lego Star Wars II: The Original Trilogy", "url": "index.html"},
        {"name": "Wing Commander III: Heart of the Tiger", "url": "index.html"},
        {"name": "NFL Blitz", "url": "index.html"},
        {"name": "Crash Bandicoot 2: Cortex Strikes Back", "url": "index.html"},
        {"name": "Rayman Origins", "url": "index.html"},
        {"name": "Ratchet & Clank", "url": "index.html"},
        {"name": "Ultima VI: The False Prophet", "url": "index.html"},
        {"name": "Supreme Commander", "url": "index.html"},
        {"name": "Punch-Out", "url": "index.html"},
        {"name": "Oddworld: Abe's Oddysee", "url": "index.html"},
        {"name": "Kirby's Epic Yarn", "url": "index.html"},
        {"name": "Mario Party", "url": "index.html"},
        {"name": "Wario Land: Super Mario Land 3", "url": "index.html"},
        {"name": "Time Crisis", "url": "index.html"},
        {"name": "Forza Motorsport 3", "url": "index.html"},
        {"name": "Drop7", "url": "index.html"},
        {"name": "Xenoblade Chronicles X", "url": "index.html"},
        {"name": "Head Over Heels", "url": "index.html"},
        {"name": "Nidhogg", "url": "index.html"},
        {"name": "Monster Hunter Tri", "url": "index.html"},
        {"name": "The Room", "url": "index.html"},
        {"name": "SSX Tricky", "url": "index.html"},
        {"name": "Tom Clancy's Splinter Cell: Pandora Tomorrow", "url": "index.html"},
        {"name": "Tempest 2000", "url": "index.html"},
        {"name": "Road Rash", "url": "index.html"},
        {"name": "Alien Vs Predator", "url": "index.html"},
        {"name": "Teenage Mutant Ninja Turtles", "url": "index.html"},
        {"name": "The House of the Dead 2", "url": "index.html"},
        {"name": "Master of Orion", "url": "index.html"},
        {"name": "BioShock 2", "url": "index.html"},
        {"name": "Call of Duty: Black Ops II", "url": "index.html"},
        {"name": "Castle of Illusion Starring Mickey Mouse", "url": "index.html"},
        {"name": "Middle-Earth: Shadow of War", "url": "index.html"},
        {"name": "Lode Runner", "url": "index.html"},
        {"name": "IL-2 Sturmovik", "url": "index.html"},
        {"name": "Medal of Honor: Allied Assault", "url": "index.html"},
        {"name": "Castlevania: Rondo of Blood", "url": "index.html"},
        {"name": "Blades of Steel", "url": "index.html"},
        {"name": "Titanfall", "url": "index.html"},
        {"name": "Arkanoid", "url": "index.html"},
        {"name": "Frontier: Elite II", "url": "index.html"},
        {"name": "Dr. Kawashima's Brain Training", "url": "index.html"},
        {"name": "Tales From The Borderlands", "url": "index.html"},
        {"name": "Bomberman", "url": "index.html"},
        {"name": "Jak II", "url": "index.html"},
        {"name": "Ghouls 'n Ghosts", "url": "index.html"},
        {"name": "Deadly Premonition", "url": "index.html"},
        {"name": "The Sims 4", "url": "index.html"},
        {"name": "Lost Odyssey", "url": "index.html"},
        {"name": "Professor Layton & The Unwound Future", "url": "index.html"},
        {"name": "Fahrenheit", "url": "index.html"},
        {"name": "Total Annihilation", "url": "index.html"},
        {"name": "Fatal Fury: Mark of the Wolves", "url": "index.html"},
        {"name": "Phantasy Star II", "url": "index.html"},
        {"name": "No More Heroes", "url": "index.html"},
        {"name": "Shinobi", "url": "index.html"},
        {"name": "Puzzle Quest", "url": "index.html"},
        {"name": "Beneath a Steel Sky", "url": "index.html"},
        {"name": "Theme Park", "url": "index.html"},
        {"name": "Oxenfree", "url": "index.html"},
        {"name": "Device 6", "url": "index.html"},
        {"name": "ARMA 3", "url": "index.html"},
        {"name": "Mario & Luigi: Bowser's Inside Story", "url": "index.html"},
        {"name": "Pro Evolution Soccer 5", "url": "index.html"},
        {"name": "Forza Motorsport", "url": "index.html"},
        {"name": "Luigi's Mansion 3", "url": "index.html"},
        {"name": "Path of Exile", "url": "index.html"},
        {"name": "Wing Commander II: Vengeance of the Kilrathi", "url": "index.html"},
        {"name": "Jet Force Gemini", "url": "index.html"},
        {"name": "Tekken 7", "url": "index.html"},
        {"name": "Total War: Warhammer II", "url": "index.html"},
        {"name": "Sin & Punishment: Successor to the Sky", "url": "index.html"},
        {"name": "Pac-Man Championship Edition DX", "url": "index.html"},
        {"name": "BurgerTime", "url": "index.html"},
        {"name": "Star Raiders", "url": "index.html"},
        {"name": "Final Fantasy V", "url": "index.html"},
        {"name": "Zero Escape: Virtue's Last Reward", "url": "index.html"},
        {"name": "Dragon Quest XI", "url": "index.html"},
        {"name": "Blaster Master", "url": "index.html"},
        {"name": "Luigi's Mansion 2", "url": "index.html"},
        {"name": "The Outer Worlds", "url": "index.html"},
        {"name": "Banjo-Tooie", "url": "index.html"},
        {"name": "Leisure Suit Larry in the Land of the Lounge Lizards", "url": "index.html"},
        {"name": "Terraria", "url": "index.html"},
        {"name": "Virtua Fighter 5", "url": "index.html"},
        {"name": "Chuckie Egg", "url": "index.html"},
        {"name": "Crash Team Racing", "url": "index.html"},
        {"name": "Jet Set Willy", "url": "index.html"},
        {"name": "Fire Emblem: Path of Radiance", "url": "index.html"},
        {"name": "Heroes of Might and Magic III: The Restoration of Erathia", "url": "index.html"},
        {"name": "Catherine", "url": "index.html"},
        {"name": "Gorogoa", "url": "index.html"},
        {"name": "The Wonderful 101", "url": "index.html"},
        {"name": "Overcooked", "url": "index.html"},
        {"name": "Samba de Amigo", "url": "index.html"},
        {"name": "Pac-Man Championship Edition", "url": "index.html"},
        {"name": "Shining Force III", "url": "index.html"},
        {"name": "S.T.A.L.K.E.R.: Call of Pripyat", "url": "index.html"},
        {"name": "Ratchet & Clank: Going Commando", "url": "index.html"},
        {"name": "MVP Baseball 2005", "url": "index.html"},
        {"name": "FIFA 10", "url": "index.html"},
        {"name": "The Elder Scrolls II: Daggerfall", "url": "index.html"},
        {"name": "Nioh", "url": "index.html"},
        {"name": "Klonoa: Door to Phantomile", "url": "index.html"},
        {"name": "No More Heroes 2: Desperate Struggle", "url": "index.html"},
        {"name": "Crimson Skies", "url": "index.html"},
        {"name": "Mortal Kombat X", "url": "index.html"},
        {"name": "Infamous", "url": "index.html"},
        {"name": "Brothers: A Tale of Two Sons", "url": "index.html"},
        {"name": "Kirby's Dream Land 2", "url": "index.html"},
        {"name": "Super Mario Maker 2", "url": "index.html"},
        {"name": "Trials Evolution", "url": "index.html"},
        {"name": "Dragon Force", "url": "index.html"},
        {"name": "Halo 3: ODST", "url": "index.html"},
        {"name": "Battlefield 4", "url": "index.html"},
        {"name": "Donkey Kong Jr.", "url": "index.html"},
        {"name": "Double Dragon II: The Revenge", "url": "index.html"},
        {"name": "Wipeout HD", "url": "index.html"},
        {"name": "Tom Clancy's Rainbow Six 3: Raven Shield", "url": "index.html"},
        {"name": "Sins of a Solar Empire", "url": "index.html"},
        {"name": "Nintendogs", "url": "index.html"},
        {"name": "Pokemon Crystal", "url": "index.html"},
        {"name": "Guild Wars", "url": "index.html"},
        {"name": "Gargoyle's Quest", "url": "index.html"},
        {"name": "Jak 3", "url": "index.html"},
        {"name": "Galaxian", "url": "index.html"},
        {"name": "Driver", "url": "index.html"},
        {"name": "Operation Flashpoint: Cold War Crisis", "url": "index.html"},
        {"name": "Sly Cooper and the Thievius Raccoonus", "url": "index.html"},
        {"name": "Roller Coaster Tycoon", "url": "index.html"},
        {"name": "The Binding of Isaac", "url": "index.html"},
        {"name": "Astro Boy: Omega Factor", "url": "index.html"},
        {"name": "Cannon Fodder", "url": "index.html"},
        {"name": "Machinarium", "url": "index.html"},
        {"name": "Pokken Tournament", "url": "index.html"},
        {"name": "Thunder Force IV", "url": "index.html"},
        {"name": "Gradius", "url": "index.html"},
        {"name": "Saints Row IV", "url": "index.html"},
        {"name": "Operation Wolf", "url": "index.html"},
        {"name": "Guacamelee!", "url": "index.html"},
        {"name": "Final Fantasy Adventure", "url": "index.html"},
        {"name": "God Hand", "url": "index.html"},
        {"name": "Gran Turismo 5", "url": "index.html"},
        {"name": "E.T. the Extra-Terrestrial", "url": "index.html"},
        {"name": "Landstalker: The Treasures of King Nole", "url": "index.html"},
        {"name": "Warcraft: Orcs and Humans", "url": "index.html"},
        {"name": "God of War: Ghost of Sparta", "url": "index.html"},
        {"name": "Spyro 2: Ripto's Rage", "url": "index.html"},
        {"name": "Lunar: Eternal Blue", "url": "index.html"},
        {"name": "Far Cry 5", "url": "index.html"},
        {"name": "Baba Is You", "url": "index.html"},
        {"name": "SNK vs. Capcom: The Match of the Millennium", "url": "index.html"},
        {"name": "The Legend of Zelda: Spirit Tracks", "url": "index.html"},
        {"name": "Star Wars Jedi: Fallen Order", "url": "index.html"},
        {"name": "Steamworld Dig 2", "url": "index.html"},
        {"name": "Valkyrie Profile", "url": "index.html"},
        {"name": "Tactics Ogre: Let Us Cling Together", "url": "index.html"},
        {"name": "Batman", "url": "index.html"},
        {"name": "Wizball", "url": "index.html"},
        {"name": "Kid Icarus: Uprising", "url": "index.html"},
        {"name": "International Karate +", "url": "index.html"},
        {"name": "Tearaway", "url": "index.html"},
        {"name": "To The Moon", "url": "index.html"},
        {"name": "Micro Machines", "url": "index.html"},
        {"name": "Tekken 2", "url": "index.html"},
        {"name": "Phoenix Wright: Ace Attorney: Trials & Tribulations", "url": "index.html"},
        {"name": "Gradius V", "url": "index.html"},
        {"name": "Pilotwings 64", "url": "index.html"},
        {"name": "ChuChu Rocket!", "url": "index.html"},
        {"name": "Marathon", "url": "index.html"},
        {"name": "Tetris DS", "url": "index.html"},
        {"name": "Little King's Story", "url": "index.html"},
        {"name": "Defense of the Ancients", "url": "index.html"},
        {"name": "Burnout: Revenge", "url": "index.html"},
        {"name": "ToeJam & Earl", "url": "index.html"},
        {"name": "Half-Minute Hero", "url": "index.html"},
        {"name": "Final Fantasy VII Remake", "url": "index.html"},
        {"name": "Final Fantasy II", "url": "index.html"},
        {"name": "Illusion of Gaia", "url": "index.html"},
        {"name": "Watch Dogs 2", "url": "index.html"},
        {"name": "The Legend of Zelda: Link's Awakening", "url": "index.html"},
        {"name": "Half Life 2: Episode 2", "url": "index.html"},
        {"name": "Ori and the Will of the Wisps", "url": "index.html"},
        {"name": "Gears 5", "url": "index.html"},
        {"name": "Audiosurf", "url": "index.html"},
        {"name": "Star Wars: X-Wing", "url": "index.html"},
        {"name": "Advance Wars 2", "url": "index.html"},
        {"name": "DOOM Eternal", "url": "index.html"},
        {"name": "Candy Crush Saga", "url": "index.html"},
        {"name": "Rez Infinite", "url": "index.html"},
        {"name": "Wii Fit", "url": "index.html"},
        {"name": "FIFA '09", "url": "index.html"},
        {"name": "Max Payne 3", "url": "index.html"},
        {"name": "Harvest Moon", "url": "index.html"},
        {"name": "Desert Strike: Return to the Gulf", "url": "index.html"},
        {"name": "The Binding of Isaac: Rebirth", "url": "index.html"},
        {"name": "Snake", "url": "index.html"},
        {"name": "Bravely Default", "url": "index.html"},
        {"name": "Hyper Light Drifter", "url": "index.html"},
        {"name": "The Need for Speed", "url": "index.html"},
        {"name": "Tom Clancy's Rainbow Six: Vegas", "url": "index.html"},
        {"name": "Salamander", "url": "index.html"},
        {"name": "Zombies Ate My Neighbors", "url": "index.html"},
        {"name": "Sanitarium", "url": "index.html"},
        {"name": "Tenchu: Stealth Assassins", "url": "index.html"},
        {"name": "Snatcher", "url": "index.html"},
        {"name": "Ninja Gaiden II: The Dark Sword of Chaos", "url": "index.html"},
        {"name": "Alex Kidd in Miracle World", "url": "index.html"},
        {"name": "Red Baron", "url": "index.html"},
        {"name": "Breakout", "url": "index.html"},
        {"name": "Monster Hunter 3 Ultimate", "url": "index.html"},
        {"name": "Metro 2033", "url": "index.html"},
        {"name": "Space Channel 5", "url": "index.html"},
        {"name": "Ultima V: Warriors of Destiny", "url": "index.html"},
        {"name": "Warhammer 40,000: Dawn of War II", "url": "index.html"},
        {"name": "Mario Kart: Super Circuit", "url": "index.html"},
        {"name": "Outcast", "url": "index.html"},
        {"name": "Planetside 2", "url": "index.html"},
        {"name": "Star Wars", "url": "index.html"},
        {"name": "DEFCON", "url": "index.html"},
        {"name": "The Talos Principle", "url": "index.html"},
        {"name": "Turok: Dinosaur Hunter", "url": "index.html"},
        {"name": "The Wolf Among Us", "url": "index.html"},
        {"name": "The Witcher", "url": "index.html"},
        {"name": "Myth: The Fallen Lords", "url": "index.html"},
        {"name": "TimeSplitters: Future Perfect", "url": "index.html"},
        {"name": "Axiom Verge", "url": "index.html"},
        {"name": "The Dig", "url": "index.html"},
        {"name": "Danganronpa: Trigger Happy Havoc", "url": "index.html"},
        {"name": "Capcom vs SNK 2 (EO)", "url": "index.html"},
        {"name": "Lunar: The Silver Star", "url": "index.html"},
        {"name": "Panzer General", "url": "index.html"},
        {"name": "Kirby Canvas Curse", "url": "index.html"},
        {"name": "Warframe", "url": "index.html"},
        {"name": "Mario & Luigi: Partners in Time", "url": "index.html"},
        {"name": "Cadence of Hyrule", "url": "index.html"},
        {"name": "Star Wars Episode I: Racer", "url": "index.html"},
        {"name": "Axelay", "url": "index.html"},
        {"name": "Owlboy", "url": "index.html"},
        {"name": "Ghost of Tsushima", "url": "index.html"},
        {"name": "No One Lives Forever 2: A Spy in H.A.R.M.'s Way", "url": "index.html"},
        {"name": "Black", "url": "index.html"},
        {"name": "Track & Field", "url": "index.html"}
    ]
};