const animeData = {
    "anime": [
        {"name": "Solo Leveling Season 2 -Arise from the Shadow-", "url": "https://anilist.co/anime/176496"},
        {"name": "The Apothecary Diaries Season 2", "url": "https://anilist.co/anime/176301"},
        {"name": "Dr. STONE SCIENCE FUTURE", "url": "https://anilist.co/anime/172019"},
        {"name": "Medalist", "url": "https://anilist.co/anime/165171"},
        {"name": "I Left My A-Rank Party to Help My Former Students Reach the Dungeon Depths!", "url": "https://anilist.co/anime/180812"},
        {"name": "I May Be a Guild Receptionist, but I’ll Solo Any Boss to Clock Out on Time", "url": "https://anilist.co/anime/167143"},
        {"name": "Re:ZERO -Starting Life in Another World- Season 3", "url": "https://anilist.co/anime/163134"},
        {"name": "SAKAMOTO DAYS", "url": "https://anilist.co/anime/177709"},
        {"name": "ONE PIECE", "url": "https://anilist.co/anime/21"},
        {"name": "Blue Box", "url": "https://anilist.co/anime/170942"},
        {"name": "One Piece Log: Fish-Man Island Saga", "url": "https://anilist.co/anime/183423"},
        {"name": "Solo Leveling", "url": "https://anilist.co/anime/151807"},
        {"name": "Orb: On the Movements of the Earth", "url": "https://anilist.co/anime/151514"},
        {"name": "I'm the Evil Lord of an Intergalactic Empire!", "url": "https://anilist.co/anime/183274"},
        {"name": "Even Given the Worthless “Appraiser” Class, I’m Actually the Strongest", "url": "https://anilist.co/anime/178548"},
        {"name": "Welcome to Japan, Ms. Elf!", "url": "https://anilist.co/anime/172439"},
        {"name": "Medalist 2nd Season", "url": "https://anilist.co/anime/189275"},
        {"name": "Shangri-La Frontier Season 2", "url": "https://anilist.co/anime/176508"},
        {"name": "Honey Lemon Soda", "url": "https://anilist.co/anime/175443"},
        {"name": "From Bureaucrat to Villainess: Dad's Been Reincarnated!", "url": "https://anilist.co/anime/172453"},
        {"name": "Frieren: Beyond Journey’s End", "url": "https://anilist.co/anime/154587"},
        {"name": "Dr.STONE SCIENCE FUTURE Part 2", "url": "https://anilist.co/anime/189117"},
        {"name": "The Daily Life of a Middle-Aged Online Shopper in Another World", "url": "https://anilist.co/anime/180292"},
        {"name": "Bleach", "url": "https://anilist.co/anime/269"},
        {"name": "Übel Blatt", "url": "https://anilist.co/anime/175198"},
        {"name": "DAN DA DAN", "url": "https://anilist.co/anime/171018"},
        {"name": "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You Season 2", "url": "https://anilist.co/anime/172258"},
        {"name": "I'm Getting Married to a Girl I Hate in My Class", "url": "https://anilist.co/anime/178462"},
        {"name": "ZENSHU", "url": "https://anilist.co/anime/176273"},
        {"name": "The Apothecary Diaries", "url": "https://anilist.co/anime/161645"},
        {"name": "You and Idol Precure ♪", "url": "https://anilist.co/anime/185073"},
        {"name": "Lazarus", "url": "https://anilist.co/anime/167336"},
        {"name": "Hunter x Hunter (2011)", "url": "https://anilist.co/anime/11061"},
        {"name": "Headhunted to Another World: From Salaryman to Big Four!", "url": "https://anilist.co/anime/179689"},
        {"name": "Ameku M.D.: Doctor Detective", "url": "https://anilist.co/anime/176642"},
        {"name": "Blue Miburo", "url": "https://anilist.co/anime/169258"},
        {"name": "Black Clover", "url": "https://anilist.co/anime/97940"},
        {"name": "Magic Maker: How to Make Magic in Another World", "url": "https://anilist.co/anime/179297"},
        {"name": "Ave Mujica - The Die is Cast -", "url": "https://anilist.co/anime/169295"},
        {"name": "Fire Force", "url": "https://anilist.co/anime/105310"},
        {"name": "Possibly the Greatest Alchemist of All Time", "url": "https://anilist.co/anime/177506"},
        {"name": "Tying the Knot with an Amagami Sister", "url": "https://anilist.co/anime/164172"},
        {"name": "Medaka Kuroiwa is Impervious to My Charms", "url": "https://anilist.co/anime/177552"},
        {"name": "Ao no Hako 2nd Season", "url": "https://anilist.co/anime/189123"},
        {"name": "I Have a Crush at Work", "url": "https://anilist.co/anime/179696"},
        {"name": "JUJUTSU KAISEN", "url": "https://anilist.co/anime/113415"},
        {"name": "Naruto", "url": "https://anilist.co/anime/20"},
        {"name": "Re:Zero kara Hajimeru Isekai Seikatsu 4th Season", "url": "https://anilist.co/anime/189046"},
        {"name": "Is It Wrong To Try To Pick Up Girls in a Dungeon? V", "url": "https://anilist.co/anime/170732"},
        {"name": "JUJUTSU KAISEN Season 2", "url": "https://anilist.co/anime/145064"},
        {"name": "Fire Force Season 2", "url": "https://anilist.co/anime/114236"},
        {"name": "Re:ZERO -Starting Life in Another World-", "url": "https://anilist.co/anime/21355"},
        {"name": "Naruto: Shippuden", "url": "https://anilist.co/anime/1735"},
        {"name": "Gintama", "url": "https://anilist.co/anime/918"},
        {"name": "My Hero Academia: Vigilantes", "url": "https://anilist.co/anime/185736"},
        {"name": "Babanba Banban Vampire", "url": "https://anilist.co/anime/175422"},
        {"name": "Super Cube", "url": "https://anilist.co/anime/166442"},
        {"name": "Chainsaw Man", "url": "https://anilist.co/anime/127230"},
        {"name": "Death Note", "url": "https://anilist.co/anime/1535"},
        {"name": "Blue Exorcist -The Blue Night Saga-", "url": "https://anilist.co/anime/185880"},
        {"name": "WIND BREAKER Season 2", "url": "https://anilist.co/anime/178680"},
        {"name": "ISHURA Season 2", "url": "https://anilist.co/anime/176234"},
        {"name": "WIND BREAKER", "url": "https://anilist.co/anime/163270"},
        {"name": "Dr. STONE", "url": "https://anilist.co/anime/105333"},
        {"name": "Sword Art Online", "url": "https://anilist.co/anime/11757"},
        {"name": "The Beginning After the End", "url": "https://anilist.co/anime/183161"},
        {"name": "WITCH WATCH", "url": "https://anilist.co/anime/180367"},
        {"name": "Witchy Precure!! ~MIRAI DAYS~", "url": "https://anilist.co/anime/162722"},
        {"name": "Sono Bisque Doll wa Koi wo Suru Season 2", "url": "https://anilist.co/anime/154768"},
        {"name": "Kaiju No.8", "url": "https://anilist.co/anime/153288"},
        {"name": "Shangri-La Frontier", "url": "https://anilist.co/anime/151970"},
        {"name": "Fullmetal Alchemist: Brotherhood", "url": "https://anilist.co/anime/5114"},
        {"name": "Neon Genesis Evangelion", "url": "https://anilist.co/anime/30"},
        {"name": "DAN DA DAN Season 2", "url": "https://anilist.co/anime/185660"},
        {"name": "Kaiju No. 8 Season 2", "url": "https://anilist.co/anime/178754"},
        {"name": "Bogus Skill <<Fruitmaster>> ~About that time I became able to eat unlimited numbers of Skill Fruits (that kill you)~", "url": "https://anilist.co/anime/178100"},
        {"name": "Chainsaw Man – The Movie: Reze Arc", "url": "https://anilist.co/anime/171627"},
        {"name": "Delicious in Dungeon", "url": "https://anilist.co/anime/153518"},
        {"name": "Fire Force Season 3", "url": "https://anilist.co/anime/149118"},
        {"name": "Sword of the Demon Hunter: Kijin Gentosho", "url": "https://anilist.co/anime/143598"},
        {"name": "ERASED", "url": "https://anilist.co/anime/21234"},
        {"name": "Angel Beats!", "url": "https://anilist.co/anime/6547"},
        {"name": "Azumanga Daioh", "url": "https://anilist.co/anime/66"},
        {"name": "From Old Country Bumpkin to Master Swordsman", "url": "https://anilist.co/anime/179955"},
        {"name": "Flower and Asura", "url": "https://anilist.co/anime/178022"},
        {"name": "The Brilliant Healer's New Life in the Shadows", "url": "https://anilist.co/anime/175872"},
        {"name": "Dragon Ball DAIMA", "url": "https://anilist.co/anime/170083"},
        {"name": "Tower of God Season 2", "url": "https://anilist.co/anime/153406"},
        {"name": "Demon Slayer: Kimetsu no Yaiba", "url": "https://anilist.co/anime/101922"},
        {"name": "Rascal Does Not Dream of Bunny Girl Senpai", "url": "https://anilist.co/anime/101291"},
        {"name": "Soul Eater", "url": "https://anilist.co/anime/3588"},
        {"name": "Gurren Lagann", "url": "https://anilist.co/anime/2001"},
        {"name": "Yu Yu Hakusho: Ghostfiles", "url": "https://anilist.co/anime/392"},
        {"name": "Solo Leveling -ReAwakening-", "url": "https://anilist.co/anime/184694"},
        {"name": "Kaoru Hana wa Rin to Saku", "url": "https://anilist.co/anime/181444"},
        {"name": "The Red Ranger Becomes an Adventurer in Another World", "url": "https://anilist.co/anime/180052"},
        {"name": "Farmagia", "url": "https://anilist.co/anime/178312"},
        {"name": "Anyway, I'm Falling in Love with You.", "url": "https://anilist.co/anime/175409"},
        {"name": "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2", "url": "https://anilist.co/anime/166873"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc", "url": "https://anilist.co/anime/166240"},
        {"name": "BLUE LOCK Season 2", "url": "https://anilist.co/anime/163146"},
        {"name": "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You", "url": "https://anilist.co/anime/162694"},
        {"name": "Dr. STONE New World Part 2", "url": "https://anilist.co/anime/162670"},
        {"name": "Arifureta: From Commonplace to World's Strongest Season 3", "url": "https://anilist.co/anime/154473"},
        {"name": "Horimiya", "url": "https://anilist.co/anime/124080"},
        {"name": "Tokyo Revengers", "url": "https://anilist.co/anime/120120"},
        {"name": "Re:ZERO -Starting Life in Another World- Season 2", "url": "https://anilist.co/anime/108632"},
        {"name": "I’m a Noble on the Brink of Ruin, So I Might as Well Try Mastering Magic", "url": "https://anilist.co/anime/176063"},
        {"name": "I'm Living With a Otaku NEET Kunoichi?!", "url": "https://anilist.co/anime/174654"},
        {"name": "Toilet-bound Hanako-kun Season 2", "url": "https://anilist.co/anime/170892"},
        {"name": "TRILLION GAME", "url": "https://anilist.co/anime/169315"},
        {"name": "OKITSURA: Fell in Love with an Okinawan Girl, but I Just Wish I Know What She's Saying", "url": "https://anilist.co/anime/166699"},
        {"name": "Spice and Wolf: MERCHANT MEETS THE WISE WOLF", "url": "https://anilist.co/anime/145728"},
        {"name": "My Dress-Up Darling", "url": "https://anilist.co/anime/132405"},
        {"name": "BOCCHI THE ROCK!", "url": "https://anilist.co/anime/130003"},
        {"name": "Vinland Saga", "url": "https://anilist.co/anime/101348"},
        {"name": "Tokyo Ghoul", "url": "https://anilist.co/anime/20605"},
        {"name": "Attack on Titan", "url": "https://anilist.co/anime/16498"},
        {"name": "JoJo's Bizarre Adventure (TV)", "url": "https://anilist.co/anime/14719"},
        {"name": "Princess Mononoke", "url": "https://anilist.co/anime/164"},
        {"name": "SAKAMOTO DAYS Part 2", "url": "https://anilist.co/anime/184237"},
        {"name": "Please Put Them On, Takamine-san", "url": "https://anilist.co/anime/179965"},
        {"name": "Lycoris Recoil: Friends are thieves of time.", "url": "https://anilist.co/anime/179706"},
        {"name": "Gachiakuta", "url": "https://anilist.co/anime/178025"},
        {"name": "Girls Band Cry", "url": "https://anilist.co/anime/164212"},
        {"name": "To Be Hero X", "url": "https://anilist.co/anime/156092"},
        {"name": "Tengoku Daimakyo", "url": "https://anilist.co/anime/155783"},
        {"name": "Can a Boy-Girl Friendship Survive?", "url": "https://anilist.co/anime/153554"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", "url": "https://anilist.co/anime/145139"},
        {"name": "KONOSUBA -God's blessing on this wonderful world! 3", "url": "https://anilist.co/anime/136804"},
        {"name": "Hell’s Paradise", "url": "https://anilist.co/anime/128893"},
        {"name": "Link Click", "url": "https://anilist.co/anime/126403"},
        {"name": "That Time I Got Reincarnated as a Slime", "url": "https://anilist.co/anime/101280"},
        {"name": "My Hero Academia", "url": "https://anilist.co/anime/21459"},
        {"name": "One-Punch Man", "url": "https://anilist.co/anime/21087"},
        {"name": "Assassination Classroom", "url": "https://anilist.co/anime/20755"},
        {"name": "Terror in Resonance", "url": "https://anilist.co/anime/20661"},
        {"name": "HAIKYU!!", "url": "https://anilist.co/anime/20464"},
        {"name": "Kuroko's Basketball", "url": "https://anilist.co/anime/11771"},
        {"name": "Blue Exorcist", "url": "https://anilist.co/anime/9919"},
        {"name": "Dragon Ball Z", "url": "https://anilist.co/anime/813"},
        {"name": "Monster", "url": "https://anilist.co/anime/19"},
        {"name": "BanG Dream! It's MyGO!!!!! / Ave Mujica (Zoku-hen)", "url": "https://anilist.co/anime/189121"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Infinity Castle", "url": "https://anilist.co/anime/178788"},
        {"name": "The Summer Hikaru Died", "url": "https://anilist.co/anime/177689"},
        {"name": "Momentary Lily", "url": "https://anilist.co/anime/177159"},
        {"name": "mono", "url": "https://anilist.co/anime/176246"},
        {"name": "My Deer Friend Nokotan", "url": "https://anilist.co/anime/175977"},
        {"name": "You are Ms. Servant", "url": "https://anilist.co/anime/172190"},
        {"name": "Rascal Does Not Dream of Santa Claus", "url": "https://anilist.co/anime/171046"},
        {"name": "Oshi no Ko Season 2", "url": "https://anilist.co/anime/166531"},
        {"name": "DEMON LORD 2099", "url": "https://anilist.co/anime/163135"},
        {"name": "Mushoku Tensei: Jobless Reincarnation Season 2", "url": "https://anilist.co/anime/146065"},
        {"name": "BLUE LOCK", "url": "https://anilist.co/anime/137822"},
        {"name": "Vinland Saga Season 2", "url": "https://anilist.co/anime/136430"},
        {"name": "The Eminence in Shadow", "url": "https://anilist.co/anime/130298"},
        {"name": "Summer Time Rendering", "url": "https://anilist.co/anime/129201"},
        {"name": "Re:ZERO -Starting Life in Another World- Season 2 Part 2", "url": "https://anilist.co/anime/119661"},
        {"name": "Death Parade", "url": "https://anilist.co/anime/20931"},
        {"name": "Parasyte -the maxim-", "url": "https://anilist.co/anime/20623"},
        {"name": "Kill la Kill", "url": "https://anilist.co/anime/18679"},
        {"name": "Steins;Gate", "url": "https://anilist.co/anime/9253"},
        {"name": "Fairy Tail", "url": "https://anilist.co/anime/6702"},
        {"name": "Howl‘s Moving Castle", "url": "https://anilist.co/anime/431"},
        {"name": "Mobile Suit Gundam", "url": "https://anilist.co/anime/80"},
        {"name": "Cowboy Bebop", "url": "https://anilist.co/anime/1"},
        {"name": "There's No Freaking Way I'll Be Your Lover! Unless...", "url": "https://anilist.co/anime/184591"},
        {"name": "Kowloon Generic Romance", "url": "https://anilist.co/anime/182814"},
        {"name": "KONOSUBA -God's Blessing on This Wonderful World! 3 -BONUS STAGE-", "url": "https://anilist.co/anime/181244"},
        {"name": "Rock is a Lady’s Modesty", "url": "https://anilist.co/anime/179694"},
        {"name": "Let This Grieving Soul Retire", "url": "https://anilist.co/anime/175019"},
        {"name": "The Shiunji Family Children", "url": "https://anilist.co/anime/174802"},
        {"name": "LOOK BACK", "url": "https://anilist.co/anime/174788"},
        {"name": "Loner Life in Another World", "url": "https://anilist.co/anime/173693"},
        {"name": "Touhai: Ura Rate Mahjong Touhai Roku", "url": "https://anilist.co/anime/173263"},
        {"name": "Link Click: Bridon Arc", "url": "https://anilist.co/anime/170166"},
        {"name": "My Happy Marriage Season 2", "url": "https://anilist.co/anime/169441"},
        {"name": "My Hero Academia Season 7", "url": "https://anilist.co/anime/163139"},
        {"name": "The Eminence in Shadow Season 2", "url": "https://anilist.co/anime/161964"},
        {"name": "Pokémon Horizons: The Series", "url": "https://anilist.co/anime/158871"},
        {"name": "2.5 Dimensional Seduction", "url": "https://anilist.co/anime/158559"},
        {"name": "That Time I Got Reincarnated as a Slime Season 3", "url": "https://anilist.co/anime/156822"},
        {"name": "Romantic Killer", "url": "https://anilist.co/anime/153930"},
        {"name": "Ragna Crimson", "url": "https://anilist.co/anime/146493"},
        {"name": "Summer Pockets", "url": "https://anilist.co/anime/143200"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", "url": "https://anilist.co/anime/142329"},
        {"name": "Attack on Titan Final Season Part 2", "url": "https://anilist.co/anime/131681"},
        {"name": "Shikimori's Not Just a Cutie", "url": "https://anilist.co/anime/127911"},
        {"name": "86 EIGHTY-SIX", "url": "https://anilist.co/anime/116589"},
        {"name": "Attack on Titan Final Season", "url": "https://anilist.co/anime/110277"},
        {"name": "Kaguya-sama: Love is War", "url": "https://anilist.co/anime/101921"},
        {"name": "Wotakoi: Love is Hard for Otaku", "url": "https://anilist.co/anime/99578"},
        {"name": "Devilman Crybaby", "url": "https://anilist.co/anime/98460"},
        {"name": "Made in Abyss", "url": "https://anilist.co/anime/97986"},
        {"name": "Mob Psycho 100", "url": "https://anilist.co/anime/21507"},
        {"name": "Steins;Gate 0", "url": "https://anilist.co/anime/21127"},
        {"name": "Charlotte", "url": "https://anilist.co/anime/20997"},
        {"name": "HAIKYU!! 2nd Season", "url": "https://anilist.co/anime/20992"},
        {"name": "A Silent Voice", "url": "https://anilist.co/anime/20954"},
        {"name": "The Seven Deadly Sins", "url": "https://anilist.co/anime/20789"},
        {"name": "The Irregular at Magic High School", "url": "https://anilist.co/anime/20458"},
        {"name": "Date A Live", "url": "https://anilist.co/anime/15583"},
        {"name": "PSYCHO-PASS", "url": "https://anilist.co/anime/13601"},
        {"name": "The Future Diary", "url": "https://anilist.co/anime/10620"},
        {"name": "Kimi ni Todoke: From Me to You", "url": "https://anilist.co/anime/6045"},
        {"name": "Toradora!", "url": "https://anilist.co/anime/4224"},
        {"name": "Code Geass: Lelouch of the Rebellion", "url": "https://anilist.co/anime/1575"},
        {"name": "Dragon Ball", "url": "https://anilist.co/anime/223"},
        {"name": "Mobile Suit Gundam GQuuuuuuX", "url": "https://anilist.co/anime/185213"},
        {"name": "The Unaware Atelier Meister", "url": "https://anilist.co/anime/183133"},
        {"name": "May I Ask for One Final Thing?", "url": "https://anilist.co/anime/181447"},
        {"name": "Yandere Dark Elf: She Chased Me All the Way From Another World!", "url": "https://anilist.co/anime/180829"},
        {"name": "Apocalypse Hotel", "url": "https://anilist.co/anime/180675"},
        {"name": "Silent Witch: Chinmoku no Majo no Kakushigoto", "url": "https://anilist.co/anime/179966"},
        {"name": "Sentai Daishikkaku 2nd Season", "url": "https://anilist.co/anime/178781"},
        {"name": "Unnamed Memory Season 2", "url": "https://anilist.co/anime/178550"},
        {"name": "Isekai Mokushiroku Mynoghra: Hametsu no Bunmei de Hajimeru Sekai Seifuku", "url": "https://anilist.co/anime/178433"},
        {"name": "Makina-san's a Love Bot?!", "url": "https://anilist.co/anime/177509"},
        {"name": "The Rising of the Shield Hero Season 4", "url": "https://anilist.co/anime/173780"},
        {"name": "The Strongest Magician in the Demon Lord's Army was a Human", "url": "https://anilist.co/anime/173584"},
        {"name": "Your Forma", "url": "https://anilist.co/anime/167142"},
        {"name": "A Sign of Affection", "url": "https://anilist.co/anime/166794"},
        {"name": "Pseudo Harem", "url": "https://anilist.co/anime/163623"},
        {"name": "Alya Sometimes Hides Her Feelings in Russian", "url": "https://anilist.co/anime/162804"},
        {"name": "The Dangers in My Heart", "url": "https://anilist.co/anime/153152"},
        {"name": "Dark Gathering", "url": "https://anilist.co/anime/152802"},
        {"name": "Moonrise", "url": "https://anilist.co/anime/150654"},
        {"name": "I've Been Killing Slimes For 300 Years And Maxed Out My Level Season 2", "url": "https://anilist.co/anime/143337"},
        {"name": "Chiikawa", "url": "https://anilist.co/anime/140842"},
        {"name": "Cyberpunk: Edgerunners", "url": "https://anilist.co/anime/120377"},
        {"name": "BEASTARS Season 2", "url": "https://anilist.co/anime/114194"},
        {"name": "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train", "url": "https://anilist.co/anime/112151"},
        {"name": "Mushoku Tensei: Jobless Reincarnation", "url": "https://anilist.co/anime/108465"},
        {"name": "Attack on Titan Season 3 Part 2", "url": "https://anilist.co/anime/104578"},
        {"name": "The Promised Neverland", "url": "https://anilist.co/anime/101759"},
        {"name": "I Want to Eat Your Pancreas", "url": "https://anilist.co/anime/99750"},
        {"name": "The Rising of the Shield Hero", "url": "https://anilist.co/anime/99263"},
        {"name": "Boruto: Naruto Next Generations", "url": "https://anilist.co/anime/97938"},
        {"name": "One-Punch Man Season 2", "url": "https://anilist.co/anime/97668"},
        {"name": "KONOSUBA -God's blessing on this wonderful world! 2", "url": "https://anilist.co/anime/21699"},
        {"name": "Plastic Memories", "url": "https://anilist.co/anime/20872"},
        {"name": "Blood Blockade Battlefront", "url": "https://anilist.co/anime/20727"},
        {"name": "Clannad: After Story", "url": "https://anilist.co/anime/4181"},
        {"name": "Pokémon", "url": "https://anilist.co/anime/527"},
        {"name": "Serial Experiments Lain", "url": "https://anilist.co/anime/339"},
        {"name": "Case Closed", "url": "https://anilist.co/anime/235"},
        {"name": "Cardcaptor Sakura", "url": "https://anilist.co/anime/232"},
        {"name": "NEET Kunoichi to Naze ka Dousei Hajimemashita OVAs", "url": "https://anilist.co/anime/185992"},
        {"name": "My Hero Academia FINAL SEASON", "url": "https://anilist.co/anime/182896"},
        {"name": "Sousou no Frieren 2nd Season", "url": "https://anilist.co/anime/182255"},
        {"name": "Uma Musume: Cinderella Gray", "url": "https://anilist.co/anime/180516"},
        {"name": "Aharen-san wa Hakarenai Season 2", "url": "https://anilist.co/anime/179979"},
        {"name": "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World Season 2", "url": "https://anilist.co/anime/178434"},
        {"name": "Beheneko: The Elf-Girl's Cat is Secretly an S-Ranked Monster!", "url": "https://anilist.co/anime/176158"},
        {"name": "Yofukashi no Uta Season 2", "url": "https://anilist.co/anime/175914"},
        {"name": "Sorairo Utility (TV)", "url": "https://anilist.co/anime/174596"},
        {"name": "Wistoria: Wand and Sword", "url": "https://anilist.co/anime/174576"},
        {"name": "Failure Frame: I Became the Strongest and Annihilated Everything with Low-Level Spells", "url": "https://anilist.co/anime/173694"},
        {"name": "SHOSHIMIN: How to Become Ordinary", "url": "https://anilist.co/anime/173295"},
        {"name": "Makeine: Too Many Losing Heroines!", "url": "https://anilist.co/anime/171457"},
        {"name": "I Parry Everything", "url": "https://anilist.co/anime/170695"},
        {"name": "BLEACH: Thousand-Year Blood War - The Conflict", "url": "https://anilist.co/anime/169755"},
        {"name": "Bungo Stray Dogs 5", "url": "https://anilist.co/anime/163263"},
        {"name": "Senpai is an Otokonoko", "url": "https://anilist.co/anime/163133"},
        {"name": "The Elusive Samurai", "url": "https://anilist.co/anime/162896"},
        {"name": "Attack on Titan Final Season THE FINAL CHAPTERS Special 2", "url": "https://anilist.co/anime/162314"},
        {"name": "ISHURA", "url": "https://anilist.co/anime/161476"},
        {"name": "I Was Reincarnated as the 7th Prince So I Can Take My Time Perfecting My Magical Ability", "url": "https://anilist.co/anime/156415"},
        {"name": "Undead Unluck", "url": "https://anilist.co/anime/154116"},
        {"name": "Days with My Stepsister", "url": "https://anilist.co/anime/152681"},
        {"name": "MASHLE: MAGIC AND MUSCLES", "url": "https://anilist.co/anime/151801"},
        {"name": "Ninja Kamui", "url": "https://anilist.co/anime/151639"},
        {"name": "KONOSUBA -An Explosion on This Wonderful World!", "url": "https://anilist.co/anime/150075"},
        {"name": "Farming Life in Another World", "url": "https://anilist.co/anime/146850"},
        {"name": "Call of the Night", "url": "https://anilist.co/anime/141391"},
        {"name": "Aharen-san wa Hakarenai", "url": "https://anilist.co/anime/137281"},
        {"name": "OVERLORD: The Sacred Kingdom", "url": "https://anilist.co/anime/133845"},
        {"name": "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc", "url": "https://anilist.co/anime/129874"},
        {"name": "Vivy -Fluorite Eye's Song-", "url": "https://anilist.co/anime/128546"},
        {"name": "Banished from the Hero’s Party, I Decided to Live a Quiet Life in the Countryside", "url": "https://anilist.co/anime/126213"},
        {"name": "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense. Season 2", "url": "https://anilist.co/anime/116867"},
        {"name": "Josee, the Tiger and the Fish", "url": "https://anilist.co/anime/113596"},
        {"name": "I've Been Killing Slimes for 300 Years and Maxed Out My Level", "url": "https://anilist.co/anime/112608"},
        {"name": "The Rising of the Shield Hero Season 3", "url": "https://anilist.co/anime/111322"},
        {"name": "The Rising of the Shield Hero Season 2", "url": "https://anilist.co/anime/111321"},
        {"name": "ID: INVADED", "url": "https://anilist.co/anime/110350"},
        {"name": "That Time I Got Reincarnated as a Slime Season 2", "url": "https://anilist.co/anime/108511"},
        {"name": "Dororo", "url": "https://anilist.co/anime/101347"},
        {"name": "Umamusume: Pretty Derby", "url": "https://anilist.co/anime/98514"},
        {"name": "Tsukigakirei", "url": "https://anilist.co/anime/98202"},
        {"name": "My Hero Academia Season 2", "url": "https://anilist.co/anime/21856"},
        {"name": "Your Name.", "url": "https://anilist.co/anime/21519"},
        {"name": "JoJo's Bizarre Adventure: Diamond is Unbreakable", "url": "https://anilist.co/anime/21450"},
        {"name": "Grimgar of Fantasy and Ash", "url": "https://anilist.co/anime/21428"},
        {"name": "Kiznaiver", "url": "https://anilist.co/anime/21421"},
        {"name": "KONOSUBA -God's blessing on this wonderful world!", "url": "https://anilist.co/anime/21202"},
        {"name": "Assassination Classroom 2", "url": "https://anilist.co/anime/21170"},
        {"name": "Attack on Titan Season 2", "url": "https://anilist.co/anime/20958"},
        {"name": "Food Wars!", "url": "https://anilist.co/anime/20923"},
        {"name": "Overlord", "url": "https://anilist.co/anime/20832"},
        {"name": "Seraph of the End: Vampire Reign", "url": "https://anilist.co/anime/20829"},
        {"name": "Yona of the Dawn", "url": "https://anilist.co/anime/20770"},
        {"name": "Your lie in April", "url": "https://anilist.co/anime/20665"},
        {"name": "World Break: Aria of Curse for a Holy Swordsman", "url": "https://anilist.co/anime/20627"},
        {"name": "Blue Spring Ride", "url": "https://anilist.co/anime/20596"},
        {"name": "Noragami", "url": "https://anilist.co/anime/20447"},
        {"name": "Fate/stay night: Unlimited Blade Works", "url": "https://anilist.co/anime/19603"},
        {"name": "Log Horizon", "url": "https://anilist.co/anime/17265"},
        {"name": "Magi: The Labyrinth of Magic", "url": "https://anilist.co/anime/14513"},
        {"name": "Fate/Zero", "url": "https://anilist.co/anime/10087"},
        {"name": "Puella Magi Madoka Magica", "url": "https://anilist.co/anime/9756"},
        {"name": "Deadman Wonderland", "url": "https://anilist.co/anime/6880"},
        {"name": "NANA", "url": "https://anilist.co/anime/877"},
        {"name": "Macross Plus", "url": "https://anilist.co/anime/474"},
        {"name": "Ao no Miburo: Serizawa Ansatsu-hen", "url": "https://anilist.co/anime/189258"},
        {"name": "Ki ni Natteru Hito ga Otoko Janakatta", "url": "https://anilist.co/anime/186822"},
        {"name": "Food for the Soul", "url": "https://anilist.co/anime/185939"},
        {"name": "Anne Shirley", "url": "https://anilist.co/anime/184639"},
        {"name": "The Too-Perfect Saint: Tossed Aside by My Fiancé and Sold to Another Kingdom", "url": "https://anilist.co/anime/183275"},
        {"name": "CARDFIGHT!! VANGUARD Divinez DELUXE Arc", "url": "https://anilist.co/anime/182920"},
        {"name": "Grand Blue Season 2", "url": "https://anilist.co/anime/182309"},
        {"name": "Mikadono Sanshimai wa Angai, Choroi.", "url": "https://anilist.co/anime/178886"},
        {"name": "Once Upon a Witch's Death", "url": "https://anilist.co/anime/178701"},
        {"name": "Ranma1/2 (2024)", "url": "https://anilist.co/anime/178533"},
        {"name": "SPY×FAMILY Season 3", "url": "https://anilist.co/anime/177937"},
        {"name": "Rurouni Kenshin -Kyoto Disturbance-", "url": "https://anilist.co/anime/171637"},
        {"name": "The Magical Girl and the Evil Lieutenant Used to Be Archenemies", "url": "https://anilist.co/anime/170938"},
        {"name": "Watari-kun no xx ga Houkai Sunzen", "url": "https://anilist.co/anime/169420"},
        {"name": "7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!", "url": "https://anilist.co/anime/168374"},
        {"name": "Dou Po Cangqiong: Nian Fan 3", "url": "https://anilist.co/anime/168164"},
        {"name": "Why Does Nobody Remember Me in This World?", "url": "https://anilist.co/anime/167419"},
        {"name": "BanG Dream! It's MyGO!!!!!", "url": "https://anilist.co/anime/163571"},
        {"name": "Horimiya: The Missing Pieces", "url": "https://anilist.co/anime/163132"},
        {"name": "Quality Assurance in Another World", "url": "https://anilist.co/anime/163077"},
        {"name": "Mission: Yozakura Family", "url": "https://anilist.co/anime/158898"},
        {"name": "Dead Mount Death Play", "url": "https://anilist.co/anime/157198"},
        {"name": "An Archdemon's Dilemma: How to Love Your Elf Bride", "url": "https://anilist.co/anime/156023"},
        {"name": "Buddy Daddies", "url": "https://anilist.co/anime/155907"},
        {"name": "My Love Story with Yamada-kun at Lv999", "url": "https://anilist.co/anime/154965"},
        {"name": "Our Dating Story: The Experienced You and The Inexperienced Me", "url": "https://anilist.co/anime/154459"},
        {"name": "No Longer Allowed in Another World", "url": "https://anilist.co/anime/152137"},
        {"name": "Date A Live V", "url": "https://anilist.co/anime/151380"},
        {"name": "TRIGUN STAMPEDE", "url": "https://anilist.co/anime/151040"},
        {"name": "Oshi No Ko", "url": "https://anilist.co/anime/150672"},
        {"name": "Classroom of the Elite Season 3", "url": "https://anilist.co/anime/146066"},
        {"name": "I've Somehow Gotten Stronger When I Improved My Farm-Related Skills", "url": "https://anilist.co/anime/145815"},
        {"name": "Classroom of the Elite Season 2", "url": "https://anilist.co/anime/145545"},
        {"name": "The Angel Next Door Spoils Me Rotten", "url": "https://anilist.co/anime/143338"},
        {"name": "Tokyo Revengers Season 2", "url": "https://anilist.co/anime/142853"},
        {"name": "Suzume", "url": "https://anilist.co/anime/142770"},
        {"name": "More than a Married Couple, but Not Lovers.", "url": "https://anilist.co/anime/141949"},
        {"name": "Skip and Loafer", "url": "https://anilist.co/anime/141911"},
        {"name": "Mobile Suit Gundam: The Witch from Mercury", "url": "https://anilist.co/anime/139274"},
        {"name": "FAIRY TAIL 100 YEARS QUEST", "url": "https://anilist.co/anime/139095"},
        {"name": "Soul Land 2: The Peerless Tang Clan", "url": "https://anilist.co/anime/137683"},
        {"name": "Renegade Immortal", "url": "https://anilist.co/anime/137653"},
        {"name": "BEASTARS Final Season Part 1", "url": "https://anilist.co/anime/136880"},
        {"name": "Overlord IV", "url": "https://anilist.co/anime/133844"},
        {"name": "The Case Study of Vanitas", "url": "https://anilist.co/anime/131646"},
        {"name": "86 EIGHTY-SIX Part 2", "url": "https://anilist.co/anime/131586"},
        {"name": "takt op.Destiny", "url": "https://anilist.co/anime/131565"},
        {"name": "Dr. STONE New World", "url": "https://anilist.co/anime/131518"},
        {"name": "Is It Wrong to Try to Pick Up Girls in a Dungeon? IV", "url": "https://anilist.co/anime/129196"},
        {"name": "The Genius Prince's Guide to Raising a Nation Out of Debt", "url": "https://anilist.co/anime/129190"},
        {"name": "GOBLIN SLAYER II", "url": "https://anilist.co/anime/129188"},
        {"name": "Blue Period", "url": "https://anilist.co/anime/128705"},
        {"name": "Mushoku Tensei: Jobless Reincarnation Cour 2", "url": "https://anilist.co/anime/127720"},
        {"name": "WONDER EGG PRIORITY", "url": "https://anilist.co/anime/124845"},
        {"name": "How a Realist Hero Rebuilt the Kingdom", "url": "https://anilist.co/anime/117612"},
        {"name": "My Hero Academia Season 5", "url": "https://anilist.co/anime/117193"},
        {"name": "That Time I Got Reincarnated as a Slime Season 2 Part 2", "url": "https://anilist.co/anime/116742"},
        {"name": "Akudama Drive", "url": "https://anilist.co/anime/116566"},
        {"name": "The God of High School", "url": "https://anilist.co/anime/116006"},
        {"name": "By the Grace of the Gods", "url": "https://anilist.co/anime/115740"},
        {"name": "Tower of God", "url": "https://anilist.co/anime/115230"},
        {"name": "Uzaki-chan Wants to Hang Out!", "url": "https://anilist.co/anime/115113"},
        {"name": "Made in Abyss: The Golden City of the Scorching Sun", "url": "https://anilist.co/anime/114745"},
        {"name": "To Your Eternity", "url": "https://anilist.co/anime/114535"},
        {"name": "Dr. STONE: STONE WARS", "url": "https://anilist.co/anime/113936"},
        {"name": "Ranking of Kings", "url": "https://anilist.co/anime/113717"},
        {"name": "Arifureta: From Commonplace to World's Strongest Season 2", "url": "https://anilist.co/anime/112323"},
        {"name": "The Quintessential Quintuplets 2", "url": "https://anilist.co/anime/109261"},
        {"name": "Toilet-bound Hanako-kun", "url": "https://anilist.co/anime/108463"},
        {"name": "BEASTARS", "url": "https://anilist.co/anime/107660"},
        {"name": "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense.", "url": "https://anilist.co/anime/106479"},
        {"name": "Dorohedoro", "url": "https://anilist.co/anime/105228"},
        {"name": "My Hero Academia Season 4", "url": "https://anilist.co/anime/104276"},
        {"name": "Domestic Girlfriend", "url": "https://anilist.co/anime/103139"},
        {"name": "JoJo's Bizarre Adventure: Golden Wind", "url": "https://anilist.co/anime/102883"},
        {"name": "Overlord III", "url": "https://anilist.co/anime/101474"},
        {"name": "Plunderer", "url": "https://anilist.co/anime/101168"},
        {"name": "Date A Live III", "url": "https://anilist.co/anime/100722"},
        {"name": "Arifureta: From Commonplace to World's Strongest", "url": "https://anilist.co/anime/100668"},
        {"name": "My Hero Academia Season 3", "url": "https://anilist.co/anime/100166"},
        {"name": "Attack on Titan Season 3", "url": "https://anilist.co/anime/99147"},
        {"name": "The Ancient Magus' Bride", "url": "https://anilist.co/anime/98436"},
        {"name": "Kakegurui", "url": "https://anilist.co/anime/98314"},
        {"name": "Violet Evergarden", "url": "https://anilist.co/anime/21827"},
        {"name": "The Disastrous Life of Saiki K.", "url": "https://anilist.co/anime/21804"},
        {"name": "Eromanga Sensei", "url": "https://anilist.co/anime/21685"},
        {"name": "Saga of Tanya the Evil", "url": "https://anilist.co/anime/21613"},
        {"name": "Prison School", "url": "https://anilist.co/anime/20807"},
        {"name": "Fairy Tail Series 2", "url": "https://anilist.co/anime/20626"},
        {"name": "Akame ga Kill!", "url": "https://anilist.co/anime/20613"},
        {"name": "No Game, No Life", "url": "https://anilist.co/anime/19815"},
        {"name": "Ace of the Diamond", "url": "https://anilist.co/anime/18689"},
        {"name": "Golden Time", "url": "https://anilist.co/anime/17895"},
        {"name": "My Teen Romantic Comedy SNAFU", "url": "https://anilist.co/anime/14813"},
        {"name": "Blast of Tempest", "url": "https://anilist.co/anime/14075"},
        {"name": "Sankarea: Undying Love", "url": "https://anilist.co/anime/11499"},
        {"name": "Another", "url": "https://anilist.co/anime/11111"},
        {"name": "Chihayafuru", "url": "https://anilist.co/anime/10800"},
        {"name": "Guilty Crown", "url": "https://anilist.co/anime/10793"},
        {"name": "Nichijou - My Ordinary Life", "url": "https://anilist.co/anime/10165"},
        {"name": "Toaru Kagaku no Railgun: Misaka-san wa Ima Chuumoku no Mato Desukara", "url": "https://anilist.co/anime/9047"},
        {"name": "Amagami SS", "url": "https://anilist.co/anime/8676"},
        {"name": "Shiki", "url": "https://anilist.co/anime/7724"},
        {"name": "A Certain Magical Index", "url": "https://anilist.co/anime/4654"},
        {"name": "Spice and Wolf", "url": "https://anilist.co/anime/2966"},
        {"name": "Code Geass: Lelouch of the Rebellion R2", "url": "https://anilist.co/anime/2904"},
        {"name": "The Girl Who Leapt Through Time", "url": "https://anilist.co/anime/2236"},
        {"name": "Clannad", "url": "https://anilist.co/anime/2167"},
        {"name": "Darker than Black", "url": "https://anilist.co/anime/2025"},
        {"name": "Lucky☆Star", "url": "https://anilist.co/anime/1887"},
        {"name": "When They Cry", "url": "https://anilist.co/anime/934"},
        {"name": "Hellsing Ultimate", "url": "https://anilist.co/anime/777"},
        {"name": "Grave of the Fireflies", "url": "https://anilist.co/anime/578"},
        {"name": "Hajime no Ippo: The Fighting!", "url": "https://anilist.co/anime/263"},
        {"name": "FLCL", "url": "https://anilist.co/anime/227"},
        {"name": "Spirited Away", "url": "https://anilist.co/anime/199"},
        {"name": "Fullmetal Alchemist", "url": "https://anilist.co/anime/121"},
        {"name": "Mobile Suit Zeta Gundam", "url": "https://anilist.co/anime/85"},
        {"name": "Akira", "url": "https://anilist.co/anime/47"},
        {"name": "Ghost in the Shell", "url": "https://anilist.co/anime/43"},
        {"name": "METEORGIRL", "url": "https://anilist.co/anime/189304"},
        {"name": "Kuroiwa Medaka ni Watashi no Kawaii ga Tsuujinai 2nd Season", "url": "https://anilist.co/anime/188892"},
        {"name": "Rurouni Kenshin: Meiji Kenkaku Romantan 3", "url": "https://anilist.co/anime/188665"},
        {"name": "Kono Subarashii Sekai ni Shukufuku wo! (Zoku-hen)", "url": "https://anilist.co/anime/187924"},
        {"name": "Kimi ga Shinu made Koi wo Shitai", "url": "https://anilist.co/anime/187260"},
        {"name": "Bocchi the Rock! 2nd Season", "url": "https://anilist.co/anime/186712"},
        {"name": "Nageki no Bourei wa Intai shitai 2", "url": "https://anilist.co/anime/185801"},
        {"name": "Tsuihousha Shokudou e Youkoso!", "url": "https://anilist.co/anime/185544"},
        {"name": "Seihantai na Kimi to Boku", "url": "https://anilist.co/anime/184951"},
        {"name": "Catch Me at the Ballpark!", "url": "https://anilist.co/anime/184279"},
        {"name": "Watashi wo Tabetai, Hitodenashi", "url": "https://anilist.co/anime/183385"},
        {"name": "Lockdown Zone: Level X Season 2", "url": "https://anilist.co/anime/182877"},
        {"name": "CITY THE ANIMATION", "url": "https://anilist.co/anime/181841"},
        {"name": "Kobayashi-san Chi no Maidragon Samishii Gariya no Ryuu", "url": "https://anilist.co/anime/181839"},
        {"name": "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 4th Season", "url": "https://anilist.co/anime/180745"},
        {"name": "Ame to Kimi to", "url": "https://anilist.co/anime/180425"},
        {"name": "I Was Reincarnated as the 7th Prince So I Can Take My Time Perfecting My Magical Ability Season 2", "url": "https://anilist.co/anime/178090"},
        {"name": "The Quintessential Quintuplets Specials 2", "url": "https://anilist.co/anime/177191"},
        {"name": "Good Bye, Dragon Life", "url": "https://anilist.co/anime/176053"},
        {"name": "MONOGATARI Series: OFF & MONSTER Season", "url": "https://anilist.co/anime/173533"},
        {"name": "Plus-Sized Elf", "url": "https://anilist.co/anime/173388"},
        {"name": "Uma Musume: Pretty Derby - Shin Jidai no Tobira", "url": "https://anilist.co/anime/172420"},
        {"name": "A Nobody's Way Up to an Exploration Hero", "url": "https://anilist.co/anime/172416"},
        {"name": "Kage no Jitsuryokusha ni Naritakute!: Zankyou-hen", "url": "https://anilist.co/anime/171952"},
        {"name": "Nina the Starry Bride", "url": "https://anilist.co/anime/171038"},
        {"name": "Chillin' in Another World with Level 2 Super Cheat Powers", "url": "https://anilist.co/anime/170130"},
        {"name": "Kimi ni Todoke: From Me to You Season 3", "url": "https://anilist.co/anime/168872"},
        {"name": "My Hero Academia: You’re Next", "url": "https://anilist.co/anime/168013"},
        {"name": "The Demon Prince of Momochi House", "url": "https://anilist.co/anime/167146"},
        {"name": "Sword Art Online Alternative: Gun Gale Online II", "url": "https://anilist.co/anime/167141"},
        {"name": "The Fable", "url": "https://anilist.co/anime/166910"},
        {"name": "Suicide Squad ISEKAI", "url": "https://anilist.co/anime/166710"},
        {"name": "Fate/strange Fake", "url": "https://anilist.co/anime/166617"},
        {"name": "MASHLE: MAGIC AND MUSCLES Season 2", "url": "https://anilist.co/anime/166610"},
        {"name": "The Dangers in My Heart Season 2", "url": "https://anilist.co/anime/166216"},
        {"name": "A Condition Called Love", "url": "https://anilist.co/anime/165855"},
        {"name": "365 Days to the Wedding", "url": "https://anilist.co/anime/165790"},
        {"name": "The Foolish Angel Dances with the Devil", "url": "https://anilist.co/anime/164244"},
        {"name": "Tokyo Revengers Season 2 Part 2", "url": "https://anilist.co/anime/163329"},
        {"name": "The Ossan Newbie Adventurer, Trained to Death by the Most Powerful Party, Became Invincible", "url": "https://anilist.co/anime/163292"},
        {"name": "A Returner's Magic Should Be Special", "url": "https://anilist.co/anime/163142"},
        {"name": "AQUARION: Myth of Emotions", "url": "https://anilist.co/anime/162921"},
        {"name": "Mr. Villain's Day Off", "url": "https://anilist.co/anime/162002"},
        {"name": "Rascal Does Not Dream of a Knapsack Kid", "url": "https://anilist.co/anime/161474"},
        {"name": "VTuber Legend: How I Went Viral after Forgetting to Turn Off My Stream", "url": "https://anilist.co/anime/160488"},
        {"name": "The Girl I Like Forgot Her Glasses", "url": "https://anilist.co/anime/160188"},
        {"name": "Whisper Me a Love Song", "url": "https://anilist.co/anime/160181"},
        {"name": "Mysterious Disappearances", "url": "https://anilist.co/anime/160090"},
        {"name": "SPY x FAMILY Season 2", "url": "https://anilist.co/anime/158927"},
        {"name": "I'm in Love with the Villainess", "url": "https://anilist.co/anime/158704"},
        {"name": "Campfire Cooking in Another World with my Absurd Skill", "url": "https://anilist.co/anime/156067"},
        {"name": "Synduality Noir", "url": "https://anilist.co/anime/154643"},
        {"name": "The Café Terrace and Its Goddesses", "url": "https://anilist.co/anime/154412"},
        {"name": "Am I Actually the Strongest?", "url": "https://anilist.co/anime/154391"},
        {"name": "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too", "url": "https://anilist.co/anime/153845"},
        {"name": "One Punch Man 3", "url": "https://anilist.co/anime/153800"},
        {"name": "HAIKYU!! The Dumpster Battle", "url": "https://anilist.co/anime/153658"},
        {"name": "Reborn as a Vending Machine, I Now Wander the Dungeon", "url": "https://anilist.co/anime/153360"},
        {"name": "The Ice Guy and His Cool Female Colleague", "url": "https://anilist.co/anime/151252"},
        {"name": "My Home Hero", "url": "https://anilist.co/anime/151189"},
        {"name": "Kubo Won't Let Me Be Invisible", "url": "https://anilist.co/anime/148969"},
        {"name": "In Another World With My Smartphone 2", "url": "https://anilist.co/anime/147571"},
        {"name": "My Happy Marriage", "url": "https://anilist.co/anime/147103"},
        {"name": "Engage Kiss", "url": "https://anilist.co/anime/146625"},
        {"name": "NieR:Automata Ver1.1a", "url": "https://anilist.co/anime/145665"},
        {"name": "Black Summoner", "url": "https://anilist.co/anime/145260"},
        {"name": "Insomniacs After School", "url": "https://anilist.co/anime/143653"},
        {"name": "Rurouni Kenshin (2023)", "url": "https://anilist.co/anime/142877"},
        {"name": "Yu☆Gi☆Oh! Go Rush!!", "url": "https://anilist.co/anime/142842"},
        {"name": "SPY x FAMILY Cour 2", "url": "https://anilist.co/anime/142838"},
        {"name": "TONIKAWA: Over The Moon For You Season 2", "url": "https://anilist.co/anime/141208"},
        {"name": "SPY x FAMILY", "url": "https://anilist.co/anime/140960"},
        {"name": "Tokyo 24th Ward", "url": "https://anilist.co/anime/140643"},
        {"name": "Mob Psycho 100 III", "url": "https://anilist.co/anime/140439"},
        {"name": "I'm the Villainess, So I'm Taming the Final Boss", "url": "https://anilist.co/anime/139820"},
        {"name": "Management of a Novice Alchemist", "url": "https://anilist.co/anime/139369"},
        {"name": "Teasing Master Takagi-san Season 3", "url": "https://anilist.co/anime/138424"},
        {"name": "Komi Can’t Communicate", "url": "https://anilist.co/anime/133965"},
        {"name": "A Couple of Cuckoos", "url": "https://anilist.co/anime/132052"},
        {"name": "JUJUTSU KAISEN 0", "url": "https://anilist.co/anime/131573"},
        {"name": "Scarlet Nexus", "url": "https://anilist.co/anime/131150"},
        {"name": "The Devil is a Part-Timer! Season 2", "url": "https://anilist.co/anime/130592"},
        {"name": "The Misfit of Demon King Academy Ⅱ: History's Strongest Demon King Reincarnates and Goes to School with His Descendants", "url": "https://anilist.co/anime/130588"},
        {"name": "My Isekai Life: I Gained a Second Character Class and Became the Strongest Sage in the World!", "url": "https://anilist.co/anime/129192"},
        {"name": "Platinum End", "url": "https://anilist.co/anime/127401"},
        {"name": "Record of Ragnarok", "url": "https://anilist.co/anime/127399"},
        {"name": "Love of Kill", "url": "https://anilist.co/anime/127050"},
        {"name": "Girlfriend, Girlfriend", "url": "https://anilist.co/anime/126192"},
        {"name": "Peach Boy Riverside", "url": "https://anilist.co/anime/122441"},
        {"name": "BLEACH: Thousand-Year Blood War", "url": "https://anilist.co/anime/116674"},
        {"name": "Date A Live IV", "url": "https://anilist.co/anime/116605"},
        {"name": "Welcome to Demon School! Iruma-kun Season 2", "url": "https://anilist.co/anime/116338"},
        {"name": "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway", "url": "https://anilist.co/anime/114232"},
        {"name": "The Daily Life of the Immortal King", "url": "https://anilist.co/anime/114121"},
        {"name": "Food Wars! The Fifth Plate", "url": "https://anilist.co/anime/114043"},
        {"name": "The Misfit of Demon King Academy: History’s Strongest Demon King Reincarnates and Goes to School with His Descendants", "url": "https://anilist.co/anime/112301"},
        {"name": "Uzumaki", "url": "https://anilist.co/anime/111314"},
        {"name": "Food Wars! The Fourth Plate", "url": "https://anilist.co/anime/109963"},
        {"name": "given", "url": "https://anilist.co/anime/108430"},
        {"name": "Ascendance of a Bookworm", "url": "https://anilist.co/anime/108268"},
        {"name": "Science Fell in Love, So I Tried to Prove It", "url": "https://anilist.co/anime/107067"},
        {"name": "Cautious Hero: The Hero Is Overpowered but Overly Cautious", "url": "https://anilist.co/anime/105156"},
        {"name": "Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?", "url": "https://anilist.co/anime/104723"},
        {"name": "So I'm a Spider, So What?", "url": "https://anilist.co/anime/103632"},
        {"name": "The Quintessential Quintuplets", "url": "https://anilist.co/anime/103572"},
        {"name": "Violet Evergarden: the Movie", "url": "https://anilist.co/anime/103047"},
        {"name": "Chihayafuru 3", "url": "https://anilist.co/anime/101215"},
        {"name": "Grand Blue Dreaming", "url": "https://anilist.co/anime/100922"},
        {"name": "Tokyo Ghoul:re", "url": "https://anilist.co/anime/100240"},
        {"name": "Re:ZERO -Starting Life in Another World- OVAs", "url": "https://anilist.co/anime/100049"},
        {"name": "MAGICAL GIRL SITE", "url": "https://anilist.co/anime/100010"},
        {"name": "Teasing Master Takagi-san", "url": "https://anilist.co/anime/99468"},
        {"name": "Food Wars! The Third Plate", "url": "https://anilist.co/anime/99255"},
        {"name": "Overlord II", "url": "https://anilist.co/anime/98437"},
        {"name": "BLEND-S", "url": "https://anilist.co/anime/97994"},
        {"name": "BAKI", "url": "https://anilist.co/anime/97888"},
        {"name": "Blue Exorcist: Kyoto Saga", "url": "https://anilist.co/anime/21861"},
        {"name": "Little Witch Academia (TV)", "url": "https://anilist.co/anime/21858"},
        {"name": "Masamune-kun's Revenge", "url": "https://anilist.co/anime/21857"},
        {"name": "Miss Kobayashi's Dragon Maid", "url": "https://anilist.co/anime/21776"},
        {"name": "HAIKYU!! 3rd Season", "url": "https://anilist.co/anime/21698"},
        {"name": "Orange", "url": "https://anilist.co/anime/21647"},
        {"name": "Food Wars! The Second Plate", "url": "https://anilist.co/anime/21518"},
        {"name": "Tanaka-kun is Always Listless", "url": "https://anilist.co/anime/21495"},
        {"name": "Bungo Stray Dogs", "url": "https://anilist.co/anime/21311"},
        {"name": "Saekano: How to Raise a Boring Girlfriend ♭", "url": "https://anilist.co/anime/21180"},
        {"name": "Dragon Ball Super", "url": "https://anilist.co/anime/21175"},
        {"name": "Monster Musume: Everyday Life With Monster Girls", "url": "https://anilist.co/anime/21093"},
        {"name": "Himouto! Umaru-chan", "url": "https://anilist.co/anime/20987"},
        {"name": "My Love Story!!", "url": "https://anilist.co/anime/20946"},
        {"name": "Durarara!! X2 The Second Arc", "url": "https://anilist.co/anime/20879"},
        {"name": "Lord Marksman and Vanadis", "url": "https://anilist.co/anime/20809"},
        {"name": "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt", "url": "https://anilist.co/anime/20799"},
        {"name": "Fate/stay night: Unlimited Blade Works 2nd Season", "url": "https://anilist.co/anime/20792"},
        {"name": "World Trigger", "url": "https://anilist.co/anime/20729"},
        {"name": "My Teen Romantic Comedy SNAFU TOO!", "url": "https://anilist.co/anime/20698"},
        {"name": "Saekano: How to Raise a Boring Girlfriend", "url": "https://anilist.co/anime/20657"},
        {"name": "Sword Art Online II", "url": "https://anilist.co/anime/20594"},
        {"name": "The Kawai Complex Guide to Manors and Hostel Behavior", "url": "https://anilist.co/anime/20529"},
        {"name": "JoJo's Bizarre Adventure: Stardust Crusaders", "url": "https://anilist.co/anime/20474"},
        {"name": "Date A Live II", "url": "https://anilist.co/anime/19163"},
        {"name": "Kuroko's Basketball 2", "url": "https://anilist.co/anime/16894"},
        {"name": "The Last: Naruto the Movie", "url": "https://anilist.co/anime/16870"},
        {"name": "The Wind Rises", "url": "https://anilist.co/anime/16662"},
        {"name": "The Devil is a Part-Timer!", "url": "https://anilist.co/anime/15809"},
        {"name": "Kamisama Kiss", "url": "https://anilist.co/anime/14713"},
        {"name": "My Little Monster", "url": "https://anilist.co/anime/14227"},
        {"name": "Daily Lives of High School Boys", "url": "https://anilist.co/anime/11843"},
        {"name": "Fate/Zero Season 2", "url": "https://anilist.co/anime/11741"},
        {"name": "High School DxD", "url": "https://anilist.co/anime/11617"},
        {"name": "Penguindrum", "url": "https://anilist.co/anime/10721"},
        {"name": "Blood-C", "url": "https://anilist.co/anime/10490"},
        {"name": "Toaru Kagaku no Railgun: Entenka no Satsuei Model mo Raku ja Arimasen wa ne.", "url": "https://anilist.co/anime/9063"},
        {"name": "High School of the Dead", "url": "https://anilist.co/anime/8074"},
        {"name": "Maid-Sama!", "url": "https://anilist.co/anime/7054"},
        {"name": "Baka and Test - Summon the Beasts", "url": "https://anilist.co/anime/6347"},
        {"name": "Dragon Ball Z Kai", "url": "https://anilist.co/anime/6033"},
        {"name": "Angel of Legend", "url": "https://anilist.co/anime/5251"},
        {"name": "Black Butler", "url": "https://anilist.co/anime/4898"},
        {"name": "Ponyo", "url": "https://anilist.co/anime/2890"},
        {"name": "School Days (TV)", "url": "https://anilist.co/anime/2476"},
        {"name": "The Familiar of Zero", "url": "https://anilist.co/anime/1195"},
        {"name": "Sailor Moon Sailor Stars", "url": "https://anilist.co/anime/996"},
        {"name": "Shin Chan", "url": "https://anilist.co/anime/966"},
        {"name": "Ergo Proxy", "url": "https://anilist.co/anime/790"},
        {"name": "Kiki's Delivery Service", "url": "https://anilist.co/anime/512"},
        {"name": "Haibane Renmei", "url": "https://anilist.co/anime/387"},
        {"name": "Hellsing", "url": "https://anilist.co/anime/270"},
        {"name": "InuYasha", "url": "https://anilist.co/anime/249"},
        {"name": "Air", "url": "https://anilist.co/anime/101"},
        {"name": "Rurouni Kenshin", "url": "https://anilist.co/anime/45"},
        {"name": "Berserk", "url": "https://anilist.co/anime/33"},
        {"name": "Trigun", "url": "https://anilist.co/anime/6"},
        {"name": "Momentary Lily: Tsudzuite iku Kappou, Kappou!", "url": "https://anilist.co/anime/189160"},
        {"name": "Koisuru ONE PIECE", "url": "https://anilist.co/anime/188668"},
        {"name": "Natsume Yuujinchou × Kumamoto-ken: Hitoyoshi Kuma de no Yasashii Jikan", "url": "https://anilist.co/anime/188619"},
        {"name": "ALL YOU NEED IS KILL", "url": "https://anilist.co/anime/187892"},
        {"name": "Ansatsusha de Aru Ore no Status ga Yuusha yori mo Akiraka ni Tsuyoi no da ga", "url": "https://anilist.co/anime/186794"},
        {"name": "Princess Principal: Crown Handler - Chapter 4", "url": "https://anilist.co/anime/186716"},
        {"name": "Fushigi ‌no ‌Kuni ‌de ‌Alice to: Dive ‌in ‌Wonderland", "url": "https://anilist.co/anime/186181"},
        {"name": "Yuugao", "url": "https://anilist.co/anime/186153"},
        {"name": "Maomao no Hitorigoto 2nd Season", "url": "https://anilist.co/anime/186148"},
        {"name": "Solo Camping for Two", "url": "https://anilist.co/anime/185965"},
        {"name": "Skip and Loafer Season 2", "url": "https://anilist.co/anime/185657"},
        {"name": "Theatre of Darkness: Yamishibai 14", "url": "https://anilist.co/anime/185088"},
        {"name": "Uchuujin MuuMuu", "url": "https://anilist.co/anime/185070"},
        {"name": "Nazotoki wa Dinner no Ato de", "url": "https://anilist.co/anime/184989"},
        {"name": "Dekin no Mogura: The Earthbound Mole", "url": "https://anilist.co/anime/184574"},
        {"name": "Xianwu Zhuan 3", "url": "https://anilist.co/anime/183157"},
        {"name": "ONE PIECE FAN LETTER", "url": "https://anilist.co/anime/182469"},
        {"name": "Re:Zero kara Hajimeru Kyuukei Jikan (Break Time) 3rd Season", "url": "https://anilist.co/anime/182417"},
        {"name": "Tensei Shitara Slime Datta Ken - Soukai no Namida-hen", "url": "https://anilist.co/anime/182206"},
        {"name": "Virgin Punk", "url": "https://anilist.co/anime/181449"},
        {"name": "SHOSHIMIN: How to become Ordinary Season 2", "url": "https://anilist.co/anime/181182"},
        {"name": "Ruri no Houseki", "url": "https://anilist.co/anime/180929"},
        {"name": "Tsuihou Sareta Tensei Juukishi wa Game Sashiki de Musou Suru", "url": "https://anilist.co/anime/180136"},
        {"name": "Negative Positive Angler", "url": "https://anilist.co/anime/179919"},
        {"name": "Yuusha Party wo Tsuihou Sareta Shiro Madoushi, S Rank Boukensha ni Hirowareru: Kono Shiro Madoushi ga Kikakugaisugiru", "url": "https://anilist.co/anime/179885"},
        {"name": "Kanojo, Okarishimasu 4th Season", "url": "https://anilist.co/anime/179344"},
        {"name": "Fire Force Season 3 Part 2", "url": "https://anilist.co/anime/179062"},
        {"name": "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha", "url": "https://anilist.co/anime/178869"},
        {"name": "Bad Girl", "url": "https://anilist.co/anime/178675"},
        {"name": "TASOKARE HOTEL", "url": "https://anilist.co/anime/178495"},
        {"name": "DEAD DEAD DEMONS DEDEDEDE DESTRUCTION", "url": "https://anilist.co/anime/177697"},
        {"name": "YAIBA: Samurai Legend", "url": "https://anilist.co/anime/177476"},
        {"name": "Tougen Anki: Legend of the Cursed Blood", "url": "https://anilist.co/anime/177474"},
        {"name": "The Most Notorious Talker Runs the World's Greatest Clan", "url": "https://anilist.co/anime/177104"},
        {"name": "Uma Musume: Pretty Derby - ROAD TO THE TOP Movie", "url": "https://anilist.co/anime/176299"},
        {"name": "Nyaight of the Living Cat", "url": "https://anilist.co/anime/175124"},
        {"name": "Tono to Inu", "url": "https://anilist.co/anime/174390"},
        {"name": "Tasuketsu -Fate of the Majority-", "url": "https://anilist.co/anime/174070"},
        {"name": "The Healer Who Was Banished From His Party, Is, in Fact, the Strongest", "url": "https://anilist.co/anime/174043"},
        {"name": "Sai-Kyo-Oh! Zukan: The Ultimate Battles", "url": "https://anilist.co/anime/173216"},
        {"name": "Yumemiru Otome", "url": "https://anilist.co/anime/172218"},
        {"name": "A Terrified Teacher at Ghoul School!", "url": "https://anilist.co/anime/171545"},
        {"name": "Trapezium", "url": "https://anilist.co/anime/171291"},
        {"name": "A Journey Through Another World: Raising Kids While Adventuring", "url": "https://anilist.co/anime/171031"},
        {"name": "Wonderful Precure!", "url": "https://anilist.co/anime/171030"},
        {"name": "Magilumiere Magical Girls Inc.", "url": "https://anilist.co/anime/171025"},
        {"name": "Promise of Wizard", "url": "https://anilist.co/anime/170916"},
        {"name": "THE NEW GATE", "url": "https://anilist.co/anime/170890"},
        {"name": "I Want to Escape from Princess Lessons", "url": "https://anilist.co/anime/170650"},
        {"name": "YATAGARASU: The Raven Does Not Choose Its Master", "url": "https://anilist.co/anime/170503"},
        {"name": "Yakuza Fiancé: Raise wa Tanin ga Ii", "url": "https://anilist.co/anime/170468"},
        {"name": "Scott Pilgrim Takes Off", "url": "https://anilist.co/anime/170206"},
        {"name": "The Strongest Tank's Labyrinth Raids -A Tank with a Rare 9999 Resistance Skill Got Kicked from the Hero's Party-", "url": "https://anilist.co/anime/169935"},
        {"name": "How I Attended an All-Guy's Mixer", "url": "https://anilist.co/anime/169931"},
        {"name": "Case Closed: The Million-dollar Pentagram", "url": "https://anilist.co/anime/169754"},
        {"name": "Synduality Noir Part 2", "url": "https://anilist.co/anime/169559"},
        {"name": "Re:Monster", "url": "https://anilist.co/anime/169417"},
        {"name": "Dahlia in Bloom: Crafting a Fresh Start with Magical Tools", "url": "https://anilist.co/anime/168623"},
        {"name": "Demon Lord, Retry! R", "url": "https://anilist.co/anime/168500"},
        {"name": "I’ll Become a Villainess Who Goes Down in History", "url": "https://anilist.co/anime/168139"},
        {"name": "Grandpa and Grandma Turn Young Again", "url": "https://anilist.co/anime/168138"},
        {"name": "GOOD NIGHT WORLD", "url": "https://anilist.co/anime/167820"},
        {"name": "UniteUp! -Uni:Birth-", "url": "https://anilist.co/anime/167742"},
        {"name": "Yuusha Kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku", "url": "https://anilist.co/anime/167152"},
        {"name": "Love Is Indivisible by Twins", "url": "https://anilist.co/anime/167144"},
        {"name": "Cherry Magic! Thirty Years of Virginity Can Make You a Wizard?!", "url": "https://anilist.co/anime/167087"},
        {"name": "A Salad Bowl of Eccentrics", "url": "https://anilist.co/anime/166828"},
        {"name": "Hell’s Paradise Season 2", "url": "https://anilist.co/anime/166613"},
        {"name": "'Tis Time for Torture, Princess", "url": "https://anilist.co/anime/166522"},
        {"name": "The Café Terrace and Its Goddesses Season 2", "url": "https://anilist.co/anime/166477"},
        {"name": "Mofa Gongzhu De Xiao Fannao", "url": "https://anilist.co/anime/165530"},
        {"name": "ZatsuTabi -That's Journey-", "url": "https://anilist.co/anime/165445"},
        {"name": "BEYBLADE X", "url": "https://anilist.co/anime/165159"},
        {"name": "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World", "url": "https://anilist.co/anime/164702"},
        {"name": "Go-toubun no Hanayome∽", "url": "https://anilist.co/anime/163327"},
        {"name": "Jellyfish Can’t Swim in the Night", "url": "https://anilist.co/anime/163078"},
        {"name": "Metallic Rouge", "url": "https://anilist.co/anime/162985"},
        {"name": "3-nen Z-gumi Ginpachi-sensei", "url": "https://anilist.co/anime/162890"},
        {"name": "Gushing Over Magical Girls", "url": "https://anilist.co/anime/162780"},
        {"name": "Doctor Elise: The Royal Lady with the Lamp", "url": "https://anilist.co/anime/162144"},
        {"name": "GAMERA -Rebirth-", "url": "https://anilist.co/anime/160831"},
        {"name": "Tales of Wedding Rings", "url": "https://anilist.co/anime/160389"},
        {"name": "Zom 100: Bucket List of the Dead", "url": "https://anilist.co/anime/159831"},
        {"name": "The Many Sides of Voice Actor Radio", "url": "https://anilist.co/anime/159039"},
        {"name": "Blue Exorcist -Shimane Illuminati Saga-", "url": "https://anilist.co/anime/158931"},
        {"name": "GHOST CAT ANZU", "url": "https://anilist.co/anime/158641"},
        {"name": "Lookism", "url": "https://anilist.co/anime/158539"},
        {"name": "The Gene of AI", "url": "https://anilist.co/anime/158530"},
        {"name": "GO! GO! Loser Ranger!", "url": "https://anilist.co/anime/158417"},
        {"name": "The Colors Within", "url": "https://anilist.co/anime/158166"},
        {"name": "My Instant Death Ability is Overpowered", "url": "https://anilist.co/anime/158028"},
        {"name": "The Dreaming Boy is a Realist", "url": "https://anilist.co/anime/157397"},
        {"name": "Bye Bye, Earth", "url": "https://anilist.co/anime/157371"},
        {"name": "The Weakest Tamer Began a Journey to Pick Up Trash", "url": "https://anilist.co/anime/156891"},
        {"name": "Busu ni Hanataba wo.", "url": "https://anilist.co/anime/156395"},
        {"name": "My Daughter Left the Nest and Returned an S-Rank Adventurer", "url": "https://anilist.co/anime/156184"},
        {"name": "Banished from the Hero’s Party, I Decided to Live a Quiet Life in the Countryside Season 2", "url": "https://anilist.co/anime/156131"},
        {"name": "The Girl Downstairs", "url": "https://anilist.co/anime/156111"},
        {"name": "Berserk of Gluttony", "url": "https://anilist.co/anime/156039"},
        {"name": "Hokkaido Gals Are Super Adorable!", "url": "https://anilist.co/anime/155963"},
        {"name": "Tsuyokute New Saga", "url": "https://anilist.co/anime/155838"},
        {"name": "Train to the End of the World", "url": "https://anilist.co/anime/155657"},
        {"name": "Urusei Yatsura (2022) Season 3", "url": "https://anilist.co/anime/155645"},
        {"name": "ATRI -My Dear Moments-", "url": "https://anilist.co/anime/154963"},
        {"name": "Mecha Ude: Mechanical Arms", "url": "https://anilist.co/anime/154673"},
        {"name": "Let You Down", "url": "https://anilist.co/anime/154591"},
        {"name": "The Ancient Magus' Bride Season 2", "url": "https://anilist.co/anime/154364"},
        {"name": "I'm Giving the Disgraced Noble Lady I Rescued a Crash Course in Naughtiness", "url": "https://anilist.co/anime/154214"},
        {"name": "The Witch and the Beast", "url": "https://anilist.co/anime/153818"},
        {"name": "The Magical Revolution of the Reincarnated Princess and the Genius Young Lady", "url": "https://anilist.co/anime/153629"},
        {"name": "The Aristocrat’s Otherworldly Adventure: Serving Gods Who Go Too Far", "url": "https://anilist.co/anime/153332"},
        {"name": "Sasaki and Peeps", "url": "https://anilist.co/anime/152682"},
        {"name": "Chillin’ in My 30s after Getting Fired from the Demon King’s Army", "url": "https://anilist.co/anime/152523"},
        {"name": "Fluffy Paradise", "url": "https://anilist.co/anime/152072"},
        {"name": "Tomo-chan Is a Girl!", "url": "https://anilist.co/anime/151806"},
        {"name": "Kaguya-sama: Love is War -The First Kiss That Never Ends-", "url": "https://anilist.co/anime/151384"},
        {"name": "Beast Tamer", "url": "https://anilist.co/anime/150695"},
        {"name": "The Masterful Cat is Depressed Again Today", "url": "https://anilist.co/anime/149883"},
        {"name": "Uma Musume: Pretty Derby - ROAD TO THE TOP", "url": "https://anilist.co/anime/148370"},
        {"name": "A Galaxy Next Door", "url": "https://anilist.co/anime/148098"},
        {"name": "Play It Cool, Guys", "url": "https://anilist.co/anime/147885"},
        {"name": "The Unwanted Undead Adventurer", "url": "https://anilist.co/anime/147642"},
        {"name": "Ao no Orchestra", "url": "https://anilist.co/anime/147369"},
        {"name": "Attack on Titan Final Season THE FINAL CHAPTERS Special 1", "url": "https://anilist.co/anime/146984"},
        {"name": "Masamune-kun's Revenge R", "url": "https://anilist.co/anime/146953"},
        {"name": "JoJo's Bizarre Adventure: STONE OCEAN Part 2", "url": "https://anilist.co/anime/146722"},
        {"name": "RWBY: Ice Queendom", "url": "https://anilist.co/anime/146668"},
        {"name": "Grisaia: Phantom Trigger", "url": "https://anilist.co/anime/145740"},
        {"name": "Lonely Castle in the Mirror", "url": "https://anilist.co/anime/145739"},
        {"name": "The Reincarnation of the Strongest Exorcist in Another World", "url": "https://anilist.co/anime/144553"},
        {"name": "Lucifer and the Biscuit Hammer", "url": "https://anilist.co/anime/144323"},
        {"name": "The Irregular at Magic High School Season 3", "url": "https://anilist.co/anime/143271"},
        {"name": "Butareba -The Story of a Man Turned into a Pig-", "url": "https://anilist.co/anime/142599"},
        {"name": "Golden Kamuy Season 4", "url": "https://anilist.co/anime/142343"},
        {"name": "Seirei Gensouki: Spirit Chronicles Season 2", "url": "https://anilist.co/anime/141182"},
        {"name": "Tomodachi Game", "url": "https://anilist.co/anime/141014"},
        {"name": "Summoned to Another World for a Second Time", "url": "https://anilist.co/anime/140754"},
        {"name": "DON'T TOY WITH ME, MISS NAGATORO 2nd Attack", "url": "https://anilist.co/anime/140596"},
        {"name": "I'm Quitting Heroing", "url": "https://anilist.co/anime/140457"},
        {"name": "Our Last Crusade or the Rise of a New World Season 2", "url": "https://anilist.co/anime/139825"},
        {"name": "How a Realist Hero Rebuilt the Kingdom Part 2", "url": "https://anilist.co/anime/139648"},
        {"name": "My Hero Academia Season 6", "url": "https://anilist.co/anime/139630"},
        {"name": "TSUKIMICHI -Moonlit Fantasy- Season 2", "url": "https://anilist.co/anime/139518"},
        {"name": "Welcome to Demon School! Iruma-kun Season 3", "url": "https://anilist.co/anime/139092"},
        {"name": "To Your Eternity Season 2", "url": "https://anilist.co/anime/138565"},
        {"name": "The Wrong Way to Use Healing Magic", "url": "https://anilist.co/anime/137908"},
        {"name": "Guimi Zhi Zhu", "url": "https://anilist.co/anime/137667"},
        {"name": "Deep Insanity THE LOST CHILD", "url": "https://anilist.co/anime/136947"},
        {"name": "Life With an Ordinary Guy Who Reincarnated Into a Total Fantasy Knockout", "url": "https://anilist.co/anime/134252"},
        {"name": "BUILD-DIVIDE -#000000- CODE BLACK", "url": "https://anilist.co/anime/132525"},
        {"name": "Skeleton Knight in Another World", "url": "https://anilist.co/anime/132474"},
        {"name": "The Faraway Paladin", "url": "https://anilist.co/anime/132473"},
        {"name": "Dance Dance Danseur", "url": "https://anilist.co/anime/132171"},
        {"name": "Love After World Domination", "url": "https://anilist.co/anime/132010"},
        {"name": "Mieruko-chan", "url": "https://anilist.co/anime/131083"},
        {"name": "Irina: The Vampire Cosmonaut", "url": "https://anilist.co/anime/131019"},
        {"name": "The Misfit of Demon King Academy II (Cour 2)", "url": "https://anilist.co/anime/130590"},
        {"name": "Sacrificial Princess and the King of Beasts", "url": "https://anilist.co/anime/128715"},
        {"name": "The Detective Is Already Dead", "url": "https://anilist.co/anime/128712"},
        {"name": "When Will Ayumu Make His Move?", "url": "https://anilist.co/anime/128223"},
        {"name": "I'm Standing on a Million Lives Season 2", "url": "https://anilist.co/anime/127366"},
        {"name": "Gintama: THE SEMI-FINAL", "url": "https://anilist.co/anime/126819"},
        {"name": "SHADOWS HOUSE", "url": "https://anilist.co/anime/125038"},
        {"name": "Godzilla Singular Point", "url": "https://anilist.co/anime/124786"},
        {"name": "Uzaki-chan Wants to Hang Out! Season 2", "url": "https://anilist.co/anime/124395"},
        {"name": "SK8 the Infinity", "url": "https://anilist.co/anime/124153"},
        {"name": "Sword Art Online the Movie -Progressive- Aria of a Starless Night", "url": "https://anilist.co/anime/124140"},
        {"name": "The Dungeon of Black Company", "url": "https://anilist.co/anime/120608"},
        {"name": "Dawang Raoming", "url": "https://anilist.co/anime/120220"},
        {"name": "SHAMAN KING (2021)", "url": "https://anilist.co/anime/119675"},
        {"name": "MARS RED", "url": "https://anilist.co/anime/115183"},
        {"name": "A Whisker Away", "url": "https://anilist.co/anime/114963"},
        {"name": "Koikimo", "url": "https://anilist.co/anime/114840"},
        {"name": "World Trigger 2nd Season", "url": "https://anilist.co/anime/114087"},
        {"name": "Kemono Jihen", "url": "https://anilist.co/anime/114085"},
        {"name": "SSSS.DYNAZENON", "url": "https://anilist.co/anime/113950"},
        {"name": "Idoly Pride", "url": "https://anilist.co/anime/113814"},
        {"name": "Rent-a-Girlfriend", "url": "https://anilist.co/anime/113813"},
        {"name": "Ascendance of a Bookworm Part 2", "url": "https://anilist.co/anime/113693"},
        {"name": "HAIKYU‼ TO THE TOP Part 2", "url": "https://anilist.co/anime/113538"},
        {"name": "Kakushigoto", "url": "https://anilist.co/anime/113311"},
        {"name": "Heaven Official's Blessing", "url": "https://anilist.co/anime/113260"},
        {"name": "APPARE-RANMAN!", "url": "https://anilist.co/anime/112444"},
        {"name": "The Irregular at Magic High School: Visitor Arc", "url": "https://anilist.co/anime/112300"},
        {"name": "Is It Wrong to Try to Pick Up Girls in a Dungeon? III", "url": "https://anilist.co/anime/112124"},
        {"name": "Sleepy Princess in the Demon Castle", "url": "https://anilist.co/anime/111428"},
        {"name": "Ikebukuro West Gate Park", "url": "https://anilist.co/anime/111324"},
        {"name": "GIBIATE", "url": "https://anilist.co/anime/110446"},
        {"name": "BNA", "url": "https://anilist.co/anime/110354"},
        {"name": "Great Pretender", "url": "https://anilist.co/anime/110349"},
        {"name": "Interspecies Reviewers", "url": "https://anilist.co/anime/110270"},
        {"name": "The Boy and the Heron", "url": "https://anilist.co/anime/109979"},
        {"name": "Mob Psycho 100 II: The First Spirits and Such Company Trip ~A Journey that Mends the Heart and Heals the Soul~", "url": "https://anilist.co/anime/109819"},
    ]
};