const gamesData = {
    "games": [
        {"name": "Black Myth: Wukong", "url": "https://www.blackmythgame.com/"},
        {"name": "Assassin's Creed Shadows", "url": "index.html"},
        {"name": "Split Fiction", "url": "https://www.splitfictiongame.com/"},
        {"name": "Two Point Museum", "url": "https://www.twopointstudios.com/"},
        {"name": "Monster Hunter Wilds", "url": "https://www.monsterhunter.com/"},
        {"name": "Like a Dragon: Pirate Yakuza in Hawaii", "url": "https://www.sega.com/games/like-a-dragon"},
        {"name": "Civilization 7", "url": "https://civilization.com/"},
        {"name": "Kingdom Come: Deliverance 2", "url": "https://www.kingdomcomerpg.com/"},
        {"name": "Citizen Sleeper 2: Starward Vector", "url": "https://www.citizensleeper.com/"},
        {"name": "Dynasty Warriors: Origins", "url": "https://www.koeitecmoamerica.com/dw/"},
        {"name": "Mouthwashing", "url": "https://www.mouthwashinggame.com/"},
        {"name": "Marvel Rivals", "url": "https://www.neteasegames.com/marvel-rivals/"},
        {"name": "Indiana Jones and the Great Circle", "url": "https://www.bethesda.net/en/game/indiana-jones"},
        {"name": "Microsoft Flight Simulator 2024", "url": "https://www.flightsimulator.com/"},
        {"name": "STALKER 2: Heart of Chornobyl", "url": "https://www.stalker2.com/"},
        {"name": "Life is Strange: Double Exposure", "url": "https://lifeisstrange.square-enix-games.com/en-us"},
        {"name": "Dragon Age: The Veilguard", "url": "https://www.ea.com/games/dragon-age"},
        {"name": "Call of Duty: Black Ops 6", "url": "https://www.callofduty.com/"},
        {"name": "Sonic X Shadow Generations", "url": "https://www.sega.com/games/sonic"},
        {"name": "MechWarrior 5: Clans", "url": "https://mw5mercs.com/"},
        {"name": "Metaphor: ReFantazio", "url": "https://www.atlus.com/metaphor/"},
        {"name": "Silent Hill 2 Remake", "url": "https://www.konami.com/games/silenthill/"},
        {"name": "Warhammer 40,000: Space Marine 2", "url": "https://www.focus-entmt.com/games/warhammer-40000-space-marine-2"},
        {"name": "Counter-Strike 2 & GO", "url": "https://store.steampowered.com/app/730/CounterStrike_2/"},
        {"name": "Minecraft", "url": "https://www.minecraft.net/"},
        {"name": "Fortnite", "url": "https://www.epicgames.com/fortnite/"},
        {"name": "The Sims 4", "url": "https://www.ea.com/games/the-sims/the-sims-4"},
        {"name": "ROBLOX", "url": "https://www.roblox.com/"},
        {"name": "Marvel Rivals", "url": "https://www.neteasegames.com/marvel-rivals/"},
        {"name": "League of Legends", "url": "https://www.leagueoflegends.com/"},
        {"name": "Dota 2", "url": "https://www.dota2.com/"},
        {"name": "Valorant", "url": "https://playvalorant.com/"},
        {"name": "PUBG: BATTLEGROUNDS", "url": "https://pubg.com/"},
        {"name": "Call of Duty: Modern Warfare II/III/Warzone/Black Ops 6", "url": "https://www.callofduty.com/"},
        {"name": "Monster Hunter Wilds", "url": "https://www.monsterhunter.com/"},
        {"name": "Overwatch 1 & 2", "url": "https://overwatch.blizzard.com/"},
        {"name": "HELLDIVERS 2", "url": "https://www.playstation.com/en-us/games/helldivers-2/"},
        {"name": "Grand Theft Auto V", "url": "https://www.rockstargames.com/V/"},
        {"name": "Rocket League", "url": "https://www.rocketleague.com/"},
        {"name": "Tom Clancy's Rainbow Six: Siege", "url": "https://www.ubisoft.com/game/rainbow-six/siege"},
        {"name": "Apex Legends", "url": "https://www.ea.com/games/apex-legends"},
        {"name": "Delta Force", "url": "https://www.timi.net/"},
        {"name": "Rust", "url": "https://rust.facepunch.com/"},
        {"name": "Tetris", "url": "https://tetris.com"},
        {"name": "The Legend of Zelda: Ocarina of Time", "url": "https://www.zelda.com/ocarina-of-time"},
        {"name": "Super Mario 64", "url": "https://www.mariowiki.com/Super_Mario_64"},
        {"name": "Half-Life 2", "url": "https://www.half-life.com/en/half-life-2"},
        {"name": "Resident Evil 4", "url": "https://www.residentevil.com/re4"},
        {"name": "BioShock", "url": "https://bioshockgame.com"},
        {"name": "Final Fantasy VII", "url": "https://ffvii.square-enix-games.com"},
        {"name": "World of Warcraft", "url": "https://worldofwarcraft.com"},
        {"name": "Metal Gear Solid", "url": "https://www.konami.com/mg/mgs"},
        {"name": "Doom", "url": "https://slayersclub.bethesda.net"},
        {"name": "The Elder Scrolls V: Skyrim", "url": "https://elderscrolls.bethesda.net"},
        {"name": "Mass Effect 2", "url": "https://www.ea.com/games/mass-effect/mass-effect-2"},
        {"name": "The Last of Us", "url": "https://www.playstation.com/en-us/games/the-last-of-us-remastered/"},
        {"name": "Super Mario World", "url": "https://www.nintendo.com/games/detail/super-mario-world/"},
        {"name": "Chrono Trigger", "url": "https://www.square-enix-games.com/en_US/games/chrono-trigger"},
        {"name": "The Legend of Zelda: A Link to the Past", "url": "https://www.zelda.com/link-to-the-past"},
        {"name": "Red Dead Redemption", "url": "https://www.rockstargames.com/reddeadredemption"},
        {"name": "GoldenEye 007", "url": "https://en.wikipedia.org/wiki/GoldenEye_007_(1997_video_game)"},
        {"name": "Halo: Combat Evolved", "url": "https://www.halowaypoint.com"},
        {"name": "Portal 2", "url": "https://store.steampowered.com/app/620/Portal_2/"},
        {"name": "Minecraft", "url": "https://www.minecraft.net"},
        {"name": "Street Fighter II", "url": "https://www.capcom.com"},
        {"name": "Portal", "url": "https://store.steampowered.com/app/400/Portal/"},
        {"name": "The Witcher 3", "url": "https://thewitcher.com/en/witcher3"},
        {"name": "Super Metroid", "url": "https://www.nintendo.com/games/detail/super-metroid-wii-u/"},
        {"name": "Super Mario Bros.", "url": "https://www.nintendo.com/games/detail/super-mario-bros/"},
        {"name": "Shadow of the Colossus", "url": "https://www.playstation.com/en-us/games/shadow-of-the-colossus/"},
        {"name": "Deus Ex", "url": "https://www.eidosmontreal.com/games/deus-ex"},
        {"name": "Super Mario Bros. 3", "url": "https://www.nintendo.com/games/detail/super-mario-bros-3/"},
        {"name": "Grand Theft Auto V", "url": "https://www.rockstargames.com/V/"},
        {"name": "Half-Life", "url": "https://www.half-life.com/en/"},
        {"name": "Call of Duty 4: Modern Warfare", "url": "https://www.callofduty.com/modernwarfare"},
        {"name": "Uncharted 2: Among Thieves", "url": "https://www.playstation.com/en-us/games/uncharted-2-among-thieves/"},
        {"name": "Grand Theft Auto III", "url": "https://www.rockstargames.com/games/grandtheftauto3"},
        {"name": "Metroid Prime", "url": "https://www.nintendo.com/games/detail/metroid-prime-remastered-switch/"},
        {"name": "Starcraft", "url": "https://starcraft.com/"},
        {"name": "Dark Souls", "url": "https://en.bandainamcoent.eu/dark-souls/dark-souls-remastered"},
        {"name": "Castlevania: Symphony of the Night", "url": "https://www.konami.com/games/castlevania/"},
        {"name": "The Legend of Zelda: Breath of the Wild", "url": "https://www.zelda.com/breath-of-the-wild/"},
        {"name": "The Legend of Zelda", "url": "https://www.nintendo.com/games/detail/the-legend-of-zelda/"},
        {"name": "Pokemon Red/Blue", "url": "https://www.pokemon.com/us/"},
        {"name": "Super Mario Kart", "url": "https://www.nintendo.com/games/detail/super-mario-kart/"},
        {"name": "Star Wars: Knights of the Old Republic", "url": "https://www.aspyr.com/games/star-wars-knights-of-the-old-republic"},
        {"name": "Super Mario Galaxy", "url": "https://www.nintendo.com/games/detail/super-mario-galaxy/"},
        {"name": "Final Fantasy VI", "url": "https://ffvi.square-enix-games.com/"},
        {"name": "Fallout 3", "url": "https://fallout.bethesda.net/"},
        {"name": "The Legend of Zelda: The Wind Waker", "url": "https://www.zelda.com/the-wind-waker"},
        {"name": "Metal Gear Solid 3: Snake Eater", "url": "https://www.konami.com/mg/mgs3/"},
        {"name": "Resident Evil", "url": "https://www.residentevil.com/"},
        {"name": "Silent Hill 2", "url": "https://www.konami.com/games/silenthill/"},
        {"name": "Grand Theft Auto: San Andreas", "url": "https://www.rockstargames.com/sanandreas"},
        {"name": "Diablo II", "url": "https://diablo2.blizzard.com"},
        {"name": "Super Smash Bros. Melee", "url": "https://www.nintendo.com/games/detail/super-smash-bros-melee/"},
        {"name": "Pac-Man", "url": "https://www.namco.com/games/pac-man"},
        {"name": "Journey", "url": "https://thatgamecompany.com/journey/"},
        {"name": "Ico", "url": "https://www.playstation.com/en-us/games/ico/"},
        {"name": "Space Invaders", "url": "https://www.taito.com/games/space-invaders"},
        {"name": "Grand Theft Auto: Vice City", "url": "https://www.rockstargames.com/games/vicecity"},
        {"name": "Overwatch", "url": "https://playoverwatch.com"},
        {"name": "The Sims", "url": "https://www.ea.com/games/the-sims"},
        {"name": "Donkey Kong", "url": "https://www.nintendo.com/games/detail/donkey-kong/"},
        {"name": "Mario Kart 8", "url": "https://www.nintendo.com/games/detail/mario-kart-8-deluxe/"},
        {"name": "Super Mario Galaxy 2", "url": "https://www.nintendo.com/games/detail/super-mario-galaxy-2/"},
        {"name": "Bloodborne", "url": "https://www.playstation.com/en-us/games/bloodborne/"},
        {"name": "Baldur's Gate II", "url": "https://baldursgate.com"},
        {"name": "Tomb Raider", "url": "https://tombraider.square-enix-games.com"},
        {"name": "Team Fortress 2", "url": "https://www.teamfortress.com"},
        {"name": "Okami", "url": "https://www.capcom.com/okami/"},
        {"name": "Batman: Arkham Asylum", "url": "https://www.rockstargames.com/arkhamasylum"},
        {"name": "The Secret of Monkey Island", "url": "https://www.lucasarts.com/games/monkeyisland/"},
        {"name": "Mass Effect", "url": "https://www.ea.com/games/mass-effect"},
        {"name": "The Walking Dead", "url": "https://www.telltale.com/the-walking-dead/"},
        {"name": "Batman: Arkham City", "url": "https://www.rockstargames.com/arkhamcity"},
        {"name": "Prince of Persia: The Sands of Time", "url": "https://www.ubisoft.com/game/prince-of-persia-the-sands-of-time"},
        {"name": "Sonic the Hedgehog", "url": "https://www.sega.com/games/sonic"},
        {"name": "Grim Fandango", "url": "https://grimfandango.com"},
        {"name": "The Elder Scrolls IV: Oblivion", "url": "https://elderscrolls.bethesda.net/en/oblivion"},
        {"name": "The Legend of Zelda: Majora's Mask", "url": "https://www.zelda.com/majoras-mask"},
        {"name": "Wii Sports", "url": "https://www.nintendo.com/games/detail/wii-sports/"},
        {"name": "Counter-Strike", "url": "https://blog.counter-strike.net"},
        {"name": "Braid", "url": "https://www.braid-game.com"},
        {"name": "Pong", "url": "https://en.wikipedia.org/wiki/Pong"},
        {"name": "Final Fantasy X", "url": "https://www.finalfantasyx.com"},
        {"name": "Halo 2", "url": "https://www.halowaypoint.com"},
        {"name": "Sid Meier's Civilization", "url": "https://civilization.com"},
        {"name": "Halo 3", "url": "https://www.halowaypoint.com"},
        {"name": "System Shock 2", "url": "https://www.nightdive.com/games/system-shock-2"},
        {"name": "Mega Man 2", "url": "https://www.capcom.com/megaman"},
        {"name": "Super Mario Odyssey", "url": "https://www.nintendo.com/games/detail/super-mario-odyssey-switch/"},
        {"name": "Grand Theft Auto IV", "url": "https://www.rockstargames.com/games/IV"},
        {"name": "Assassin's Creed II", "url": "https://www.ubisoft.com/game/assassins-creed-ii"},
        {"name": "The Legend of Zelda: Twilight Princess", "url": "https://www.zelda.com/twilight-princess"},
        {"name": "Punch-Out!!", "url": "https://www.nintendo.com/games/detail/punch-out/"},
        {"name": "Earthbound", "url": "https://www.nintendo.com/games/detail/earthbound/"},
        {"name": "Metal Gear Solid V: The Phantom Pain", "url": "https://www.konami.com/mg/mgsv/"},
        {"name": "Resident Evil 2", "url": "https://www.residentevil.com/re2"},
        {"name": "Shin Megami Tensei: Persona 4", "url": "https://www.atlus.com/persona4golden/"},
        {"name": "Yoshi's Island", "url": "https://www.nintendo.com/games/detail/yoshis-island/"},
        {"name": "Quake", "url": "https://bethesda.net/en/game/quake"},
        {"name": "Doom (2016)", "url": "https://slayersclub.bethesda.net/en/game/doom"},
        {"name": "God of War", "url": "https://www.playstation.com/en-us/games/god-of-war-2005/"},
        {"name": "God of War (2018)", "url": "https://www.playstation.com/en-us/games/god-of-war/"},
        {"name": "Rocket League", "url": "https://www.rocketleague.com/"},
        {"name": "Tony Hawk's Pro Skater 2", "url": "https://www.tonyhawkthegame.com/"},
        {"name": "Mario Kart 64", "url": "https://www.nintendo.com/games/detail/mario-kart-64/"},
        {"name": "SimCity", "url": "https://www.ea.com/games/simcity"},
        {"name": "Secret of Mana", "url": "https://www.square-enix-games.com/games/secret-mana"},
        {"name": "Planescape: Torment", "url": "https://www.beamdog.com/planescape-torment"},
        {"name": "Gears of War", "url": "https://www.gearsofwar.com/"},
        {"name": "Horizon: Zero Dawn", "url": "https://www.guerrilla-games.com/play/horizon"},
        {"name": "Metal Gear Solid 2: Sons of Liberty", "url": "https://www.konami.com/mg/mgs2/"},
        {"name": "Sid Meier's Civilization IV", "url": "https://civilization.com/"},
        {"name": "The Elder Scrolls III: Morrowind", "url": "https://elderscrolls.bethesda.net/morrowind"},
        {"name": "Starcraft 2", "url": "https://starcraft2.com/"},
        {"name": "Uncharted 4: A Thief's End", "url": "https://www.playstation.com/en-us/games/uncharted-4/"},
        {"name": "Dead Space", "url": "https://www.ea.com/games/dead-space"},
        {"name": "Red Dead Redemption 2", "url": "https://www.rockstargames.com/reddeadredemption2"},
        {"name": "NBA Jam", "url": "https://en.wikipedia.org/wiki/NBA_Jam"},
        {"name": "Sonic the Hedgehog 2", "url": "https://www.sega.com/games/sonic"},
        {"name": "Ms. Pac-Man", "url": "https://www.namco.com/games/pac-man"},
        {"name": "Stardew Valley", "url": "https://www.stardewvalley.net/"},
        {"name": "Nier: Automata", "url": "https://nierautomata.square-enix-games.com/"},
        {"name": "Final Fantasy Tactics", "url": "https://www.square-enix-games.com/en_US/games/final-fantasy-tactics"},
        {"name": "Titanfall 2", "url": "https://www.ea.com/games/titanfall/titanfall-2"},
        {"name": "Metal Gear Solid 4: Guns of the Patriots", "url": "https://www.konami.com/mg/mgs4/"},
        {"name": "UFO: Enemy Unknown", "url": "https://en.wikipedia.org/wiki/UFO:_Enemy_Unknown"},
        {"name": "Beyond Good & Evil", "url": "https://www.ubisoft.com/game/beyond-good-and-evil"},
        {"name": "Contra", "url": "https://www.konami.com/games/contra/"},
        {"name": "Banjo-Kazooie", "url": "https://www.nintendo.com/games/detail/banjo-kazooie/"},
        {"name": "Donkey Kong Country", "url": "https://www.nintendo.com/games/detail/donkey-kong-country/"},
        {"name": "Burnout 3: Takedown", "url": "https://en.wikipedia.org/wiki/Burnout_3:_Takedown"},
        {"name": "SoulCalibur", "url": "https://en.wikipedia.org/wiki/Soulcalibur"},
        {"name": "BioShock Infinite", "url": "https://bioshockgame.com/"},
        {"name": "Limbo", "url": "https://playdead.com/games/limbo/"},
        {"name": "Advance Wars", "url": "https://www.nintendo.com/games/detail/advance-wars/"},
        {"name": "Inside", "url": "https://playdead.com/games/inside/"},
        {"name": "Fallout: New Vegas", "url": "https://fallout.bethesda.net/en/games/fallout-new-vegas"},
        {"name": "Shenmue", "url": "https://www.sega.com/games/shenmue"},
        {"name": "The Legend of Zelda: Link's Awakening", "url": "https://www.zelda.com/links-awakening/"},
        {"name": "Metroid", "url": "https://www.nintendo.com/games/detail/metroid/"},
        {"name": "Wolfenstein 3D", "url": "https://bethesda.net/en/game/wolfenstein"},
        {"name": "Spelunky", "url": "https://spelunkyworld.com/"},
        {"name": "League of Legends", "url": "https://www.leagueoflegends.com/"},
        {"name": "Psychonauts", "url": "https://www.doublefine.com/games/psychonauts"},
        {"name": "Myst", "url": "https://cyan.com/games/myst/"},
        {"name": "Left 4 Dead", "url": "https://www.valvesoftware.com/en/"},
        {"name": "Dragon Age: Origins", "url": "https://www.ea.com/games/dragon-age/dragon-age-origins"},
        {"name": "Sid Meier's Civilization V", "url": "https://civilization.com/"},
        {"name": "Dance Dance Revolution", "url": "https://en.wikipedia.org/wiki/Dance_Dance_Revolution"},
        {"name": "Guitar Hero", "url": "https://en.wikipedia.org/wiki/Guitar_Hero"},
        {"name": "Super Meat Boy", "url": "https://www.supermeatboy.com/"},
        {"name": "Age of Empires II: The Age of Kings", "url": "https://www.ageofempires.com/games/aoeii/"},
        {"name": "Super Mario RPG: Legend of the Seven Stars", "url": "https://www.nintendo.com/games/detail/super-mario-rpg-legend-of-the-seven-stars/"},
        {"name": "Maniac Mansion: Day of the Tentacle", "url": "https://www.lucasarts.com/games/day-of-the-tentacle/"},
        {"name": "Diablo", "url": "https://diablo.blizzard.com/"},
        {"name": "Tekken 3", "url": "https://www.bandainamcoent.com/games/tekken"},
        {"name": "Super Smash Bros. Brawl", "url": "https://www.nintendo.com/games/detail/super-smash-bros-brawl/"},
        {"name": "Sid Meier's Civilization II", "url": "https://civilization.com/"},
        {"name": "Star Wars: TIE Fighter", "url": "https://www.starwars.com/games-apps/star-wars-tie-fighter"},
        {"name": "Resident Evil 7: Biohazard", "url": "https://www.residentevil.com/re7/"},
        {"name": "Final Fantasy IX", "url": "https://www.square-enix-games.com/games/final-fantasy-ix"},
        {"name": "Bayonetta 2", "url": "https://www.nintendo.com/games/detail/bayonetta-2/"},
        {"name": "Persona 5", "url": "https://atlus.com/persona5/"},
        {"name": "Star Fox 64", "url": "https://www.nintendo.com/games/detail/star-fox-64/"},
        {"name": "Rock Band", "url": "https://www.harmonixmusic.com/games/rock-band/"},
        {"name": "Xenoblade Chronicles", "url": "https://www.nintendo.com/games/detail/xenoblade-chronicles/"},
        {"name": "Gran Turismo", "url": "https://www.gran-turismo.com/"},
        {"name": "Far Cry 3", "url": "https://www.ubisoft.com/game/far-cry-3"},
        {"name": "Alien: Isolation", "url": "https://www.alienisolation.com/"},
        {"name": "Fortnite", "url": "https://www.fortnite.com/"},
        {"name": "Dishonored", "url": "https://bethesda.net/en/game/dishonored"},
        {"name": "Dune II", "url": "https://en.wikipedia.org/wiki/Dune_II"},
        {"name": "Pokemon Gold/Silver", "url": "https://www.pokemon.com/us/"},
        {"name": "Eternal Darkness: Sanity's Requiem", "url": "https://www.nintendo.com/games/detail/eternal-darkness-sanitys-requiem/"},
        {"name": "Celeste", "url": "https://www.celestegame.com/"},
        {"name": "Fallout", "url": "https://fallout.bethesda.net/"},
        {"name": "Lemmings", "url": "https://www.lemmingsgame.com/"},
        {"name": "Duke Nukem 3D", "url": "https://www.3drealms.com/duke3d/"},
        {"name": "SimCity 2000", "url": "https://en.wikipedia.org/wiki/SimCity_2000"},
        {"name": "Warcraft III: Reign of Chaos", "url": "https://worldofwarcraft.com/"},
        {"name": "Katamari Damacy", "url": "https://www.bandainamcoent.com/games/katamari"},
        {"name": "XCOM: Enemy Unknown", "url": "https://xcom.com/"},
        {"name": "LittleBigPlanet", "url": "https://www.playstation.com/en-us/games/littlebigplanet/"},
        {"name": "Perfect Dark", "url": "https://en.wikipedia.org/wiki/Perfect_Dark"},
        {"name": "Streets of Rage II", "url": "https://www.sega.com/games/streets-of-rage"},
        {"name": "Diablo III", "url": "https://diablo3.blizzard.com/"},
        {"name": "Street Fighter IV", "url": "https://www.capcom.com/street-fighter/"},
        {"name": "Final Fantasy IV", "url": "https://www.square-enix-games.com/games/final-fantasy-iv"},
        {"name": "Zork I", "url": "https://en.wikipedia.org/wiki/Zork"},
        {"name": "Bayonetta", "url": "https://www.nintendo.com/games/detail/bayonetta/"},
        {"name": "Elite", "url": "https://en.wikipedia.org/wiki/Elite_(video_game)"},
        {"name": "Undertale", "url": "https://undertale.com/"},
        {"name": "God of War II", "url": "https://www.playstation.com/en-us/games/god-of-war-ii/"},
        {"name": "Quake III Arena", "url": "https://bethesda.net/en/game/quake"},
        {"name": "Mass Effect 3", "url": "https://www.ea.com/games/mass-effect/mass-effect-3"},
        {"name": "Final Fantasy XII", "url": "https://www.square-enix-games.com/games/final-fantasy-xii"},
        {"name": "Left 4 Dead 2", "url": "https://www.valvesoftware.com/en/"},
        {"name": "Soul Calibur II", "url": "https://en.wikipedia.org/wiki/Soulcalibur_II"},
        {"name": "Unreal Tournament", "url": "https://en.wikipedia.org/wiki/Unreal_Tournament"},
        {"name": "Spider-Man (2018)", "url": "https://www.playstation.com/en-us/games/marvels-spider-man/"},
        {"name": "Mortal Kombat II", "url": "https://www.mortalkombat.com/"},
        {"name": "Shovel Knight", "url": "https://yachtclubgames.com/shovel-knight/"},
        {"name": "Kingdom Hearts", "url": "https://www.kingdomhearts.com/"},
        {"name": "Fallout 4", "url": "https://fallout.bethesda.net/en/games/fallout-4"},
        {"name": "Super Smash Bros.", "url": "https://www.nintendo.com/games/detail/super-smash-bros/"},
        {"name": "Super Smash Bros. Ultimate", "url": "https://www.smashbros.com/"},
        {"name": "Eve Online", "url": "https://www.eveonline.com/"},
        {"name": "Mortal Kombat", "url": "https://www.mortalkombat.com/"},
        {"name": "Hotline Miami", "url": "https://store.steampowered.com/app/219150/Hotline_Miami/"},
        {"name": "God of War III", "url": "https://www.playstation.com/en-us/games/god-of-war-iii/"},
        {"name": "Burnout Paradise", "url": "https://www.ea.com/games/burnout/burnout-paradise"},
        {"name": "Deus Ex: Human Revolution", "url": "https://www.eidosmontreal.com/games/deus-ex-human-revolution"},
        {"name": "Rock Band 3", "url": "https://en.wikipedia.org/wiki/Rock_Band_3"},
        {"name": "F-Zero GX", "url": "https://www.nintendo.com/games/detail/f-zero-gx/"},
        {"name": "Dishonored 2", "url": "https://bethesda.net/en/game/dishonored2"},
        {"name": "Ultima IV: Quest of the Avatar", "url": "https://en.wikipedia.org/wiki/Ultima_IV:_Quest_of_the_Avatar"},
        {"name": "Rayman Legends", "url": "https://www.ubisoft.com/game/rayman-legends"},
        {"name": "Paper Mario: The Thousand-Year Door", "url": "https://www.nintendo.com/games/detail/paper-mario-the-thousand-year-door/"},
        {"name": "Gran Turismo 3: A-Spec", "url": "https://www.gran-turismo.com/"},
        {"name": "Rez", "url": "https://en.wikipedia.org/wiki/Rez_(video_game)"},
        {"name": "FTL: Faster Than Light", "url": "https://subsetgames.com/ftl.html"},
        {"name": "Monkey Island 2: LeChuck's Revenge", "url": "https://www.lucasarts.com/games/monkeyisland/"},
        {"name": "Company of Heroes", "url": "https://www.companyofheroes.com/"},
        {"name": "Battlefield 1942", "url": "https://www.ea.com/games/battlefield/battlefield-1942"},
        {"name": "DOTA 2", "url": "https://www.dota2.com/"},
        {"name": "Cuphead", "url": "https://www.studiomdhr.com/"},
        {"name": "Monster Hunter: World", "url": "https://www.monsterhunter.com/world/"},
        {"name": "Warcraft II: Tides of Darkness", "url": "https://en.wikipedia.org/wiki/Warcraft_II:_Tides_of_Darkness"},
        {"name": "XCOM 2", "url": "https://xcom.com/"},
        {"name": "Fallout 2", "url": "https://fallout.bethesda.net/"},
        {"name": "Animal Crossing", "url": "https://www.nintendo.com/games/detail/animal-crossing/"},
        {"name": "Tomb Raider (2013)", "url": "https://tombraider.square-enix-games.com/"},
        {"name": "Skies of Arcadia", "url": "https://en.wikipedia.org/wiki/Skies_of_Arcadia"},
        {"name": "Final Fantasy", "url": "https://www.square-enix-games.com/en_US/games/final-fantasy"},
        {"name": "Gone Home", "url": "https://gonehome.game/"},
        {"name": "Destiny 2", "url": "https://www.bungie.net/7/en/Destiny"},
        {"name": "Super Mario Sunshine", "url": "https://www.nintendo.com/games/detail/super-mario-sunshine/"},
        {"name": "Asteroids", "url": "https://en.wikipedia.org/wiki/Asteroids_(video_game)"},
        {"name": "Heavy Rain", "url": "https://www.quanticdream.com/en/heavy-rain"},
        {"name": "Divinity: Original Sin 2", "url": "https://divinity.game/"},
        {"name": "Tom Clancy's Splinter Cell: Chaos Theory", "url": "https://www.ubisoft.com/game/splinter-cell-chaos-theory"},
        {"name": "Prince of Persia", "url": "https://www.ubisoft.com/game/prince-of-persia"},
        {"name": "Double Dragon", "url": "https://www.arcade-museum.com/game_detail.php?game_id=7621"},
        {"name": "R-Type", "url": "https://en.wikipedia.org/wiki/R-Type"},
        {"name": "Hearthstone", "url": "https://playhearthstone.com/"},
        {"name": "What Remains of Edith Finch", "url": "https://www.giantsparrow.com/games/edithfinch/"},
        {"name": "Tony Hawk's Pro Skater", "url": "https://www.tonyhawkthegame.com/"},
        {"name": "The Legend of Zelda: Skyward Sword", "url": "https://www.zelda.com/skyward-sword/"},
        {"name": "Kingdom Hearts II", "url": "https://www.kingdomhearts.com/"},
        {"name": "Borderlands 2", "url": "https://borderlands.com/"},
        {"name": "Suikoden II", "url": "https://en.wikipedia.org/wiki/Suikoden_II"},
        {"name": "Silent Hill", "url": "https://www.konami.com/games/silenthill/"},
        {"name": "Gauntlet", "url": "https://en.wikipedia.org/wiki/Gauntlet_(1985_video_game)"},
        {"name": "Fez", "url": "https://fezgame.com/"},
        {"name": "Demon's Souls", "url": "https://www.playstation.com/en-us/games/demons-souls/"},
        {"name": "Battlefield 2", "url": "https://www.ea.com/games/battlefield/battlefield-2"},
        {"name": "Resident Evil 2", "url": "https://www.residentevil.com/re2/"},
        {"name": "Mirror's Edge", "url": "https://www.ea.com/games/mirrors-edge"},
        {"name": "PlayerUnknown's Battlegrounds", "url": "https://pubg.com/"},
        {"name": "Sid Meier's Pirates", "url": "https://en.wikipedia.org/wiki/Sid_Meier%27s_Pirates!"},
        {"name": "Animal Crossing: New Leaf", "url": "https://www.nintendo.com/games/detail/animal-crossing-new-leaf/"},
        {"name": "The Witcher 2: Assassins of Kings", "url": "https://thewitcher.com/en/witcher2"},
        {"name": "Splatoon 2", "url": "https://www.nintendo.com/games/detail/splatoon-2-switch/"},
        {"name": "Super Mario Bros. 2", "url": "https://www.nintendo.com/games/detail/super-mario-bros-2/"},
        {"name": "Counter-Strike: Global Offensive", "url": "https://blog.counter-strike.net/"},
        {"name": "OutRun", "url": "https://en.wikipedia.org/wiki/Out_Run"},
        {"name": "Galaga", "url": "https://www.bandainamcoent.com/games/galaga"},
        {"name": "Everquest", "url": "https://www.everquest.com/"},
        {"name": "Hollow Knight", "url": "https://hollowknight.com/"},
        {"name": "Jet Set Radio", "url": "https://www.sega.com/games/jet-set-radio"},
        {"name": "Contra III: The Alien Wars", "url": "https://www.nintendo.com/games/detail/contra-iii-the-alien-wars/"},
        {"name": "Baldur's Gate", "url": "https://baldursgate.com/"},
        {"name": "Castlevania", "url": "https://www.konami.com/games/castlevania/"},
        {"name": "Bubble Bobble", "url": "https://www.taito.com/games/bubble-bobble"},
        {"name": "Mario + Rabbids Kingdom Battle", "url": "https://www.nintendo.com/games/detail/mario-plus-rabbids-kingdom-battle-switch/"},
        {"name": "Fire Emblem: Awakening", "url": "https://www.nintendo.com/games/detail/fire-emblem-awakening-3ds/"},
        {"name": "Thief II: The Metal Age", "url": "https://www.gog.com/game/thief_2_the_metal_age"},
        {"name": "Life Is Strange", "url": "https://lifeisstrange.square-enix-games.com/"},
        {"name": "Metroid Prime 3: Corruption", "url": "https://www.nintendo.com/games/detail/metroid-prime-3-corruption/"},
        {"name": "Devil May Cry", "url": "https://www.capcom.com/devil-may-cry/"},
        {"name": "Ikaruga", "url": "https://www.nintendo.com/games/detail/ikaruga-switch/"},
        {"name": "Alone in the Dark", "url": "https://www.atarilife.com/games/alone-in-the-dark"},
        {"name": "Assassin's Creed Odyssey", "url": "https://www.ubisoft.com/game/assassins-creed-odyssey"},
        {"name": "Forza Horizon 3", "url": "https://www.xbox.com/en-US/games/forza-horizon-3"},
        {"name": "Street Fighter III: Third Strike", "url": "https://www.capcom.com/street-fighter/"},
        {"name": "Final Fantasy VIII", "url": "https://www.square-enix-games.com/games/final-fantasy-viii"},
        {"name": "Dragon Quest", "url": "https://www.square-enix-games.com/games/dragonquest"},
        {"name": "Rome: Total War", "url": "https://www.totalwar.com/games/rome/"},
        {"name": "Crash Bandicoot: Warped", "url": "https://www.crashbandicoot.com/"},
        {"name": "Mega Man X", "url": "https://www.capcom.com/megamanx/"},
        {"name": "Conker's Bad Fur Day", "url": "https://www.nintendo.com/games/detail/conkers-bad-fur-day/"},
        {"name": "Robotron: 2084", "url": "https://en.wikipedia.org/wiki/Robotron:_2084"},
        {"name": "Ultima Online", "url": "https://uo.com/"},
        {"name": "Uncharted 3: Drake's Deception", "url": "https://www.playstation.com/en-us/games/uncharted-3-drakes-deception/"},
        {"name": "Phantasy Star Online", "url": "https://www.sega.com/games/phantasy-star-online"},
        {"name": "Destiny", "url": "https://www.bungie.net/7/en/Destiny"},
        {"name": "Max Payne", "url": "https://www.rockstargames.com/games/maxpayne"},
        {"name": "PaRappa the Rapper", "url": "https://www.playstation.com/en-us/games/parappa-the-rapper/"},
        {"name": "Dragon Quest VIII: Journey of the Cursed King", "url": "https://www.square-enix-games.com/games/dragon-quest-viii"},
        {"name": "Splatoon", "url": "https://www.nintendo.com/games/detail/splatoon-wii-u/"},
        {"name": "Assassin's Creed IV: Black Flag", "url": "https://www.ubisoft.com/game/assassins-creed-iv-black-flag"},
        {"name": "The Witness", "url": "https://the-witness.net/"},
        {"name": "Crazy Taxi", "url": "https://www.sega.com/games/crazy-taxi"},
        {"name": "Marvel vs. Capcom 2: New Age of Heroes", "url": "https://www.capcom.com/marvel-vs-capcom-2/"},
        {"name": "Outer Wilds", "url": "https://www.mobiusdigitalgames.com/outer-wilds.html"},
        {"name": "Homeworld", "url": "https://www.gearboxsoftware.com/homeworld/"},
        {"name": "Super Mario 3D World", "url": "https://www.nintendo.com/games/detail/super-mario-3d-world-bowsers-fury-switch/"},
        {"name": "Dead Cells", "url": "https://dead-cells.com/"},
        {"name": "Gears of War 2", "url": "https://www.gearsofwar.com/"},
        {"name": "Crash Bandicoot", "url": "https://www.crashbandicoot.com/"},
        {"name": "Rise of the Tomb Raider", "url": "https://tombraider.square-enix-games.com/"},
        {"name": "Ori and the Blind Forest", "url": "https://www.orithegame.com/"},
        {"name": "Viewtiful Joe", "url": "https://www.capcom.com/viewtiful-joe/"},
        {"name": "Ninja Gaiden", "url": "https://www.tecmokoei.com/ninja-gaiden/"},
        {"name": "Star Fox", "url": "https://www.nintendo.com/games/detail/star-fox/"},
        {"name": "Gran Turismo 4", "url": "https://www.gran-turismo.com/"},
        {"name": "Forza Horizon 4", "url": "https://www.xbox.com/en-US/games/forza-horizon-4"},
        {"name": "Sam & Max Hit the Road", "url": "https://www.lucasarts.com/games/sam-max-hit-the-road/"},
        {"name": "Teenage Mutant Ninja Turtles: Turtles in Time", "url": "https://www.konami.com/games/tmnt/"},
        {"name": "Xenogears", "url": "https://www.square-enix-games.com/games/xenogears"},
        {"name": "DuckTales", "url": "https://www.capcom.com/ducktales/"},
        {"name": "Tecmo Super Bowl", "url": "https://en.wikipedia.org/wiki/Tecmo_Super_Bowl"},
        {"name": "M.U.L.E.", "url": "https://en.wikipedia.org/wiki/M.U.L.E."},
        {"name": "Fable II", "url": "https://www.xbox.com/en-US/games/fable-ii"},
        {"name": "Dark Souls III", "url": "https://en.bandainamcoent.eu/dark-souls/dark-souls-iii"},
        {"name": "F-Zero", "url": "https://www.nintendo.com/games/detail/f-zero/"},
        {"name": "Angry Birds", "url": "https://www.angrybirds.com/"},
        {"name": "Ultima Underworld: The Stygian Abyss", "url": "https://en.wikipedia.org/wiki/Ultima_Underworld:_The_Stygian_Abyss"},
        {"name": "Super Mario Maker", "url": "https://www.nintendo.com/games/detail/super-mario-maker/"},
        {"name": "WarioWare, Inc.: Mega MicroGames!", "url": "https://www.nintendo.com/games/detail/warioware-inc-mega-microgames/"},
        {"name": "Command & Conquer", "url": "https://www.ea.com/games/command-and-conquer"},
        {"name": "Pitfall!", "url": "https://en.wikipedia.org/wiki/Pitfall!"},
        {"name": "Devil May Cry 3", "url": "https://www.capcom.com/devil-may-cry-3/"},
        {"name": "Thief: The Dark Project", "url": "https://www.gog.com/game/thief_gold"},
        {"name": "Wolfenstein II: The New Colossus", "url": "https://bethesda.net/en/game/wolfenstein"},
        {"name": "Mario Kart DS", "url": "https://www.nintendo.com/games/detail/mario-kart-ds/"},
        {"name": "Papers, Please", "url": "https://papersplea.se/"},
        {"name": "Vampire: The Masquerade - Bloodlines", "url": "https://www.worldofdarkness.com/vampire-the-masquerade-bloodlines"},
        {"name": "Until Dawn", "url": "https://www.playstation.com/en-us/games/until-dawn/"},
        {"name": "Gunstar Heroes", "url": "https://www.sega.com/games/gunstar-heroes"},
        {"name": "Hitman: Blood Money", "url": "https://www.ioi.dk/hitman-blood-money/"},
        {"name": "Pokemon Go", "url": "https://www.pokemongo.com/"},
        {"name": "Ninja Gaiden", "url": "https://www.tecmokoei.com/ninja-gaiden/"},
        {"name": "Mario Kart Wii", "url": "https://www.nintendo.com/games/detail/mario-kart-wii/"},
        {"name": "Spacewar!", "url": "https://en.wikipedia.org/wiki/Spacewar!"},
        {"name": "Phoenix Wright: Ace Attorney", "url": "https://www.capcom.com/phoenixwright/"},
        {"name": "Doom II: Hell on Earth", "url": "https://www.bethesda.net/en/game/doom"},
        {"name": "Mario Kart: Double Dash", "url": "https://www.nintendo.com/games/detail/mario-kart-double-dash/"},
        {"name": "NHL '94", "url": "https://en.wikipedia.org/wiki/NHL_%2794"},
        {"name": "Maniac Mansion", "url": "https://www.lucasarts.com/games/maniac-mansion/"},
        {"name": "The Legend of Zelda: A Link Between Worlds", "url": "https://www.zelda.com/a-link-between-worlds"},
        {"name": "Lumines", "url": "https://en.wikipedia.org/wiki/Lumines"},
        {"name": "Shenmue II", "url": "https://www.sega.com/games/shenmue-ii"},
        {"name": "Into the Breach", "url": "https://subsetgames.com/itb.html"},
        {"name": "Alan Wake", "url": "https://www.alanwake.com/"},
        {"name": "Adventure", "url": "https://en.wikipedia.org/wiki/Adventure_(1979_video_game)"},
        {"name": "TimeSplitters 2", "url": "https://en.wikipedia.org/wiki/TimeSplitters_2"},
        {"name": "Rock Band 2", "url": "https://www.harmonixmusic.com/games/rock-band-2/"},
        {"name": "Metroid Prime 2: Echoes", "url": "https://www.nintendo.com/games/detail/metroid-prime-2-echoes/"},
        {"name": "Final Fantasy XIV: A Realm Reborn", "url": "https://na.finalfantasyxiv.com/"},
        {"name": "Bastion", "url": "https://www.supergiantgames.com/games/bastion/"},
        {"name": "Wave Race 64", "url": "https://www.nintendo.com/games/detail/wave-race-64/"},
        {"name": "Kerbal Space Program", "url": "https://www.kerbalspaceprogram.com/"},
        {"name": "Tom Clancy's Splinter Cell", "url": "https://www.ubisoft.com/game/splinter-cell"},
        {"name": "Kentucky Route Zero", "url": "https://kentuckyroutezero.com/"},
        {"name": "Tecmo Bowl", "url": "https://en.wikipedia.org/wiki/Tecmo_Bowl"},
        {"name": "The Chronicles of Riddick: Escape from Butcher Bay", "url": "https://en.wikipedia.org/wiki/The_Chronicles_of_Riddick:_Escape_from_Butcher_Bay"},
        {"name": "Amnesia: The Dark Descent", "url": "https://www.amnesiagame.com/"},
        {"name": "Earthworm Jim", "url": "https://www.interplay.com/games/earthwormjim"},
        {"name": "Command & Conquer: Red Alert", "url": "https://www.ea.com/games/command-and-conquer"},
        {"name": "Chrono Cross", "url": "https://www.square-enix-games.com/games/chrono-cross"},
        {"name": "Return of the Obra Dinn", "url": "https://obradinn.com/"},
        {"name": "Super Smash Bros. for Wii U", "url": "https://www.smashbros.com/"},
        {"name": "Super Castlevania IV", "url": "https://www.konami.com/games/castlevania/"},
        {"name": "The World Ends With You", "url": "https://www.square-enix-games.com/games/the-world-ends-with-you"},
        {"name": "Donkey Kong", "url": "https://www.nintendo.com/games/detail/donkey-kong/"},
        {"name": "Sekiro: Shadows Die Twice", "url": "https://www.sekirothegame.com/"},
        {"name": "Donkey Kong Country Returns", "url": "https://www.nintendo.com/games/detail/donkey-kong-country-returns/"},
        {"name": "Street Fighter II Turbo: Hyper Fighting", "url": "https://www.capcom.com/street-fighter/"},
        {"name": "Donkey Kong Country 2", "url": "https://www.nintendo.com/games/detail/donkey-kong-country-2/"},
        {"name": "Metroid II: Return of Samus", "url": "https://www.nintendo.com/games/detail/metroid-ii-return-of-samus/"},
        {"name": "Tom Clancy's Rainbow Six Siege", "url": "https://www.ubisoft.com/game/rainbow-six-siege"},
        {"name": "Bionic Commando", "url": "https://www.capcom.com/bionic-commando/"},
        {"name": "Tetris Effect", "url": "https://www.tetriseffect.game/"},
        {"name": "New Super Mario Bros.", "url": "https://www.nintendo.com/games/detail/new-super-mario-bros/"},
        {"name": "Pikmin 2", "url": "https://www.nintendo.com/games/detail/pikmin-2/"},
        {"name": "Donkey Kong Country: Tropical Freeze", "url": "https://www.nintendo.com/games/detail/donkey-kong-country-tropical-freeze/"},
        {"name": "The Longest Journey", "url": "https://www.funcom.com/games/the-longest-journey"},
        {"name": "Call of Duty", "url": "https://www.callofduty.com/"},
        {"name": "Defender", "url": "https://en.wikipedia.org/wiki/Defender_(1980_video_game)"},
        {"name": "Sega Rally Championship", "url": "https://en.wikipedia.org/wiki/Sega_Rally_Championship"},
        {"name": "SSX 3", "url": "https://www.ea.com/games/ssx"},
        {"name": "Golden Axe", "url": "https://www.sega.com/games/golden-axe"},
        {"name": "Hitman", "url": "https://www.ioi.dk/hitman/"},
        {"name": "Shin Megami Tensei: Persona 3", "url": "https://www.atlus.com/persona3/"},
        {"name": "Another World", "url": "https://en.wikipedia.org/wiki/Another_World_(video_game)"},
        {"name": "Halo: Reach", "url": "https://www.halowaypoint.com/"},
        {"name": "Wizardry: Proving Grounds of the Mad Overlord", "url": "https://en.wikipedia.org/wiki/Wizardry:_Proving_Grounds_of_the_Mad_Overlord"},
        {"name": "Dungeon Master", "url": "https://en.wikipedia.org/wiki/Dungeon_Master_(video_game)"},
        {"name": "Borderlands", "url": "https://borderlands.com/"},
        {"name": "The Last Guardian", "url": "https://www.playstation.com/en-us/games/the-last-guardian/"},
        {"name": "Quake II", "url": "https://bethesda.net/en/game/quake"},
        {"name": "Yakuza 0", "url": "https://yakuza.sega.com/yakuza0/"},
        {"name": "Tony Hawk's Pro Skater 3", "url": "https://www.tonyhawkthegame.com/"},
        {"name": "King's Quest", "url": "https://en.wikipedia.org/wiki/King%27s_Quest"},
        {"name": "Assassin's Creed: Brotherhood", "url": "https://www.ubisoft.com/game/assassins-creed-brotherhood"},
        {"name": "Metal Gear Solid: Peace Walker", "url": "https://www.konami.com/mg/mgs_pw/"},
        {"name": "Halo 4", "url": "https://www.halowaypoint.com/"},
        {"name": "Gran Turismo 2", "url": "https://www.gran-turismo.com/"},
        {"name": "World of Goo", "url": "https://worldofgoo.com/"},
        {"name": "Cave Story", "url": "https://www.nicalis.com/games/cavestory+"},
        {"name": "NiGHTS into Dreams...", "url": "https://www.sega.com/games/nights-into-dreams"},
        {"name": "Battlefield: Bad Company 2", "url": "https://www.ea.com/games/battlefield/battlefield-bad-company-2"},
        {"name": "Paper Mario", "url": "https://www.nintendo.com/games/detail/paper-mario/"},
        {"name": "John Madden Football", "url": "https://en.wikipedia.org/wiki/John_Madden_Football"},
        {"name": "Dragon Age: Inquisition", "url": "https://www.ea.com/games/dragon-age/dragon-age-inquisition"},
        {"name": "Control", "url": "https://controlgame.com/"},
        {"name": "ActRaiser", "url": "https://en.wikipedia.org/wiki/ActRaiser"},
        {"name": "Panzer Dragoon Saga", "url": "https://en.wikipedia.org/wiki/Panzer_Dragoon_Saga"},
        {"name": "Her Story", "url": "https://www.herstorygame.com/"},
        {"name": "Grand Theft Auto: Chinatown Wars", "url": "https://www.rockstargames.com/games/chinatownwars"},
        {"name": "Wipeout 2097", "url": "https://en.wikipedia.org/wiki/Wipeout_2097"},
        {"name": "Command & Conquer: Red Alert 2", "url": "https://www.ea.com/games/command-and-conquer"},
        {"name": "F.E.A.R.", "url": "https://www.warnerbros.com/games/fear"},
        {"name": "New Super Mario Bros. Wii", "url": "https://www.nintendo.com/games/detail/new-super-mario-bros-wii/"},
        {"name": "Mario & Luigi: Superstar Saga", "url": "https://www.nintendo.com/games/detail/mario-and-luigi-superstar-saga/"},
        {"name": "Mega Man 3", "url": "https://www.capcom.com/megaman/"},
        {"name": "Valkyria Chronicles", "url": "https://www.sega.com/games/valkyria-chronicles"},
        {"name": "Battlefield 1", "url": "https://www.ea.com/games/battlefield/battlefield-1"},
        {"name": "Phantasy Star IV: The End of the Millennium", "url": "https://www.sega.com/games/phantasy-star-iv"},
        {"name": "Wipeout", "url": "https://en.wikipedia.org/wiki/Wipeout_(video_game)"},
        {"name": "River City Ransom", "url": "https://www.nintendo.com/games/detail/river-city-ransom/"},
        {"name": "The Oregon Trail", "url": "https://en.wikipedia.org/wiki/The_Oregon_Trail_(series)"},
        {"name": "Ultima VII: The Black Gate", "url": "https://en.wikipedia.org/wiki/Ultima_VII"},
        {"name": "Sid Meier's Civilization VI", "url": "https://civilization.com/"},
        {"name": "Elite Beat Agents", "url": "https://en.wikipedia.org/wiki/Elite_Beat_Agents"},
        {"name": "Super Mario Land 2: 6 Golden Coins", "url": "https://www.nintendo.com/games/detail/super-mario-land-2/"},
        {"name": "Saints Row: The Third", "url": "https://www.saintsrow.com/games/saints-row-the-third"},
        {"name": "Guitar Hero II", "url": "https://en.wikipedia.org/wiki/Guitar_Hero_II"},
        {"name": "Tempest", "url": "https://en.wikipedia.org/wiki/Tempest_(video_game)"},
        {"name": "Firewatch", "url": "https://www.firewatchgame.com/"},
        {"name": "Geometry Wars: Retro Evolved 2", "url": "https://en.wikipedia.org/wiki/Geometry_Wars:_Retro_Evolved_2"},
        {"name": "Syndicate", "url": "https://en.wikipedia.org/wiki/Syndicate_(video_game)"},
        {"name": "Max Payne 2: The Fall of Max Payne", "url": "https://www.rockstargames.com/games/maxpayne2"},
        {"name": "The Sims 2", "url": "https://www.ea.com/games/the-sims/the-sims-2"},
        {"name": "Populous", "url": "https://en.wikipedia.org/wiki/Populous_(video_game)"},
        {"name": "Legacy of Kain: Soul Reaver", "url": "https://www.square-enix-games.com/games/legacy-of-kain"},
        {"name": "Zelda II: The Adventure of Link", "url": "https://www.nintendo.com/games/detail/zelda-ii-the-adventure-of-link/"},
        {"name": "Pole Position", "url": "https://en.wikipedia.org/wiki/Pole_Position_(video_game)"},
        {"name": "Metroid Fusion", "url": "https://www.nintendo.com/games/detail/metroid-fusion/"},
        {"name": "Vagrant Story", "url": "https://www.square-enix-games.com/games/vagrant-story"},
        {"name": "Crysis", "url": "https://www.ea.com/games/crysis/crysis"},
        {"name": "Star Wars", "url": "https://www.starwars.com/games-apps"},
        {"name": "Star Wars Rogue Squadron II: Rogue Leader", "url": "https://www.nintendo.com/games/detail/star-wars-rogue-squadron-ii-rogue-leader/"},
        {"name": "Uncharted: Drake's Fortune", "url": "https://www.playstation.com/en-us/games/uncharted-drakes-fortune/"},
        {"name": "Death Stranding", "url": "https://www.playstation.com/en-us/games/death-stranding/"},
        {"name": "Killer7", "url": "https://en.wikipedia.org/wiki/Killer7"},
        {"name": "Castlevania III: Dracula's Curse", "url": "https://www.konami.com/games/castlevania/"},
        {"name": "Sonic Mania", "url": "https://www.sega.com/games/sonic-mania"},
        {"name": "Apex Legends", "url": "https://www.ea.com/games/apex-legends"},
        {"name": "Pokemon Yellow", "url": "https://www.pokemon.com/us/"},
        {"name": "Mario Kart 7", "url": "https://www.nintendo.com/games/detail/mario-kart-7/"},
        {"name": "Final Fight", "url": "https://www.capcom.com/final-fight"},
        {"name": "Thumper", "url": "https://www.thumpermusic.com/"},
        {"name": "Middle-Earth: Shadow Of Mordor", "url": "https://www.shadowofmordor.com/"},
        {"name": "Call of Duty: Modern Warfare 2", "url": "https://www.callofduty.com/modernwarfare2"},
        {"name": "Castlevania: Aria of Sorrow", "url": "https://www.konami.com/games/castlevania/"},
        {"name": "Super Monkey Ball", "url": "https://www.sega.com/games/super-monkey-ball"},
        {"name": "Spec Ops: The Line", "url": "https://www.specopstheline.com/"},
        {"name": "Mega Man", "url": "https://www.capcom.com/megaman/"},
        {"name": "Ratchet & Clank: Up Your Arsenal", "url": "https://www.playstation.com/en-us/games/ratchet-and-clank-up-your-arsenal/"},
        {"name": "Daytona USA", "url": "https://www.sega.com/games/daytona-usa"},
        {"name": "Jak and Daxter: The Precursor Legacy", "url": "https://www.playstation.com/en-us/games/jak-and-daxter-the-precursor-legacy/"},
        {"name": "Sonic the Hedgehog 3", "url": "https://www.sega.com/games/sonic-the-hedgehog-3"},
        {"name": "Crusader Kings II", "url": "https://www.paradoxinteractive.com/games/crusader-kings-ii/about"},
        {"name": "Disco Elysium", "url": "https://discoelysium.com/"},
        {"name": "Kirby's Adventure", "url": "https://www.nintendo.com/games/detail/kirbys-adventure/"},
        {"name": "Super Punch-Out!!", "url": "https://www.nintendo.com/games/detail/super-punch-out/"},
        {"name": "Cities: Skylines", "url": "https://www.paradoxinteractive.com/games/cities-skylines/about"},
        {"name": "Hellblade: Senua's Sacrifice", "url": "https://www.hellblade.com/"},
        {"name": "Assassin's Creed Origins", "url": "https://www.ubisoft.com/game/assassins-creed-origins"},
        {"name": "Guild Wars 2", "url": "https://www.guildwars2.com/"},
        {"name": "80 Days", "url": "https://www.inklestudios.com/80days/"},
        {"name": "Threes", "url": "https://play.threesgame.com/"},
        {"name": "Resident Evil - Code: Veronica", "url": "https://www.residentevil.com/"},
        {"name": "Super Hexagon", "url": "https://superhexagon.com/"},
        {"name": "Counter-Strike: Source", "url": "https://blog.counter-strike.net/"},
        {"name": "The Legend of Zelda: The Minish Cap", "url": "https://www.nintendo.com/games/detail/the-legend-of-zelda-the-minish-cap/"},
        {"name": "Ghosts 'n Goblins", "url": "https://www.capcom.com/games/ghosts-n-goblins"},
        {"name": "Madden NFL 2005", "url": "https://www.ea.com/games/madden-nfl"},
        {"name": "Manic Miner", "url": "https://en.wikipedia.org/wiki/Manic_Miner"},
        {"name": "Pokemon Black/White", "url": "https://www.pokemon.com/us/"},
        {"name": "Super Mario 3D Land", "url": "https://www.nintendo.com/games/detail/super-mario-3d-land/"},
        {"name": "Battlefield 3", "url": "https://www.ea.com/games/battlefield/battlefield-3"},
        {"name": "Aladdin", "url": "https://www.disney.com/aladdin"},
        {"name": "Star Wars Jedi Knight: Dark Forces II", "url": "https://www.starwars.com/games-apps"},
        {"name": "ESPN NFL 2K5", "url": "https://en.wikipedia.org/wiki/ESPN_NFL_2K5"},
        {"name": "Monument Valley", "url": "https://www.monumentvalleygame.com/"},
        {"name": "LittleBigPlanet 2", "url": "https://www.playstation.com/en-us/games/littlebigplanet-2/"},
        {"name": "Final Fantasy XV", "url": "https://finalfantasyxv.square-enix-games.com/"},
        {"name": "Batman: Arkham Knight", "url": "https://www.rockstargames.com/arkhamknight"},
        {"name": "Crackdown", "url": "https://www.xbox.com/en-US/games/crackdown"},
        {"name": "Luigi's Mansion", "url": "https://www.nintendo.com/games/detail/luigis-mansion/"},
        {"name": "Indiana Jones and the Fate of Atlantis", "url": "https://www.lucasarts.com/games/indiana-jones-and-the-fate-of-atlantis/"},
        {"name": "WWF No Mercy", "url": "https://en.wikipedia.org/wiki/WWF_No_Mercy_(video_game)"},
        {"name": "Super Street Fighter IV", "url": "https://www.capcom.com/street-fighter/"},
        {"name": "Ultima I", "url": "https://en.wikipedia.org/wiki/Ultima_I:_The_First_Age_of_Darkness"},
        {"name": "Metal Gear", "url": "https://www.konami.com/mg/"},
        {"name": "Virtua Fighter 2", "url": "https://www.sega.com/games/virtua-fighter-2"},
        {"name": "Sensible World of Soccer", "url": "https://en.wikipedia.org/wiki/Sensible_World_of_Soccer"},
        {"name": "Unreal Tournament 2004", "url": "https://www.unrealtournament.com/"},
        {"name": "Killer Instinct", "url": "https://www.ultra-combo.com/"},
        {"name": "Twisted Metal 2", "url": "https://www.playstation.com/en-us/games/twisted-metal-2/"},
        {"name": "Hitman 2", "url": "https://www.ioi.dk/hitman2/"},
        {"name": "Peggle", "url": "https://www.popcap.com/games/peggle"},
        {"name": "Condemned", "url": "https://en.wikipedia.org/wiki/Condemned:_Criminal_Origins"},
        {"name": "Flashback", "url": "https://en.wikipedia.org/wiki/Flashback_(1992_video_game)"},
        {"name": "Age of Empires", "url": "https://www.ageofempires.com/"},
        {"name": "The Legend of Zelda: Phantom Hourglass", "url": "https://www.nintendo.com/games/detail/the-legend-of-zelda-phantom-hourglass/"},
        {"name": "Virtua Fighter 4", "url": "https://www.sega.com/games/virtua-fighter-4"},
        {"name": "System Shock", "url": "https://www.nightdive.com/games/system-shock"},
        {"name": "Duck Hunt", "url": "https://www.nintendo.com/games/detail/duck-hunt/"},
        {"name": "Street Fighter Alpha III", "url": "https://www.capcom.com/street-fighter/"},
        {"name": "Broken Sword: The Shadow of the Templars", "url": "https://revolution.co.uk/games/broken-sword"},
        {"name": "Tetris Attack", "url": "https://www.nintendo.com/games/detail/tetris-attack/"},
        {"name": "Missile Command", "url": "https://en.wikipedia.org/wiki/Missile_Command"},
        {"name": "Pokemon Ruby/Sapphire", "url": "https://www.pokemon.com/us/"},
        {"name": "Arms", "url": "https://www.nintendo.com/games/detail/arms-switch/"},
        {"name": "Super Mario Land", "url": "https://www.nintendo.com/games/detail/super-mario-land/"},
        {"name": "Call of Duty: Black Ops", "url": "https://www.callofduty.com/blackops"},
        {"name": "Metal Slug", "url": "https://www.snk-corp.co.jp/us/games/metalslug/"},
        {"name": "Animal Crossing: Wild World", "url": "https://www.nintendo.com/games/detail/animal-crossing-wild-world/"},
        {"name": "No Man's Sky", "url": "https://www.nomanssky.com/"},
        {"name": "Dr. Mario", "url": "https://www.nintendo.com/games/detail/dr-mario/"},
        {"name": "Star Wars: Knights of the Old Republic II", "url": "https://www.aspyr.com/games/star-wars-knights-of-the-old-republic-ii"},
        {"name": "The Sims 3", "url": "https://www.ea.com/games/the-sims/the-sims-3"},
        {"name": "Geometry Wars: Retro Evolved", "url": "https://en.wikipedia.org/wiki/Geometry_Wars"},
        {"name": "Virtua Fighter", "url": "https://www.sega.com/games/virtua-fighter"},
        {"name": "Tales of Symphonia", "url": "https://www.bandainamcoent.com/games/tales-of-symphonia"},
        {"name": "Fire Emblem", "url": "https://www.nintendo.com/games/detail/fire-emblem/"},
        {"name": "Sonic & Knuckles", "url": "https://www.sega.com/games/sonic-knuckles"},
        {"name": "WarioWare: Twisted!", "url": "https://www.nintendo.com/games/detail/warioware-twisted/"},
        {"name": "Golden Sun", "url": "https://www.nintendo.com/games/detail/golden-sun/"},
        {"name": "Pokemon X/Y", "url": "https://www.pokemon.com/us/"},
        {"name": "Mafia: The City of Lost Heaven", "url": "https://mafiagame.com/"},
        {"name": "Kid Icarus", "url": "https://www.nintendo.com/games/detail/kid-icarus/"},
        {"name": "Super Puzzle Fighter II Turbo", "url": "https://www.capcom.com/street-fighter/"},
        {"name": "FIFA 12", "url": "https://www.ea.com/games/fifa"},
        {"name": "Grand Theft Auto", "url": "https://www.rockstargames.com/games/grandtheftauto"},
        {"name": "Tekken 5", "url": "https://www.bandainamcoent.com/games/tekken"},
        {"name": "Far Cry", "url": "https://www.ubisoft.com/game/far-cry"},
        {"name": "Bully", "url": "https://www.rockstargames.com/games/bully"},
        {"name": "Far Cry 4", "url": "https://www.ubisoft.com/game/far-cry-4"},
        {"name": "Fire Emblem: Three Houses", "url": "https://www.nintendo.com/games/detail/fire-emblem-three-houses/"},
        {"name": "S.T.A.L.K.E.R.: Shadow of Chernobyl", "url": "https://www.stalker-game.com/"},
        {"name": "Wing Commander", "url": "https://en.wikipedia.org/wiki/Wing_Commander_(video_game)"},
        {"name": "Dragon's Lair", "url": "https://www.digitalleisure.com/dragons-lair/"},
        {"name": "Pokemon Sun/Moon", "url": "https://www.pokemon.com/us/"},
        {"name": "Dead Rising", "url": "https://www.capcom.com/deadrising/"},
        {"name": "Ultima III: Exodus", "url": "https://en.wikipedia.org/wiki/Ultima_III:_Exodus"},
        {"name": "L.A. Noire", "url": "https://www.rockstargames.com/lanoire"},
        {"name": "Speedball 2: Brutal Deluxe", "url": "https://en.wikipedia.org/wiki/Speedball_2:_Brutal_Deluxe"},
        {"name": "F-Zero X", "url": "https://www.nintendo.com/games/detail/f-zero-x/"},
        {"name": "Jet Set Radio Future", "url": "https://www.sega.com/games/jet-set-radio-future"},
        {"name": "Plants vs. Zombies", "url": "https://www.ea.com/games/plants-vs-zombies"},
        {"name": "The Curse of Monkey Island", "url": "https://www.lucasarts.com/games/the-curse-of-monkey-island/"},
        {"name": "Devil May Cry 5", "url": "https://www.capcom.com/devil-may-cry-5/"},
        {"name": "Pokemon: Let's Go, Pikachu! and Let's Go, Eevee!", "url": "https://www.pokemon.com/us/"},
        {"name": "Rayman 2: The Great Escape", "url": "https://www.ubisoft.com/game/rayman-2-the-great-escape"},
        {"name": "Ratchet & Clank", "url": "https://www.playstation.com/en-us/games/ratchet-and-clank/"},
        {"name": "Tomb Raider II", "url": "https://www.tombraider.com/"},
        {"name": "Star Wars: Battlefront II", "url": "https://www.ea.com/games/starwars/battlefront/battlefront-2"},
        {"name": "Pro Evolution Soccer 6", "url": "https://en.wikipedia.org/wiki/Pro_Evolution_Soccer_6"},
        {"name": "The Legend of Zelda: Oracle of Seasons/Ages", "url": "https://www.nintendo.com/games/detail/the-legend-of-zelda-oracle-of-seasons-ages/"},
        {"name": "Castle Crashers", "url": "https://www.thebehemoth.com/games/castle-crashers/"},
        {"name": "Freespace 2", "url": "https://www.gog.com/game/freespace_2"},
        {"name": "Pikmin", "url": "https://www.nintendo.com/games/detail/pikmin/"},
        {"name": "Prey", "url": "https://bethesda.net/en/game/prey"},
        {"name": "Star Control II", "url": "https://en.wikipedia.org/wiki/Star_Control_II"},
        {"name": "Gears of War 4", "url": "https://www.gearsofwar.com/"},
        {"name": "Sid Meier's Civilization III", "url": "https://civilization.com/"},
        {"name": "Super Hot", "url": "https://superhotgame.com/"},
        {"name": "Shining Force II", "url": "https://www.sega.com/games/shining-force-ii"},
        {"name": "Fable", "url": "https://www.xbox.com/en-US/games/fable"},
        {"name": "Halo 5: Guardians", "url": "https://www.halowaypoint.com/"},
        {"name": "Manhunt", "url": "https://www.rockstargames.com/games/manhunt"},
        {"name": "Battletoads", "url": "https://www.xbox.com/en-US/games/battletoads"},
        {"name": "Ridge Racer", "url": "https://www.bandainamcoent.com/games/ridge-racer"},
        {"name": "Night in the Woods", "url": "https://www.nightinthewoods.com/"},
        {"name": "Metal Gear Solid: The Twin Snakes", "url": "https://www.konami.com/mg/"},
        {"name": "Pikmin 3", "url": "https://www.nintendo.com/games/detail/pikmin-3/"},
        {"name": "Divinity: Original Sin", "url": "https://divinity.game/"},
        {"name": "Fatal Frame II: Crimson Butterfly", "url": "https://www.koeitecmoamerica.com/fatalframe/"},
        {"name": "Uncharted: The Lost Legacy", "url": "https://www.playstation.com/en-us/games/uncharted-the-lost-legacy/"},
        {"name": "Herzog Zwei", "url": "https://en.wikipedia.org/wiki/Herzog_Zwei"},
        {"name": "Bulletstorm", "url": "https://www.peoplecanfly.com/bulletstorm/"},
        {"name": "Injustice 2", "url": "https://www.injustice.com/"},
        {"name": "Battlezone", "url": "https://en.wikipedia.org/wiki/Battlezone_(1980_video_game)"},
        {"name": "Excitebike", "url": "https://www.nintendo.com/games/detail/excitebike/"},
        {"name": "Disgaea: Hour of Darkness", "url": "https://www.nisamerica.com/games/disgaea/"},
        {"name": "Superbrothers: Sword & Sworcery EP", "url": "https://www.swordandsworcery.com/"},
        {"name": "Guardian Heroes", "url": "https://en.wikipedia.org/wiki/Guardian_Heroes"},
        {"name": "Sea of Thieves", "url": "https://www.seaofthieves.com/"},
        {"name": "Wii Sports Resort", "url": "https://www.nintendo.com/games/detail/wii-sports-resort/"},
        {"name": "Spyro the Dragon", "url": "https://www.spyrothedragon.com/"},
        {"name": "New Super Mario Bros. U", "url": "https://www.nintendo.com/games/detail/new-super-mario-bros-u/"},
        {"name": "Dead Space 2", "url": "https://www.ea.com/games/dead-space/dead-space-2"},
        {"name": "Full Throttle", "url": "https://www.lucasarts.com/games/full-throttle/"},
        {"name": "Virtua Tennis", "url": "https://www.sega.com/games/virtua-tennis"},
        {"name": "Gabriel Knight: Sins of the Fathers", "url": "https://www.sierra.com/games/gabriel-knight/"},
        {"name": "Flower", "url": "https://thatgamecompany.com/flower/"},
        {"name": "Dragon Quest III", "url": "https://www.square-enix-games.com/games/dragonquest"},
        {"name": "Final Fantasy Tactics Advance", "url": "https://www.square-enix-games.com/games/final-fantasy-tactics"},
        {"name": "Xenoblade Chronicles 2", "url": "https://www.nintendo.com/games/detail/xenoblade-chronicles-2/"},
        {"name": "Super Bomberman", "url": "https://www.konami.com/games/bomberman/"},
        {"name": "MechWarrior 2: 31st Century Combat", "url": "https://en.wikipedia.org/wiki/MechWarrior_2:_31st_Century_Combat"},
        {"name": "Golf Story", "url": "https://www.sidetwelve.com/golfstory/"},
        {"name": "Diddy Kong Racing", "url": "https://www.nintendo.com/games/detail/diddy-kong-racing/"},
        {"name": "Dark Souls II", "url": "https://en.bandainamcoent.eu/dark-souls/dark-souls-ii"},
        {"name": "Infamous 2", "url": "https://www.playstation.com/en-us/games/infamous-2/"},
        {"name": "Metroid Zero Mission", "url": "https://www.nintendo.com/games/detail/metroid-zero-mission/"},
        {"name": "Worms", "url": "https://www.team17.com/games/worms/"},
        {"name": "Enslaved: Odyssey to the West", "url": "https://en.wikipedia.org/wiki/Enslaved:_Odyssey_to_the_West"},
        {"name": "Darkest Dungeon", "url": "https://www.darkestdungeon.com/"},
        {"name": "Sonic CD", "url": "https://www.sega.com/games/sonic-cd"},
        {"name": "Pokemon HeartGold/SoulSilver", "url": "https://www.pokemon.com/us/"},
        {"name": "Jade Empire", "url": "https://www.bioware.com/games/jade-empire"},
        {"name": "Dragon Quest IV: Chapters of the Chosen", "url": "https://www.square-enix-games.com/games/dragonquest"},
        {"name": "Comix Zone", "url": "https://www.sega.com/games/comix-zone"},
        {"name": "Mario Tennis", "url": "https://www.nintendo.com/games/detail/mario-tennis/"},
        {"name": "Far Cry 2", "url": "https://www.ubisoft.com/game/far-cry-2"},
        {"name": "Black & White", "url": "https://en.wikipedia.org/wiki/Black_%26_White_(video_game)"},
        {"name": "Worms Armageddon", "url": "https://www.team17.com/games/worms-armageddon/"},
        {"name": "Total War: Shogun 2", "url": "https://www.totalwar.com/games/shogun-2/"},
        {"name": "Sunset Overdrive", "url": "https://insomniac.games/game/sunset-overdrive/"},
        {"name": "Captain Toad: Treasure Tracker", "url": "https://www.nintendo.com/games/detail/captain-toad-treasure-tracker/"},
        {"name": "Monster Hunter 4 Ultimate", "url": "https://www.monsterhunter.com/"},
        {"name": "After Burner", "url": "https://en.wikipedia.org/wiki/After_Burner"},
        {"name": "Castlevania: Dawn of Sorrow", "url": "https://www.konami.com/games/castlevania/"},
        {"name": "Boulder Dash", "url": "https://www.firststarsoftware.com/boulderdash.htm"},
        {"name": "Vanquish", "url": "https://www.platinumgames.com/games/vanquish"},
        {"name": "Mark of the Ninja", "url": "https://www.kleientertainment.com/mark-of-the-ninja"},
        {"name": "Archon", "url": "https://en.wikipedia.org/wiki/Archon_(video_game)"},
        {"name": "Wolfenstein: The New Order", "url": "https://bethesda.net/en/game/wolfenstein"},
        {"name": "Ape Escape", "url": "https://www.playstation.com/en-us/games/ape-escape/"},
        {"name": "Frogger", "url": "https://www.konami.com/games/frogger/"},
        {"name": "God of War: Chains of Olympus", "url": "https://www.playstation.com/en-us/games/god-of-war-chains-of-olympus/"},
        {"name": "Forza Motorsport 4", "url": "https://www.xbox.com/en-US/games/forza-motorsport-4"},
        {"name": "Phantasy Star", "url": "https://www.sega.com/games/phantasy-star"},
        {"name": "Neverwinter Nights", "url": "https://www.beamdog.com/games/neverwinter-nights/"},
        {"name": "Slaves to Armok II: Dwarf Fortress", "url": "http://www.bay12games.com/dwarves/"},
        {"name": "Dragon Ball FighterZ", "url": "https://www.bandainamcoent.com/games/dragon-ball-fighterz"},
        {"name": "Radiant Silvergun", "url": "https://en.wikipedia.org/wiki/Radiant_Silvergun"},
        {"name": "Medal of Honor", "url": "https://www.ea.com/games/medal-of-honor"},
        {"name": "Strider", "url": "https://www.capcom.com/strider/"},
        {"name": "999: 9 Hours, 9 Persons, 9 Doors", "url": "https://www.spike-chunsoft.com/games/999/"},
        {"name": "Wasteland", "url": "https://www.inxile-entertainment.com/wasteland"},
        {"name": "Ghost Trick: Phantom Detective", "url": "https://www.capcom.com/games/ghost-trick"},
        {"name": "Saturn Bomberman", "url": "https://www.konami.com/games/bomberman/"},
        {"name": "Sonic Adventure", "url": "https://www.sega.com/games/sonic-adventure"},
        {"name": "Slay the Spire", "url": "https://www.megacrit.com/"},
        {"name": "Baseball Stars", "url": "https://en.wikipedia.org/wiki/Baseball_Stars"},
        {"name": "Dying Light", "url": "https://dyinglightgame.com/"},
        {"name": "Power Stone 2", "url": "https://www.capcom.com/games/power-stone"},
        {"name": "Outlast", "url": "https://redbarrelsgames.com/games/outlast/"},
        {"name": "Bejeweled", "url": "https://www.popcap.com/games/bejeweled"},
        {"name": "Madden NFL 2004", "url": "https://www.ea.com/games/madden-nfl"},
        {"name": "Professor Layton and the Curious Village", "url": "https://www.nintendo.com/games/detail/professor-layton-and-the-curious-village/"},
        {"name": "Rainbow Islands", "url": "https://en.wikipedia.org/wiki/Rainbow_Islands:_The_Story_of_Bubble_Bobble_2"},
        {"name": "Donkey Kong Jungle Beat", "url": "https://www.nintendo.com/games/detail/donkey-kong-jungle-beat/"},
        {"name": "Pokemon Diamond and Pearl", "url": "https://www.pokemon.com/us/"},
        {"name": "Ridiculous Fishing", "url": "https://www.vlambeer.com/games/ridiculous-fishing/"},
        {"name": "King's Quest VI: Heir Today, Gone Tomorrow", "url": "https://www.sierra.com/games/kings-quest/"},
        {"name": "Starsiege: Tribes", "url": "https://en.wikipedia.org/wiki/Starsiege:_Tribes"},
        {"name": "Ratchet & Clank: A Crack in Time", "url": "https://www.playstation.com/en-us/games/ratchet-clank-a-crack-in-time/"},
        {"name": "The Stanley Parable", "url": "https://www.stanleyparable.com/"},
        {"name": "Pro Evolution Soccer 3", "url": "https://en.wikipedia.org/wiki/Pro_Evolution_Soccer_3"},
        {"name": "Sensible Soccer", "url": "https://en.wikipedia.org/wiki/Sensible_Soccer"},
        {"name": "Centipede", "url": "https://en.wikipedia.org/wiki/Centipede_(video_game)"},
        {"name": "Puyo Puyo Tetris", "url": "https://puyonexus.com/"},
        {"name": "1080 Snowboarding", "url": "https://www.nintendo.com/games/detail/1080-snowboarding/"},
        {"name": "Shadow Complex", "url": "https://store.epicgames.com/en-US/p/shadow-complex-remastered"},
        {"name": "Animal Crossing: New Horizons", "url": "https://www.nintendo.com/games/detail/animal-crossing-new-horizons/"},
        {"name": "SOMA", "url": "https://frictionalgames.com/soma/"},
        {"name": "Sonic Adventure 2", "url": "https://www.sega.com/games/sonic-adventure-2"},
        {"name": "Elite: Dangerous", "url": "https://www.elitedangerous.com/"},
        {"name": "Killzone 2", "url": "https://www.playstation.com/en-us/games/killzone-2/"},
        {"name": "Samurai Shodown II", "url": "https://www.snk-corp.co.jp/us/games/samurai-shodown/"},
        {"name": "Super Paper Mario", "url": "https://www.nintendo.com/games/detail/super-paper-mario/"},
        {"name": "Ys Book I & II", "url": "https://www.konami.com/games/ys/"},
        {"name": "The Operative: No One Lives Forever", "url": "https://en.wikipedia.org/wiki/The_Operative:_No_One_Lives_Forever"},
        {"name": "Mother 3", "url": "https://www.nintendo.com/games/detail/mother-3/"},
        {"name": "Thief: Deadly Shadows", "url": "https://www.gog.com/game/thief_deadly_shadows"},
        {"name": "Oddworld: Stranger's Wrath", "url": "https://www.oddworld.com/"},
        {"name": "Marble Madness", "url": "https://en.wikipedia.org/wiki/Marble_Madness"},
        {"name": "Hades", "url": "https://www.supergiantgames.com/games/hades/"},
        {"name": "Tron", "url": "https://en.wikipedia.org/wiki/Tron_(video_game)"},
        {"name": "South Park: The Stick of Truth", "url": "https://www.ubisoft.com/game/south-park-the-stick-of-truth"},
        {"name": "Snipperclips", "url": "https://www.nintendo.com/games/detail/snipperclips-switch/"},
        {"name": "LEGO Star Wars", "url": "https://www.lego.com/en-us/themes/star-wars/games"},
        {"name": "Super Smash Bros For 3DS", "url": "https://www.nintendo.com/games/detail/super-smash-bros-for-nintendo-3ds/"},
        {"name": "Octopath Traveler", "url": "https://octopathtraveler.square-enix-games.com/"},
        {"name": "Super Mario All-Stars", "url": "https://www.nintendo.com/games/detail/super-mario-all-stars/"},
        {"name": "Impossible Mission", "url": "https://en.wikipedia.org/wiki/Impossible_Mission"},
        {"name": "Warhammer 40,000: Dawn of War", "url": "https://www.dawnofwar.com/"},
        {"name": "Call of Duty 2", "url": "https://www.callofduty.com/"},
        {"name": "Puzzle Bobble", "url": "https://www.taito.com/games/puzzle-bobble"},
        {"name": "Joust", "url": "https://en.wikipedia.org/wiki/Joust_(video_game)"},
        {"name": "Final Fantasy III", "url": "https://www.square-enix-games.com/games/final-fantasy-iii"},
        {"name": "Subnautica", "url": "https://unknownworlds.com/subnautica/"},
        {"name": "Dungeon Keeper", "url": "https://www.ea.com/games/dungeon-keeper"},
        {"name": "Virtua Racing", "url": "https://www.sega.com/games/virtua-racing"},
        {"name": "DayZ", "url": "https://www.bohemia.net/games/dayz"},
        {"name": "Syphon Filter", "url": "https://www.playstation.com/en-us/games/syphon-filter/"},
        {"name": "Paradroid", "url": "https://en.wikipedia.org/wiki/Paradroid"},
        {"name": "X-Men", "url": "https://en.wikipedia.org/wiki/X-Men_(1992_video_game)"},
        {"name": "The Simpsons", "url": "https://en.wikipedia.org/wiki/The_Simpsons_Arcade_Game"},
        {"name": "NBA 2K11", "url": "https://www.2k.com/games/nba-2k11/"},
        {"name": "Project Gotham Racing 2", "url": "https://en.wikipedia.org/wiki/Project_Gotham_Racing_2"},
        {"name": "NBA Street Vol. 2", "url": "https://en.wikipedia.org/wiki/NBA_Street_Vol._2"},
        {"name": "Pokemon Sword / Shield", "url": "https://www.pokemon.com/us/"},
        {"name": "Streets Of Rage", "url": "https://www.sega.com/games/streets-of-rage"},
        {"name": "Nethack", "url": "https://www.nethack.org/"},
        {"name": "Gears of War 3", "url": "https://www.gearsofwar.com/"},
        {"name": "Ni No Kuni: Wrath of the White Witch", "url": "https://www.bandainamcoent.com/games/ni-no-kuni"},
        {"name": "Pro Evolution Soccer 4", "url": "https://en.wikipedia.org/wiki/Pro_Evolution_Soccer_4"},
        {"name": "Untitled Goose Game", "url": "https://goose.game/"},
        {"name": "Donkey Kong 64", "url": "https://www.nintendo.com/games/detail/donkey-kong-64/"},
        {"name": "Tetris 99", "url": "https://www.nintendo.com/games/detail/tetris-99-switch/"},
        {"name": "Blast Corps", "url": "https://en.wikipedia.org/wiki/Blast_Corps"},
        {"name": "Dragon Quest V", "url": "https://www.square-enix-games.com/games/dragonquest"},
        {"name": "Sleeping Dogs", "url": "https://www.sleepingdogs.net/"},
        {"name": "Spy Hunter", "url": "https://en.wikipedia.org/wiki/Spy_Hunter"},
        {"name": "Pilotwings", "url": "https://www.nintendo.com/games/detail/pilotwings/"},
        {"name": "Advance Wars: Dual Strike", "url": "https://www.nintendo.com/games/detail/advance-wars-dual-strike/"},
        {"name": "The Last of Us Part II", "url": "https://www.playstation.com/en-us/games/the-last-of-us-part-ii/"},
        {"name": "Towerfall Ascension", "url": "https://www.towerfall-game.com/"},
        {"name": "Pokemon Snap", "url": "https://www.nintendo.com/games/detail/pokemon-snap/"},
        {"name": "Assassin's Creed", "url": "https://www.ubisoft.com/game/assassins-creed"},
        {"name": "Star Wars Jedi Knight II: Jedi Outcast", "url": "https://www.starwars.com/games-apps"},
        {"name": "Kirby's Dream Land", "url": "https://www.nintendo.com/games/detail/kirbys-dream-land/"},
        {"name": "Bard's Tale", "url": "https://www.inxile-entertainment.com/the-bards-tale"},
        {"name": "Florence", "url": "https://annapurna.pictures/interactive/florence"},
        {"name": "Hitman 2: Silent Assassin", "url": "https://www.ioi.dk/hitman2/"},
        {"name": "Tom Clancy's Rainbow Six", "url": "https://www.ubisoft.com/game/rainbow-six"},
        {"name": "Forza Motorsport 7", "url": "https://www.xbox.com/en-US/games/forza-motorsport-7"},
        {"name": "Dragon Quest IX: Sentinels of the Starry Skies", "url": "https://www.square-enix-games.com/games/dragonquest"},
        {"name": "Silent Hills: P.T.", "url": "https://en.wikipedia.org/wiki/P.T._(video_game)"},
        {"name": "Super Ghouls 'n Ghosts", "url": "https://www.capcom.com/games/ghouls-n-ghosts"},
        {"name": "Sid Meier's Alpha Centauri", "url": "https://en.wikipedia.org/wiki/Sid_Meier%27s_Alpha_Centauri"},
        {"name": "R.C. Pro-Am", "url": "https://en.wikipedia.org/wiki/R.C._Pro-Am"},
        {"name": "Star Wars: Rogue Squadron", "url": "https://www.nintendo.com/games/detail/star-wars-rogue-squadron/"},
        {"name": "Samurai Shodown", "url": "https://www.snk-corp.co.jp/us/games/samurai-shodown/"},
        {"name": "Rogue", "url": "https://en.wikipedia.org/wiki/Rogue_(video_game)"},
        {"name": "Need for Speed: Most Wanted", "url": "https://www.ea.com/games/need-for-speed/need-for-speed-most-wanted"},
        {"name": "The Legend of Zelda: Four Swords Adventures", "url": "https://www.nintendo.com/games/detail/the-legend-of-zelda-four-swords-adventures/"},
        {"name": "Zack & Wiki: Quest for Barbaros' Treasure", "url": "https://www.capcom.com/games/zack-wiki/"},
        {"name": "Lego Star Wars II: The Original Trilogy", "url": "https://www.lego.com/en-us/themes/star-wars/games"},
        {"name": "Wing Commander III: Heart of the Tiger", "url": "https://en.wikipedia.org/wiki/Wing_Commander_III:_Heart_of_the_Tiger"},
        {"name": "NFL Blitz", "url": "https://en.wikipedia.org/wiki/NFL_Blitz"},
        {"name": "Crash Bandicoot 2: Cortex Strikes Back", "url": "https://www.crashbandicoot.com/"},
        {"name": "Rayman Origins", "url": "https://www.ubisoft.com/game/rayman-origins"},
        {"name": "Ratchet & Clank", "url": "https://www.playstation.com/en-us/games/ratchet-and-clank/"},
        {"name": "Ultima VI: The False Prophet", "url": "https://en.wikipedia.org/wiki/Ultima_VI:_The_False_Prophet"},
        {"name": "Supreme Commander", "url": "https://www.supremecommander.com/"},
        {"name": "Punch-Out", "url": "https://www.nintendo.com/games/detail/punch-out/"},
        {"name": "Oddworld: Abe's Oddysee", "url": "https://www.oddworld.com/"},
        {"name": "Kirby's Epic Yarn", "url": "https://www.nintendo.com/games/detail/kirbys-epic-yarn/"},
        {"name": "Mario Party", "url": "https://www.nintendo.com/games/detail/mario-party/"},
        {"name": "Wario Land: Super Mario Land 3", "url": "https://www.nintendo.com/games/detail/wario-land-super-mario-land-3/"},
        {"name": "Time Crisis", "url": "https://www.bandainamcoent.com/games/time-crisis"},
        {"name": "Forza Motorsport 3", "url": "https://www.xbox.com/en-US/games/forza-motorsport-3"},
        {"name": "Drop7", "url": "https://en.wikipedia.org/wiki/Drop7"},
        {"name": "Xenoblade Chronicles X", "url": "https://www.nintendo.com/games/detail/xenoblade-chronicles-x/"},
        {"name": "Head Over Heels", "url": "https://en.wikipedia.org/wiki/Head_Over_Heels_(video_game)"},
        {"name": "Nidhogg", "url": "https://nidhogggame.com/"},
        {"name": "Monster Hunter Tri", "url": "https://www.monsterhunter.com/"},
        {"name": "The Room", "url": "https://fireproofgames.com/games/the-room"},
        {"name": "SSX Tricky", "url": "https://www.ea.com/games/ssx"},
        {"name": "Tom Clancy's Splinter Cell: Pandora Tomorrow", "url": "https://www.ubisoft.com/game/splinter-cell-pandora-tomorrow"},
        {"name": "Tempest 2000", "url": "https://en.wikipedia.org/wiki/Tempest_2000"},
        {"name": "Road Rash", "url": "https://en.wikipedia.org/wiki/Road_Rash"},
        {"name": "Alien Vs Predator", "url": "https://en.wikipedia.org/wiki/Alien_vs._Predator_(1994_video_game)"},
        {"name": "Teenage Mutant Ninja Turtles", "url": "https://www.konami.com/games/tmnt/"},
        {"name": "The House of the Dead 2", "url": "https://www.sega.com/games/house-of-the-dead-2"},
        {"name": "Master of Orion", "url": "https://www.masteroforion.com/"},
        {"name": "BioShock 2", "url": "https://bioshock.fandom.com/wiki/BioShock_2"},
        {"name": "Call of Duty: Black Ops II", "url": "https://www.callofduty.com/blackops2"},
        {"name": "Castle of Illusion Starring Mickey Mouse", "url": "https://www.disney.com/games/castle-of-illusion"},
        {"name": "Middle-Earth: Shadow of War", "url": "https://www.shadowofwar.com/"},
        {"name": "Lode Runner", "url": "https://www.loderunner.com/"},
        {"name": "IL-2 Sturmovik", "url": "https://il2sturmovik.com/"},
        {"name": "Medal of Honor: Allied Assault", "url": "https://www.ea.com/games/medal-of-honor"},
        {"name": "Castlevania: Rondo of Blood", "url": "https://www.konami.com/games/castlevania/"},
        {"name": "Blades of Steel", "url": "https://en.wikipedia.org/wiki/Blades_of_Steel"},
        {"name": "Titanfall", "url": "https://www.ea.com/games/titanfall"},
        {"name": "Arkanoid", "url": "https://www.taito.com/games/arkanoid"},
        {"name": "Frontier: Elite II", "url": "https://en.wikipedia.org/wiki/Frontier:_Elite_II"},
        {"name": "Dr. Kawashima's Brain Training", "url": "https://www.nintendo.com/games/detail/dr-kawashimas-brain-training-switch/"},
        {"name": "Tales From The Borderlands", "url": "https://borderlands.com/game/tales-from-the-borderlands/"},
        {"name": "Bomberman", "url": "https://www.konami.com/games/bomberman/"},
        {"name": "Jak II", "url": "https://www.playstation.com/en-us/games/jak-ii/"},
        {"name": "Ghouls 'n Ghosts", "url": "https://www.capcom.com/games/ghouls-n-ghosts"},
        {"name": "Deadly Premonition", "url": "https://www.deadlypremonition.com/"},
        {"name": "The Sims 4", "url": "https://www.ea.com/games/the-sims/the-sims-4"},
        {"name": "Lost Odyssey", "url": "https://en.wikipedia.org/wiki/Lost_Odyssey"},
        {"name": "Professor Layton & The Unwound Future", "url": "https://www.nintendo.com/games/detail/professor-layton-and-the-unwound-future/"},
        {"name": "Fahrenheit", "url": "https://www.quanticdream.com/en/game/fahrenheit"},
        {"name": "Total Annihilation", "url": "https://en.wikipedia.org/wiki/Total_Annihilation"},
        {"name": "Fatal Fury: Mark of the Wolves", "url": "https://www.snk-corp.co.jp/us/games/fatal-fury/"},
        {"name": "Phantasy Star II", "url": "https://www.sega.com/games/phantasy-star-ii"},
        {"name": "No More Heroes", "url": "https://www.nintendo.com/games/detail/no-more-heroes/"},
        {"name": "Shinobi", "url": "https://www.sega.com/games/shinobi"},
        {"name": "Puzzle Quest", "url": "https://en.wikipedia.org/wiki/Puzzle_Quest"},
        {"name": "Beneath a Steel Sky", "url": "https://revolution.co.uk/games/beneath-a-steel-sky"},
        {"name": "Theme Park", "url": "https://www.ea.com/games/theme-park"},
        {"name": "Oxenfree", "url": "https://www.nightstudios.com/oxenfree/"},
        {"name": "Device 6", "url": "https://simogo.com/work/device-6/"},
        {"name": "ARMA 3", "url": "https://www.arma3.com/"},
        {"name": "Mario & Luigi: Bowser's Inside Story", "url": "https://www.nintendo.com/games/detail/mario-and-luigi-bowsers-inside-story/"},
        {"name": "Pro Evolution Soccer 5", "url": "https://en.wikipedia.org/wiki/Pro_Evolution_Soccer_5"},
        {"name": "Forza Motorsport", "url": "https://www.xbox.com/en-US/games/forza-motorsport"},
        {"name": "Luigi's Mansion 3", "url": "https://www.nintendo.com/games/detail/luigis-mansion-3-switch/"},
        {"name": "Path of Exile", "url": "https://www.pathofexile.com/"},
        {"name": "Wing Commander II: Vengeance of the Kilrathi", "url": "https://en.wikipedia.org/wiki/Wing_Commander_II:_Vengeance_of_the_Kilrathi"},
        {"name": "Jet Force Gemini", "url": "https://www.nintendo.com/games/detail/jet-force-gemini/"},
        {"name": "Tekken 7", "url": "https://www.bandainamcoent.com/games/tekken-7"},
        {"name": "Total War: Warhammer II", "url": "https://www.totalwar.com/games/warhammer-ii/"},
        {"name": "Sin & Punishment: Successor to the Sky", "url": "https://www.nintendo.com/games/detail/sin-and-punishment-successor-of-the-skies/"},
        {"name": "Pac-Man Championship Edition DX", "url": "https://www.bandainamcoent.com/games/pac-man"},
        {"name": "BurgerTime", "url": "https://en.wikipedia.org/wiki/BurgerTime"},
        {"name": "Star Raiders", "url": "https://en.wikipedia.org/wiki/Star_Raiders"},
        {"name": "Final Fantasy V", "url": "https://www.square-enix-games.com/games/final-fantasy-v"},
        {"name": "Zero Escape: Virtue's Last Reward", "url": "https://www.spike-chunsoft.com/games/zero-escape/"},
        {"name": "Dragon Quest XI", "url": "https://www.square-enix-games.com/games/dragonquest"},
        {"name": "Blaster Master", "url": "https://www.sunsoftgames.com/blastermaster/"},
        {"name": "Luigi's Mansion 2", "url": "https://www.nintendo.com/games/detail/luigis-mansion-dark-moon/"},
        {"name": "The Outer Worlds", "url": "https://outerworlds.obsidian.net/"},
        {"name": "Banjo-Tooie", "url": "https://www.nintendo.com/games/detail/banjo-tooie/"},
        {"name": "Leisure Suit Larry in the Land of the Lounge Lizards", "url": "https://www.sierra.com/games/leisure-suit-larry/"},
        {"name": "Terraria", "url": "https://terraria.org/"},
        {"name": "Virtua Fighter 5", "url": "https://www.sega.com/games/virtua-fighter-5"},
        {"name": "Chuckie Egg", "url": "https://en.wikipedia.org/wiki/Chuckie_Egg"},
        {"name": "Crash Team Racing", "url": "https://www.crashbandicoot.com/crashteamracing"},
        {"name": "Jet Set Willy", "url": "https://en.wikipedia.org/wiki/Jet_Set_Willy"},
        {"name": "Fire Emblem: Path of Radiance", "url": "https://www.nintendo.com/games/detail/fire-emblem-path-of-radiance/"},
        {"name": "Heroes of Might and Magic III: The Restoration of Erathia", "url": "https://www.ubisoft.com/game/heroes-of-might-and-magic-iii"},
        {"name": "Catherine", "url": "https://www.atlus.com/catherine/"},
        {"name": "Gorogoa", "url": "https://gorogoa.com/"},
        {"name": "The Wonderful 101", "url": "https://www.platinumgames.com/games/the-wonderful-101"},
        {"name": "Overcooked", "url": "https://www.team17.com/games/overcooked/"},
        {"name": "Samba de Amigo", "url": "https://www.sega.com/games/samba-de-amigo"},
        {"name": "Pac-Man Championship Edition", "url": "https://www.bandainamcoent.com/games/pac-man"},
        {"name": "Shining Force III", "url": "https://www.sega.com/games/shining-force-iii"},
        {"name": "S.T.A.L.K.E.R.: Call of Pripyat", "url": "https://www.stalker-game.com/"},
        {"name": "Ratchet & Clank: Going Commando", "url": "https://www.playstation.com/en-us/games/ratchet-and-clank/"},
        {"name": "MVP Baseball 2005", "url": "https://en.wikipedia.org/wiki/MVP_Baseball_2005"},
        {"name": "FIFA 10", "url": "https://www.ea.com/games/fifa/fifa-10"},
        {"name": "The Elder Scrolls II: Daggerfall", "url": "https://elderscrolls.bethesda.net/"},
        {"name": "Nioh", "url": "https://teamninja-studio.com/nioh/"},
        {"name": "Klonoa: Door to Phantomile", "url": "https://www.bandainamcoent.com/games/klonoa"},
        {"name": "No More Heroes 2: Desperate Struggle", "url": "https://www.nintendo.com/games/detail/no-more-heroes-2-desperate-struggle/"},
        {"name": "Crimson Skies", "url": "https://en.wikipedia.org/wiki/Crimson_Skies"},
        {"name": "Mortal Kombat X", "url": "https://www.mortalkombat.com/"},
        {"name": "Infamous", "url": "https://www.playstation.com/en-us/games/infamous/"},
        {"name": "Brothers: A Tale of Two Sons", "url": "https://505games.com/games/brothers-a-tale-of-two-sons/"},
        {"name": "Kirby's Dream Land 2", "url": "https://www.nintendo.com/games/detail/kirbys-dream-land-2/"},
        {"name": "Super Mario Maker 2", "url": "https://www.nintendo.com/games/detail/super-mario-maker-2-switch/"},
        {"name": "Trials Evolution", "url": "https://www.ubisoft.com/game/trials-evolution"},
        {"name": "Dragon Force", "url": "https://en.wikipedia.org/wiki/Dragon_Force_(video_game)"},
        {"name": "Halo 3: ODST", "url": "https://www.halowaypoint.com/"},
        {"name": "Battlefield 4", "url": "https://www.ea.com/games/battlefield/battlefield-4"},
        {"name": "Donkey Kong Jr.", "url": "https://www.nintendo.com/games/detail/donkey-kong-jr/"},
        {"name": "Double Dragon II: The Revenge", "url": "https://www.arcsyss.co.jp/"},
        {"name": "Wipeout HD", "url": "https://www.playstation.com/en-us/games/wipeout-hd/"},
        {"name": "Tom Clancy's Rainbow Six 3: Raven Shield", "url": "https://www.ubisoft.com/game/rainbow-six-3-raven-shield"},
        {"name": "Sins of a Solar Empire", "url": "https://www.sinsofasolarempire.com/"},
        {"name": "Nintendogs", "url": "https://www.nintendo.com/games/detail/nintendogs/"},
        {"name": "Pokemon Crystal", "url": "https://www.pokemon.com/us/"},
        {"name": "Guild Wars", "url": "https://www.guildwars.com/"},
        {"name": "Gargoyle's Quest", "url": "https://en.wikipedia.org/wiki/Gargoyle%27s_Quest"},
        {"name": "Jak 3", "url": "https://www.playstation.com/en-us/games/jak-3/"},
        {"name": "Galaxian", "url": "https://www.bandainamcoent.com/games/galaxian"},
        {"name": "Driver", "url": "https://www.ubisoft.com/game/driver"},
        {"name": "Operation Flashpoint: Cold War Crisis", "url": "https://en.wikipedia.org/wiki/Operation_Flashpoint:_Cold_War_Crisis"},
        {"name": "Sly Cooper and the Thievius Raccoonus", "url": "https://www.playstation.com/en-us/games/sly-cooper-and-the-thievius-raccoonus/"},
        {"name": "Roller Coaster Tycoon", "url": "https://www.rollercoastertycoon.com/"},
        {"name": "The Binding of Isaac", "url": "https://www.bindingofisaac.com/"},
        {"name": "Astro Boy: Omega Factor", "url": "https://en.wikipedia.org/wiki/Astro_Boy:_Omega_Factor"},
        {"name": "Cannon Fodder", "url": "https://en.wikipedia.org/wiki/Cannon_Fodder_(video_game)"},
        {"name": "Machinarium", "url": "https://amanita-design.net/games/machinarium.html"},
        {"name": "Pokken Tournament", "url": "https://www.pokkentournament.com/"},
        {"name": "Thunder Force IV", "url": "https://en.wikipedia.org/wiki/Thunder_Force_IV"},
        {"name": "Gradius", "url": "https://www.konami.com/games/gradius/"},
        {"name": "Saints Row IV", "url": "https://www.saintsrow.com/games/saints-row-iv"},
        {"name": "Operation Wolf", "url": "https://en.wikipedia.org/wiki/Operation_Wolf"},
        {"name": "Guacamelee!", "url": "https://www.guacamelee.com/"},
        {"name": "Final Fantasy Adventure", "url": "https://www.square-enix-games.com/games/final-fantasy-adventure"},
        {"name": "God Hand", "url": "https://en.wikipedia.org/wiki/God_Hand"},
        {"name": "Gran Turismo 5", "url": "https://www.gran-turismo.com/"},
        {"name": "E.T. the Extra-Terrestrial", "url": "https://en.wikipedia.org/wiki/E.T._the_Extra-Terrestrial_(video_game)"},
        {"name": "Landstalker: The Treasures of King Nole", "url": "https://en.wikipedia.org/wiki/Landstalker"},
        {"name": "Warcraft: Orcs and Humans", "url": "https://en.wikipedia.org/wiki/Warcraft:_Orcs_%26_Humans"},
        {"name": "God of War: Ghost of Sparta", "url": "https://www.playstation.com/en-us/games/god-of-war-ghost-of-sparta/"},
        {"name": "Spyro 2: Ripto's Rage", "url": "https://www.spyrothedragon.com/"},
        {"name": "Lunar: Eternal Blue", "url": "https://en.wikipedia.org/wiki/Lunar:_Eternal_Blue"},
        {"name": "Far Cry 5", "url": "https://www.ubisoft.com/game/far-cry-5"},
        {"name": "Baba Is You", "url": "https://hempuli.com/baba/"},
        {"name": "SNK vs. Capcom: The Match of the Millennium", "url": "https://en.wikipedia.org/wiki/SNK_vs._Capcom:_The_Match_of_the_Millennium"},
        {"name": "The Legend of Zelda: Spirit Tracks", "url": "https://www.nintendo.com/games/detail/the-legend-of-zelda-spirit-tracks/"},
        {"name": "Star Wars Jedi: Fallen Order", "url": "https://www.ea.com/games/starwars/jedi-fallen-order"},
        {"name": "Steamworld Dig 2", "url": "https://www.imageform.se/game/steamworld-dig-2/"},
        {"name": "Valkyrie Profile", "url": "https://www.square-enix-games.com/games/valkyrie-profile"},
        {"name": "Tactics Ogre: Let Us Cling Together", "url": "https://en.wikipedia.org/wiki/Tactics_Ogre"},
        {"name": "Batman", "url": "https://en.wikipedia.org/wiki/Batman_(1989_video_game)"},
        {"name": "Wizball", "url": "https://en.wikipedia.org/wiki/Wizball"},
        {"name": "Kid Icarus: Uprising", "url": "https://www.nintendo.com/games/detail/kid-icarus-uprising/"},
        {"name": "International Karate +", "url": "https://en.wikipedia.org/wiki/International_Karate_Plus"},
        {"name": "Tearaway", "url": "https://www.playstation.com/en-us/games/tearaway/"},
        {"name": "To The Moon", "url": "https://freebirdgames.com/to-the-moon/"},
        {"name": "Micro Machines", "url": "https://en.wikipedia.org/wiki/Micro_Machines_(video_game)"},
        {"name": "Tekken 2", "url": "https://www.bandainamcoent.com/games/tekken-2"},
        {"name": "Phoenix Wright: Ace Attorney: Trials & Tribulations", "url": "https://www.capcom.com/games/phoenix-wright-ace-attorney-trials-and-tribulations"},
        {"name": "Gradius V", "url": "https://www.konami.com/games/gradius/"},
        {"name": "Pilotwings 64", "url": "https://www.nintendo.com/games/detail/pilotwings-64/"},
        {"name": "ChuChu Rocket!", "url": "https://www.sega.com/games/chuchu-rocket"},
        {"name": "Marathon", "url": "https://marathon.bungie.org/"},
        {"name": "Tetris DS", "url": "https://www.nintendo.com/games/detail/tetris-ds/"},
        {"name": "Little King's Story", "url": "https://en.wikipedia.org/wiki/Little_King%27s_Story"},
        {"name": "Defense of the Ancients", "url": "https://en.wikipedia.org/wiki/Defense_of_the_Ancients"},
        {"name": "Burnout: Revenge", "url": "https://www.ea.com/games/burnout/burnout-revenge"},
        {"name": "ToeJam & Earl", "url": "https://www.sega.com/games/toejam-and-earl"},
        {"name": "Half-Minute Hero", "url": "https://en.wikipedia.org/wiki/Half-Minute_Hero"},
        {"name": "Final Fantasy VII Remake", "url": "https://ffvii-remake.square-enix-games.com/"},
        {"name": "Final Fantasy II", "url": "https://www.square-enix-games.com/games/final-fantasy-ii"},
        {"name": "Illusion of Gaia", "url": "https://en.wikipedia.org/wiki/Illusion_of_Gaia"},
        {"name": "Watch Dogs 2", "url": "https://www.ubisoft.com/game/watch-dogs-2"},
        {"name": "The Legend of Zelda: Link's Awakening", "url": "https://www.nintendo.com/games/detail/the-legend-of-zelda-links-awakening-switch/"},
        {"name": "Half Life 2: Episode 2", "url": "https://www.half-life.com/en/"},
        {"name": "Ori and the Will of the Wisps", "url": "https://www.orithegame.com/"},
        {"name": "Gears 5", "url": "https://www.gearsofwar.com/"},
        {"name": "Audiosurf", "url": "https://audio-surf.com/"},
        {"name": "Star Wars: X-Wing", "url": "https://en.wikipedia.org/wiki/Star_Wars:_X-Wing"},
        {"name": "Advance Wars 2", "url": "https://www.nintendo.com/games/detail/advance-wars-2-black-hole-rising/"},
        {"name": "DOOM Eternal", "url": "https://slayersclub.bethesda.net/en/doom"},
        {"name": "Candy Crush Saga", "url": "https://www.king.com/game/candycrush"},
        {"name": "Rez Infinite", "url": "https://www.enhance-experience.com/rez"},
        {"name": "Wii Fit", "url": "https://www.nintendo.com/games/detail/wii-fit/"},
        {"name": "FIFA '09", "url": "https://www.ea.com/games/fifa/fifa-09"},
        {"name": "Max Payne 3", "url": "https://www.rockstargames.com/games/maxpayne3"},
        {"name": "Harvest Moon", "url": "https://en.wikipedia.org/wiki/Harvest_Moon_(video_game)"},
        {"name": "Desert Strike: Return to the Gulf", "url": "https://en.wikipedia.org/wiki/Desert_Strike"},
        {"name": "The Binding of Isaac: Rebirth", "url": "https://www.bindingofisaac.com/"},
        {"name": "Snake", "url": "https://en.wikipedia.org/wiki/Snake_(video_game_genre)"},
        {"name": "Bravely Default", "url": "https://square-enix-games.com/games/bravely-default"},
        {"name": "Hyper Light Drifter", "url": "https://www.heart-machine.com/hyper-light-drifter"},
        {"name": "The Need for Speed", "url": "https://en.wikipedia.org/wiki/The_Need_for_Speed"},
        {"name": "Tom Clancy's Rainbow Six: Vegas", "url": "https://www.ubisoft.com/game/rainbow-six-vegas"},
        {"name": "Salamander", "url": "https://en.wikipedia.org/wiki/Salamander_(video_game)"},
        {"name": "Zombies Ate My Neighbors", "url": "https://en.wikipedia.org/wiki/Zombies_Ate_My_Neighbors"},
        {"name": "Sanitarium", "url": "https://en.wikipedia.org/wiki/Sanitarium_(video_game)"},
        {"name": "Tenchu: Stealth Assassins", "url": "https://en.wikipedia.org/wiki/Tenchu:_Stealth_Assassins"},
        {"name": "Snatcher", "url": "https://en.wikipedia.org/wiki/Snatcher_(video_game)"},
        {"name": "Ninja Gaiden II: The Dark Sword of Chaos", "url": "https://en.wikipedia.org/wiki/Ninja_Gaiden_II:_The_Dark_Sword_of_Chaos"},
        {"name": "Alex Kidd in Miracle World", "url": "https://en.wikipedia.org/wiki/Alex_Kidd_in_Miracle_World"},
        {"name": "Red Baron", "url": "https://en.wikipedia.org/wiki/Red_Baron_(1990_video_game)"},
        {"name": "Breakout", "url": "https://en.wikipedia.org/wiki/Breakout_(video_game)"},
        {"name": "Monster Hunter 3 Ultimate", "url": "https://www.monsterhunter.com/"},
        {"name": "Metro 2033", "url": "https://www.metrothegame.com/"},
        {"name": "Space Channel 5", "url": "https://en.wikipedia.org/wiki/Space_Channel_5"},
        {"name": "Ultima V: Warriors of Destiny", "url": "https://en.wikipedia.org/wiki/Ultima_V:_Warriors_of_Destiny"},
        {"name": "Warhammer 40,000: Dawn of War II", "url": "https://www.dawnofwar.com/"},
        {"name": "Mario Kart: Super Circuit", "url": "https://www.nintendo.com/games/detail/mario-kart-super-circuit/"},
        {"name": "Outcast", "url": "https://en.wikipedia.org/wiki/Outcast_(video_game)"},
        {"name": "Planetside 2", "url": "https://www.planetside2.com/"},
        {"name": "Star Wars", "url": "https://en.wikipedia.org/wiki/Star_Wars_(1991_video_game)"},
        {"name": "DEFCON", "url": "https://www.introversion.co.uk/defcon/"},
        {"name": "The Talos Principle", "url": "https://www.croteam.com/talosprinciple/"},
        {"name": "Turok: Dinosaur Hunter", "url": "https://en.wikipedia.org/wiki/Turok:_Dinosaur_Hunter"},
        {"name": "The Wolf Among Us", "url": "https://telltale.com/the-wolf-among-us/"},
        {"name": "The Witcher", "url": "https://www.thewitcher.com/"},
        {"name": "Myth: The Fallen Lords", "url": "https://en.wikipedia.org/wiki/Myth:_The_Fallen_Lords"},
        {"name": "TimeSplitters: Future Perfect", "url": "https://en.wikipedia.org/wiki/TimeSplitters:_Future_Perfect"},
        {"name": "Axiom Verge", "url": "https://www.axiomverge.com/"},
        {"name": "The Dig", "url": "https://en.wikipedia.org/wiki/The_Dig_(video_game)"},
        {"name": "Danganronpa: Trigger Happy Havoc", "url": "https://www.spike-chunsoft.com/games/danganronpa"},
        {"name": "Capcom vs SNK 2 (EO)", "url": "https://www.capcom.com/games/capcom-vs-snk-2"},
        {"name": "Lunar: The Silver Star", "url": "https://en.wikipedia.org/wiki/Lunar:_The_Silver_Star"},
        {"name": "Panzer General", "url": "https://en.wikipedia.org/wiki/Panzer_General"},
        {"name": "Kirby Canvas Curse", "url": "https://www.nintendo.com/games/detail/kirby-canvas-curse/"},
        {"name": "Warframe", "url": "https://www.warframe.com/"},
        {"name": "Mario & Luigi: Partners in Time", "url": "https://www.nintendo.com/games/detail/mario-and-luigi-partners-in-time/"},
        {"name": "Cadence of Hyrule", "url": "https://www.nintendo.com/games/detail/cadence-of-hyrule-crypt-of-the-necrodancer-featuring-the-legend-of-zelda/"},
        {"name": "Star Wars Episode I: Racer", "url": "https://www.nintendo.com/games/detail/star-wars-episode-i-racer/"},
        {"name": "Axelay", "url": "https://en.wikipedia.org/wiki/Axelay"},
        {"name": "Owlboy", "url": "https://www.owlboygame.com/"},
        {"name": "Ghost of Tsushima", "url": "https://www.playstation.com/en-us/games/ghost-of-tsushima/"},
        {"name": "No One Lives Forever 2: A Spy in H.A.R.M.'s Way", "url": "https://en.wikipedia.org/wiki/No_One_Lives_Forever_2:_A_Spy_in_H.A.R.M.%27s_Way"},
        {"name": "Black", "url": "https://en.wikipedia.org/wiki/Black_(video_game)"},
        {"name": "Track & Field", "url": "https://en.wikipedia.org/wiki/Track_%26_Field_(video_game)"}
    ]
};